version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    target-branch: master
    schedule:
      interval: weekly
    groups:
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
