import type { VendorProduct } from './model'
import { REPOSITORY_SOURCES } from './sources'
import { validateRepositoryCatalog } from './validate'

function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === 'object') {
    Object.values(value).forEach((child) => deepFreeze(child))
    Object.freeze(value)
  }
  return value
}

const catalog: VendorProduct[] = [
  { id: 'brave-browser', sourceId: 'brave-browser', name: 'Brave Browser', category: 'browser', icon: 'mdi-shield-check', packages: ['brave-browser'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'mozilla-firefox', sourceId: 'mozilla', name: 'Mozilla Firefox', category: 'browser', icon: 'mdi-firefox', packages: ['firefox'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'google-chrome', sourceId: 'google-chrome', name: 'Google Chrome', category: 'browser', icon: 'mdi-google-chrome', packages: ['google-chrome-stable'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'microsoft-edge', sourceId: 'microsoft-edge', name: 'Microsoft Edge', category: 'browser', icon: 'mdi-microsoft-edge', packages: ['microsoft-edge-stable'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'vivaldi', sourceId: 'vivaldi', name: 'Vivaldi', category: 'browser', icon: 'mdi-compass-outline', packages: ['vivaldi-stable'], supportedReleases: ['trixie', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'opera', sourceId: 'opera', name: 'Opera', category: 'browser', icon: 'mdi-opera', packages: ['opera-stable'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'signal-desktop', sourceId: 'signal', name: 'Signal Desktop', category: 'communication', icon: 'mdi-message-lock-outline', packages: ['signal-desktop'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'proton-vpn', sourceId: 'proton-vpn', name: 'Proton VPN', category: 'privacy', icon: 'mdi-shield-lock-outline', packages: ['proton-vpn-gnome-desktop'], supportedReleases: ['trixie'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['proton-vpn-supported-environment'], verifiedAt: '2026-08-28' },
  { id: 'mullvad-vpn', sourceId: 'mullvad', name: 'Mullvad VPN', category: 'privacy', icon: 'mdi-vpn', packages: ['mullvad-vpn'], supportedReleases: ['trixie', 'bookworm', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'tor', sourceId: 'tor', name: 'Tor', category: 'privacy', icon: 'mdi-incognito', packages: ['tor'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: ['tor-not-browser'], verifiedAt: '2026-08-28' },
  { id: 'docker-engine', sourceId: 'docker', name: 'Docker Engine', category: 'containers', icon: 'mdi-docker', packages: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', 'docker-compose-plugin'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64', 'armhf'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['docker-firewall'], verifiedAt: '2026-08-28' },
  { id: 'kubernetes-tools-v1-36', sourceId: 'kubernetes-v1-36', name: 'Kubernetes tools v1.36', category: 'containers', icon: 'mdi-ship-wheel', packages: ['kubectl'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'google-cloud-cli', sourceId: 'google-cloud', name: 'Google Cloud CLI', category: 'cloud', icon: 'mdi-google-cloud', packages: ['google-cloud-cli'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'azure-cli', sourceId: 'microsoft-azure-cli', name: 'Microsoft Azure CLI', category: 'cloud', icon: 'mdi-microsoft-azure', packages: ['azure-cli'], supportedReleases: ['bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'github-cli', sourceId: 'github-cli', name: 'GitHub CLI', category: 'development', icon: 'mdi-github', packages: ['gh'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'hashicorp-terraform', sourceId: 'hashicorp', name: 'HashiCorp Terraform', category: 'development', icon: 'mdi-terraform', packages: ['terraform'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'postgresql-pgdg', sourceId: 'postgresql-pgdg', name: 'PostgreSQL PGDG', category: 'database', icon: 'mdi-elephant', packages: ['postgresql'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'mongodb-community-8-0', sourceId: 'mongodb-community-8-0', name: 'MongoDB Community 8.0', category: 'database', icon: 'mdi-leaf', packages: ['mongodb-org'], supportedReleases: ['bookworm'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'grafana', sourceId: 'grafana', name: 'Grafana', category: 'monitoring', icon: 'mdi-chart-timeline-variant', packages: ['grafana'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'nvidia-container-toolkit', sourceId: 'nvidia-container-toolkit', name: 'NVIDIA Container Toolkit', category: 'containers', icon: 'mdi-chip', packages: ['nvidia-container-toolkit'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['nvidia-container-toolkit-prerequisites'], verifiedAt: '2026-08-28' },
  { id: 'mariadb-community-11-8', sourceId: 'mariadb-community-11-8', name: 'MariaDB Community 11.8', category: 'database', icon: 'mdi-database-cog', packages: ['mariadb-server'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['mariadb-no-setup-script'], verifiedAt: '2026-08-28' },
  { id: 'redis-open-source', sourceId: 'redis-open-source', name: 'Redis Open Source', category: 'database', icon: 'mdi-database-outline', packages: ['redis'], supportedReleases: ['trixie', 'bookworm'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'clickhouse', sourceId: 'clickhouse', name: 'ClickHouse', category: 'database', icon: 'mdi-database-arrow-right-outline', packages: ['clickhouse-server', 'clickhouse-client'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['clickhouse-generic-debian'], verifiedAt: '2026-08-28' },
  { id: 'influxdb-3-core', sourceId: 'influxdb-3-core', name: 'InfluxDB 3 Core', category: 'monitoring', icon: 'mdi-chart-areaspline', packages: ['influxdb3-core'], supportedReleases: ['trixie', 'bookworm', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
  { id: 'zabbix-7-4', sourceId: 'zabbix-7-4', name: 'Zabbix 7.4', category: 'monitoring', icon: 'mdi-server-security', packages: ['zabbix-agent2'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [], verifiedAt: '2026-08-28' },
]

validateRepositoryCatalog(REPOSITORY_SOURCES, catalog)

export const VENDOR_PRODUCTS: readonly VendorProduct[] = deepFreeze(catalog)

export function getVendorProduct(id: string): VendorProduct | undefined {
  return VENDOR_PRODUCTS.find((product) => product.id === id)
}
