import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { VENDOR_PRODUCTS, getVendorProduct } from './catalog'
import type { VendorProduct } from './model'
import { REPOSITORY_SOURCES } from './sources'
import { validateRepositoryCatalog } from './validate'

const expectedProducts = [
  { id: 'brave-browser', sourceId: 'brave-browser', name: 'Brave Browser', category: 'web-browsers', icon: 'mdi-shield-check', packages: ['brave-browser'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'mozilla-firefox', sourceId: 'mozilla', name: 'Mozilla Firefox', category: 'web-browsers', icon: 'mdi-firefox', packages: ['firefox'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'google-chrome', sourceId: 'google-chrome', name: 'Google Chrome', category: 'web-browsers', icon: 'mdi-google-chrome', packages: ['google-chrome-stable'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'microsoft-edge', sourceId: 'microsoft-edge', name: 'Microsoft Edge', category: 'web-browsers', icon: 'mdi-microsoft-edge', packages: ['microsoft-edge-stable'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'vivaldi', sourceId: 'vivaldi', name: 'Vivaldi', category: 'web-browsers', icon: 'mdi-compass-outline', packages: ['vivaldi-stable'], supportedReleases: ['trixie', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'opera', sourceId: 'opera', name: 'Opera', category: 'web-browsers', icon: 'mdi-opera', packages: ['opera-stable'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'signal-desktop', sourceId: 'signal', name: 'Signal Desktop', category: 'messaging-email', icon: 'mdi-message-lock-outline', packages: ['signal-desktop'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'proton-vpn', sourceId: 'proton-vpn', name: 'Proton VPN', category: 'vpn-secure-networking', icon: 'mdi-shield-lock-outline', packages: ['proton-vpn-gnome-desktop'], supportedReleases: ['trixie'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['proton-vpn-supported-environment'] },
  { id: 'mullvad-vpn', sourceId: 'mullvad', name: 'Mullvad VPN', category: 'vpn-secure-networking', icon: 'mdi-vpn', packages: ['mullvad-vpn'], supportedReleases: ['trixie', 'bookworm', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'tor', sourceId: 'tor', name: 'Tor', category: 'vpn-secure-networking', icon: 'mdi-incognito', packages: ['tor'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: ['tor-not-browser'] },
  { id: 'docker-engine', sourceId: 'docker', name: 'Docker Engine', category: 'containers-kubernetes', icon: 'mdi-docker', packages: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', 'docker-compose-plugin'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64', 'armhf'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['docker-firewall'] },
  { id: 'kubernetes-tools-v1-36', sourceId: 'kubernetes-v1-36', name: 'Kubernetes tools v1.36', category: 'containers-kubernetes', icon: 'mdi-ship-wheel', packages: ['kubectl'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'google-cloud-cli', sourceId: 'google-cloud', name: 'Google Cloud CLI', category: 'cloud-edge', icon: 'mdi-google-cloud', packages: ['google-cloud-cli'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'azure-cli', sourceId: 'microsoft-azure-cli', name: 'Microsoft Azure CLI', category: 'cloud-edge', icon: 'mdi-microsoft-azure', packages: ['azure-cli'], supportedReleases: ['bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'github-cli', sourceId: 'github-cli', name: 'GitHub CLI', category: 'developer-workstation', icon: 'mdi-github', packages: ['gh'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'hashicorp-terraform', sourceId: 'hashicorp', name: 'HashiCorp Terraform', category: 'infrastructure-automation', icon: 'mdi-terraform', packages: ['terraform'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'postgresql-pgdg', sourceId: 'postgresql-pgdg', name: 'PostgreSQL PGDG', category: 'data-platforms', icon: 'mdi-elephant', packages: ['postgresql'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'mongodb-community-8-0', sourceId: 'mongodb-community-8-0', name: 'MongoDB Community 8.0', category: 'data-platforms', icon: 'mdi-leaf', packages: ['mongodb-org'], supportedReleases: ['bookworm'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'grafana', sourceId: 'grafana', name: 'Grafana', category: 'observability-logging', icon: 'mdi-chart-timeline-variant', packages: ['grafana'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'nvidia-container-toolkit', sourceId: 'nvidia-container-toolkit', name: 'NVIDIA Container Toolkit', category: 'containers-kubernetes', icon: 'mdi-chip', packages: ['nvidia-container-toolkit'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['nvidia-container-toolkit-prerequisites'] },
  { id: 'mariadb-community-11-8', sourceId: 'mariadb-community-11-8', name: 'MariaDB Community 11.8', category: 'data-platforms', icon: 'mdi-database-cog', packages: ['mariadb-server'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['mariadb-no-setup-script'] },
  { id: 'redis-open-source', sourceId: 'redis-open-source', name: 'Redis Open Source', category: 'data-platforms', icon: 'mdi-database-outline', packages: ['redis'], supportedReleases: ['trixie', 'bookworm'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'clickhouse', sourceId: 'clickhouse', name: 'ClickHouse', category: 'data-platforms', icon: 'mdi-database-arrow-right-outline', packages: ['clickhouse-server', 'clickhouse-client'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: ['clickhouse-generic-debian'] },
  { id: 'influxdb-3-core', sourceId: 'influxdb-3-core', name: 'InfluxDB 3 Core', category: 'observability-logging', icon: 'mdi-chart-areaspline', packages: ['influxdb3-core'], supportedReleases: ['trixie', 'bookworm', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'zabbix-7-4', sourceId: 'zabbix-7-4', name: 'Zabbix 7.4', category: 'observability-logging', icon: 'mdi-server-security', packages: ['zabbix-agent2'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'mullvad-browser', sourceId: 'mullvad', name: 'Mullvad Browser', category: 'web-browsers', icon: 'mdi-web', packages: ['mullvad-browser'], supportedReleases: ['trixie', 'bookworm'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'onepassword', sourceId: 'onepassword', name: '1Password', category: 'security-secrets', icon: 'mdi-shield-lock-outline', packages: ['1password'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'visual-studio-code', sourceId: 'visual-studio-code', name: 'Visual Studio Code', category: 'developer-workstation', icon: 'mdi-code-tags', packages: ['code'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64', 'armhf'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'powershell-7-6', sourceId: 'microsoft-prod', name: 'PowerShell 7.6', category: 'developer-workstation', icon: 'mdi-code-tags', packages: ['powershell'], supportedReleases: ['trixie'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'dotnet-sdk-10', sourceId: 'microsoft-prod', name: '.NET SDK 10', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['dotnet-sdk-10.0'], supportedReleases: ['trixie', 'bookworm'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'tailscale', sourceId: 'tailscale', name: 'Tailscale', category: 'vpn-secure-networking', icon: 'mdi-vpn', packages: ['tailscale'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64', 'armhf', 'i386'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'cloudflare-warp', sourceId: 'cloudflare-warp', name: 'Cloudflare WARP', category: 'vpn-secure-networking', icon: 'mdi-shield-lock-outline', packages: ['cloudflare-warp'], supportedReleases: ['trixie', 'bookworm'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'cloudflared', sourceId: 'cloudflared', name: 'cloudflared', category: 'cloud-edge', icon: 'mdi-cloud-outline', packages: ['cloudflared'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64', 'armhf'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'opentofu', sourceId: 'opentofu', name: 'OpenTofu', category: 'infrastructure-automation', icon: 'mdi-code-tags', packages: ['tofu'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64', 'armhf', 'i386'], supportLevel: 'generic-debian', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'anydesk', sourceId: 'anydesk', name: 'AnyDesk', category: 'remote-desktop', icon: 'mdi-message-text-outline', packages: ['anydesk'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'sublime-text', sourceId: 'sublime', name: 'Sublime Text', category: 'developer-workstation', icon: 'mdi-code-tags', packages: ['sublime-text'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: false, warningKeys: [] },
  { id: 'element-desktop', sourceId: 'element', name: 'Element Desktop', category: 'messaging-email', icon: 'mdi-message-text-outline', packages: ['element-desktop'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'oracle-virtualbox-7-2', sourceId: 'oracle-virtualbox', name: 'Oracle VirtualBox 7.2', category: 'virtualization', icon: 'mdi-cube-outline', packages: ['virtualbox-7.2'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'gitlab-ce', sourceId: 'gitlab-ce', name: 'GitLab Community Edition', category: 'development-platforms-cicd', icon: 'mdi-code-tags', packages: ['gitlab-ce'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['gitlab-server-prerequisites'] },
  { id: 'gitlab-runner', sourceId: 'gitlab-runner', name: 'GitLab Runner', category: 'development-platforms-cicd', icon: 'mdi-code-tags', packages: ['gitlab-runner'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'jenkins-lts', sourceId: 'jenkins-lts', name: 'Jenkins LTS', category: 'development-platforms-cicd', icon: 'mdi-code-tags', packages: ['jenkins'], supportedReleases: ['trixie'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: ['jenkins-java-prerequisite'] },
  { id: 'nginx-stable', sourceId: 'nginx-stable', name: 'NGINX Stable', category: 'web-servers', icon: 'mdi-cloud-outline', packages: ['nginx'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'hashicorp-vault', sourceId: 'hashicorp', name: 'HashiCorp Vault', category: 'security-secrets', icon: 'mdi-terraform', packages: ['vault'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'hashicorp-packer', sourceId: 'hashicorp', name: 'HashiCorp Packer', category: 'infrastructure-automation', icon: 'mdi-terraform', packages: ['packer'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'elastic-stack-9', sourceId: 'elastic-9', name: 'Elastic Stack 9', category: 'observability-logging', icon: 'mdi-chart-line', packages: ['elasticsearch', 'kibana', 'logstash', 'filebeat'], supportedReleases: ['trixie', 'bookworm'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['elastic-stack-resource-requirements'] },
  { id: 'syncthing-stable-v2', sourceId: 'syncthing', name: 'Syncthing Stable v2', category: 'file-synchronization', icon: 'mdi-cloud-outline', packages: ['syncthing'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64', 'armhf'], supportLevel: 'generic-debian', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'amazon-corretto-21', sourceId: 'corretto', name: 'Amazon Corretto 21', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['java-21-amazon-corretto-jdk'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'eclipse-temurin-25', sourceId: 'adoptium', name: 'Eclipse Temurin 25', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['temurin-25-jdk'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'grafana-alloy', sourceId: 'grafana', name: 'Grafana Alloy', category: 'observability-logging', icon: 'mdi-chart-line', packages: ['alloy'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'caddy', sourceId: 'caddy', name: 'Caddy', category: 'web-servers', icon: 'mdi-cloud-outline', packages: ['caddy'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64', 'armhf'], supportLevel: 'generic-debian', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'zerotier-one', sourceId: 'zerotier-one', name: 'ZeroTier One', category: 'vpn-secure-networking', icon: 'mdi-vpn', packages: ['zerotier-one'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64', 'armhf', 'i386'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'yarn-classic-1', sourceId: 'yarn', name: 'Yarn Classic 1.x', category: 'developer-workstation', icon: 'mdi-code-tags', packages: ['yarn'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64', 'armhf', 'i386'], supportLevel: 'generic-debian', provenance: 'upstream', securityCritical: true, warningKeys: ['yarn-classic-only'] },
  { id: 'netbird', sourceId: 'netbird', name: 'NetBird', category: 'vpn-secure-networking', icon: 'mdi-vpn', packages: ['netbird'], supportedReleases: ['bookworm'], supportedArchitectures: ['amd64', 'arm64', 'armhf'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'mozilla-thunderbird', sourceId: 'mozilla-thunderbird', name: 'Mozilla Thunderbird', category: 'messaging-email', icon: 'mdi-message-text-outline', packages: ['thunderbird'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'firefox-developer-edition', sourceId: 'mozilla', name: 'Firefox Developer Edition', category: 'web-browsers', icon: 'mdi-firefox', packages: ['firefox-devedition'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'onepassword-cli', sourceId: 'onepassword', name: '1Password CLI', category: 'security-secrets', icon: 'mdi-shield-lock-outline', packages: ['1password-cli'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'gitlab-ee', sourceId: 'gitlab-ee', name: 'GitLab Enterprise Edition', category: 'development-platforms-cicd', icon: 'mdi-code-tags', packages: ['gitlab-ee'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['gitlab-server-prerequisites'] },
  { id: 'jenkins-weekly', sourceId: 'jenkins-weekly', name: 'Jenkins Weekly', category: 'development-platforms-cicd', icon: 'mdi-code-tags', packages: ['jenkins'], supportedReleases: ['trixie'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: ['jenkins-java-prerequisite'] },
  { id: 'nginx-mainline', sourceId: 'nginx-mainline', name: 'NGINX Mainline', category: 'web-servers', icon: 'mdi-cloud-outline', packages: ['nginx'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'grafana-enterprise', sourceId: 'grafana', name: 'Grafana Enterprise', category: 'observability-logging', icon: 'mdi-chart-line', packages: ['grafana-enterprise'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'hashicorp-consul', sourceId: 'hashicorp', name: 'HashiCorp Consul', category: 'infrastructure-automation', icon: 'mdi-terraform', packages: ['consul'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'hashicorp-nomad', sourceId: 'hashicorp', name: 'HashiCorp Nomad', category: 'infrastructure-automation', icon: 'mdi-terraform', packages: ['nomad'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'hashicorp-boundary', sourceId: 'hashicorp', name: 'HashiCorp Boundary', category: 'infrastructure-automation', icon: 'mdi-terraform', packages: ['boundary'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'elastic-agent-9', sourceId: 'elastic-9', name: 'Elastic Agent 9', category: 'observability-logging', icon: 'mdi-chart-line', packages: ['elastic-agent'], supportedReleases: ['trixie', 'bookworm'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['elastic-agent-enrollment'] },
  { id: 'kubernetes-node-tools-v1-36', sourceId: 'kubernetes-v1-36', name: 'Kubernetes Node Tools 1.36', category: 'containers-kubernetes', icon: 'mdi-ship-wheel', packages: ['kubelet', 'kubeadm'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: ['kubernetes-node-configuration'] },
  { id: 'microsoft-openjdk-21', sourceId: 'microsoft-prod', name: 'Microsoft OpenJDK 21', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['msopenjdk-21'], supportedReleases: ['bookworm'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'microsoft-openjdk-25', sourceId: 'microsoft-prod', name: 'Microsoft OpenJDK 25', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['msopenjdk-25'], supportedReleases: ['bookworm'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'eclipse-temurin-8', sourceId: 'adoptium', name: 'Eclipse Temurin 8', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['temurin-8-jdk'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'eclipse-temurin-11', sourceId: 'adoptium', name: 'Eclipse Temurin 11', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['temurin-11-jdk'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'eclipse-temurin-17', sourceId: 'adoptium', name: 'Eclipse Temurin 17', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['temurin-17-jdk'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'eclipse-temurin-21', sourceId: 'adoptium', name: 'Eclipse Temurin 21', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['temurin-21-jdk'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'amazon-corretto-8', sourceId: 'corretto', name: 'Amazon Corretto 8', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['java-1.8.0-amazon-corretto-jdk'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'amazon-corretto-11', sourceId: 'corretto', name: 'Amazon Corretto 11', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['java-11-amazon-corretto-jdk'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'amazon-corretto-17', sourceId: 'corretto', name: 'Amazon Corretto 17', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['java-17-amazon-corretto-jdk'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'amazon-corretto-25', sourceId: 'corretto', name: 'Amazon Corretto 25', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['java-25-amazon-corretto-jdk'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'azul-zulu-jdk-21', sourceId: 'azul-zulu', name: 'Azul Zulu JDK 21', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['zulu21-jdk'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'bellsoft-liberica-jdk-21', sourceId: 'bellsoft-liberica', name: 'BellSoft Liberica JDK 21', category: 'runtimes-sdks', icon: 'mdi-code-tags', packages: ['bellsoft-java21'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'teamviewer', sourceId: 'teamviewer', name: 'TeamViewer', category: 'remote-desktop', icon: 'mdi-message-text-outline', packages: ['teamviewer'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'steam-launcher', sourceId: 'steam', name: 'Steam Launcher', category: 'games', icon: 'mdi-code-tags', packages: ['steam-launcher'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: false, warningKeys: ['steam-i386-multiarch'] },
  { id: 'google-earth-pro', sourceId: 'google-earth', name: 'Google Earth Pro', category: 'desktop-productivity', icon: 'mdi-web', packages: ['google-earth-pro-stable'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: false, warningKeys: [] },
  { id: 'sublime-merge', sourceId: 'sublime', name: 'Sublime Merge', category: 'developer-workstation', icon: 'mdi-code-tags', packages: ['sublime-merge'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: false, warningKeys: [] },
  { id: 'typora', sourceId: 'typora', name: 'Typora', category: 'desktop-productivity', icon: 'mdi-code-tags', packages: ['typora'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: false, warningKeys: [] },
  { id: 'warp-terminal', sourceId: 'warp', name: 'Warp Terminal', category: 'developer-workstation', icon: 'mdi-code-tags', packages: ['warp-terminal'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: false, warningKeys: [] },
  { id: 'nordvpn', sourceId: 'nordvpn', name: 'NordVPN', category: 'vpn-secure-networking', icon: 'mdi-vpn', packages: ['nordvpn'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'ivpn', sourceId: 'ivpn', name: 'IVPN', category: 'vpn-secure-networking', icon: 'mdi-vpn', packages: ['ivpn'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'teleport-community-18', sourceId: 'teleport-18', name: 'Teleport Community Edition 18', category: 'vpn-secure-networking', icon: 'mdi-shield-lock-outline', packages: ['teleport'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'wazuh-agent', sourceId: 'wazuh', name: 'Wazuh Agent', category: 'security-secrets', icon: 'mdi-server-security', packages: ['wazuh-agent'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64', 'i386'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: ['wazuh-manager-enrollment'] },
  { id: 'apache-couchdb-3-5', sourceId: 'apache-couchdb', name: 'Apache CouchDB 3.5', category: 'data-platforms', icon: 'mdi-database-outline', packages: ['couchdb'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: ['couchdb-interactive-configuration'] },
  { id: 'neo4j-community', sourceId: 'neo4j', name: 'Neo4j Community Edition', category: 'data-platforms', icon: 'mdi-database-outline', packages: ['neo4j'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'icinga2', sourceId: 'icinga', name: 'Icinga 2', category: 'observability-logging', icon: 'mdi-chart-line', packages: ['icinga2'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'mysql-community-server-8-4-lts', sourceId: 'mysql-8-4', name: 'MySQL Community Server 8.4 LTS', category: 'data-platforms', icon: 'mdi-database-outline', packages: ['mysql-server'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64'], supportLevel: 'explicit', provenance: 'manufacturer', securityCritical: true, warningKeys: ['mysql-interactive-configuration'] },
  { id: 'opensearch-3', sourceId: 'opensearch-3', name: 'OpenSearch 3', category: 'data-platforms', icon: 'mdi-database-outline', packages: ['opensearch'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'upstream', securityCritical: true, warningKeys: ['opensearch-security-bootstrap'] },
  { id: 'datadog-agent-7', sourceId: 'datadog', name: 'Datadog Agent 7', category: 'observability-logging', icon: 'mdi-chart-line', packages: ['datadog-agent'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: ['datadog-api-key-required'] },
  { id: 'falco', sourceId: 'falco', name: 'Falco', category: 'security-secrets', icon: 'mdi-server-security', packages: ['falco'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'upstream', securityCritical: true, warningKeys: ['falco-driver-setup'] },
  { id: 'trivy', sourceId: 'trivy', name: 'Trivy', category: 'security-secrets', icon: 'mdi-shield-check', packages: ['trivy'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'crowdsec-security-engine', sourceId: 'crowdsec', name: 'CrowdSec Security Engine', category: 'security-secrets', icon: 'mdi-shield-check', packages: ['crowdsec'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
  { id: 'fluent-bit', sourceId: 'fluent-bit', name: 'Fluent Bit', category: 'observability-logging', icon: 'mdi-chart-line', packages: ['fluent-bit'], supportedReleases: ['trixie', 'bookworm', 'bullseye'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'explicit', provenance: 'upstream', securityCritical: true, warningKeys: [] },
  { id: 'dbeaver-community', sourceId: 'dbeaver', name: 'DBeaver Community', category: 'data-platforms', icon: 'mdi-database-outline', packages: ['dbeaver-ce'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'upstream', securityCritical: false, warningKeys: [] },
  { id: 'buildkite-agent', sourceId: 'buildkite-agent', name: 'Buildkite Agent', category: 'development-platforms-cicd', icon: 'mdi-code-tags', packages: ['buildkite-agent'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: ['buildkite-agent-token-required'] },
  { id: 'buildkite-cli', sourceId: 'buildkite-cli', name: 'Buildkite CLI', category: 'development-platforms-cicd', icon: 'mdi-code-tags', packages: ['bk'], supportedReleases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'], supportedArchitectures: ['amd64', 'arm64'], supportLevel: 'generic-debian', provenance: 'manufacturer', securityCritical: true, warningKeys: [] },
] as const satisfies readonly VendorProduct[]

describe('100-product vendor catalog', () => {
  it('matches the exact authoritative metadata table in approved order', () => {
    expect(VENDOR_PRODUCTS).toHaveLength(100)
    expect(VENDOR_PRODUCTS).toEqual(expectedProducts)
  })

  it('uses the strict immutable product contract and validates against the repository catalog', () => {
    expect(() => validateRepositoryCatalog(REPOSITORY_SOURCES, VENDOR_PRODUCTS)).not.toThrow()
    expect(Object.isFrozen(VENDOR_PRODUCTS)).toBe(true)
    expect(VENDOR_PRODUCTS.every(Object.isFrozen)).toBe(true)
    for (const product of VENDOR_PRODUCTS) {
      expect(product.warningKeys).toEqual(expect.any(Array))
      expect(product.sourceId).toEqual(expect.any(String))
      expect(product.provenance).not.toBe('debian-native')
      if (product.securityCritical) expect(product.provenance).not.toBe('community-endorsed')
      const source = REPOSITORY_SOURCES.find((candidate) => candidate.id === product.sourceId)
      expect(source?.locations.map((location) => location.supportLevel)).toContain(product.supportLevel)
    }
    expect(REPOSITORY_SOURCES.some((source) => /nodesource/i.test(`${source.id} ${source.name} ${source.documentationUrl}`))).toBe(false)
  })

  it('uses the closed researched category taxonomy and exact membership counts', () => {
    expect([...new Set(VENDOR_PRODUCTS.map((product) => product.category))]).toEqual([
      'web-browsers',
      'messaging-email',
      'vpn-secure-networking',
      'containers-kubernetes',
      'cloud-edge',
      'developer-workstation',
      'infrastructure-automation',
      'data-platforms',
      'observability-logging',
      'security-secrets',
      'runtimes-sdks',
      'remote-desktop',
      'virtualization',
      'development-platforms-cicd',
      'web-servers',
      'file-synchronization',
      'games',
      'desktop-productivity',
    ])
    expect(Object.fromEntries([
      ...new Set(VENDOR_PRODUCTS.map((product) => product.category)),
    ].map((category) => [
      category,
      VENDOR_PRODUCTS.filter((product) => product.category === category).length,
    ]))).toEqual({
      'web-browsers': 8,
      'messaging-email': 3,
      'vpn-secure-networking': 10,
      'containers-kubernetes': 4,
      'cloud-edge': 3,
      'developer-workstation': 7,
      'infrastructure-automation': 6,
      'data-platforms': 10,
      'observability-logging': 10,
      'security-secrets': 7,
      'runtimes-sdks': 15,
      'remote-desktop': 2,
      'virtualization': 1,
      'development-platforms-cicd': 7,
      'web-servers': 3,
      'file-synchronization': 1,
      games: 1,
      'desktop-productivity': 2,
    })
  })

  it('uses product icons included in the bundled Material-Design font', () => {
    const require = createRequire(import.meta.url)
    const mdiCss = readFileSync(require.resolve('@mdi/font/css/materialdesignicons.css'), 'utf8')

    for (const product of VENDOR_PRODUCTS) expect(mdiCss).toContain(`.${product.icon}::before`)
  })

  it('looks up known products and leaves unknown IDs unresolved', () => {
    expect(getVendorProduct('docker-engine')?.name).toBe('Docker Engine')
    expect(getVendorProduct('zerotier-one')?.sourceId).toBe('zerotier-one')
    expect(getVendorProduct('netbird')?.sourceId).toBe('netbird')
    expect(getVendorProduct('nodejs')).toBeUndefined()
    expect(getVendorProduct('libreoffice')).toBeUndefined()
    expect(getVendorProduct('unknown-product')).toBeUndefined()
  })
})
