import { describe, expect, it } from 'vitest'
import type { RepositorySource } from './model'
import { REPOSITORY_SOURCES, getRepositorySource } from './sources'

const expectedSources = [
  { id: 'brave-browser', name: 'Brave Browser', documentationUrl: 'https://brave.com/linux/', verifiedAt: '2026-08-29', locations: ['https://brave-browser-apt-release.s3.brave.com/|trixie,bookworm,bullseye,forky,sid|amd64,arm64|stable|main|explicit'], keys: ['brave-browser-signing-key|https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg|/usr/share/keyrings/brave-browser-archive-keyring.gpg|binary||trixie,bookworm,bullseye,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'mozilla', name: 'Mozilla', documentationUrl: 'https://support.mozilla.org/en-US/kb/install-firefox-linux', verifiedAt: '2026-08-29', locations: ['https://packages.mozilla.org/apt|trixie,bookworm,bullseye|amd64,arm64|mozilla|main|explicit'], keys: ['mozilla-signing-key|https://packages.mozilla.org/apt/repo-signing-key.gpg|/etc/apt/keyrings/packages.mozilla.org.asc|ascii-armored|35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3|trixie,bookworm,bullseye'], auxiliaryTrustFiles: [], preferenceFiles: [{ id: 'mozilla-firefox', content: 'Package: *\nPin: origin packages.mozilla.org\nPin-Priority: 1000\n' }], warnings: [] },
  { id: 'google-chrome', name: 'Google Chrome', documentationUrl: 'https://support.google.com/chrome/a/answer/9025903', verifiedAt: '2026-08-29', locations: ['https://dl.google.com/linux/chrome/deb/|trixie,bookworm,bullseye,forky,sid|amd64|stable|main|explicit'], keys: ['google-chrome-signing-key|https://dl.google.com/linux/linux_signing_key.pub|/etc/apt/keyrings/google-chrome.asc|ascii-armored|EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796|trixie,bookworm,bullseye,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'microsoft-edge', name: 'Microsoft Edge', documentationUrl: 'https://learn.microsoft.com/en-us/linux/packages', verifiedAt: '2026-08-29', locations: ['https://packages.microsoft.com/repos/edge|trixie,bookworm,bullseye,forky,sid|amd64|stable|main|explicit'], keys: ['microsoft-edge-signing-key|https://packages.microsoft.com/keys/microsoft.asc|/etc/apt/keyrings/microsoft-edge.gpg|ascii-armored|BC528686B50D79E339D3721CEB3E94ADBE1229CF|trixie,bookworm,bullseye,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'vivaldi', name: 'Vivaldi', documentationUrl: 'https://help.vivaldi.com/desktop/install-update/obtaining-official-builds/', verifiedAt: '2026-08-29', locations: ['https://repo.vivaldi.com/stable/deb/|trixie,forky,sid|amd64,arm64|stable|main|explicit'], keys: ['vivaldi-signing-key|https://repo.vivaldi.com/stable/linux_signing_key.pub|/etc/apt/keyrings/vivaldi.gpg|ascii-armored||trixie,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'opera', name: 'Opera', documentationUrl: 'https://deb.opera.com/manual.html', verifiedAt: '2026-08-29', locations: ['https://deb.opera.com/opera-stable/|trixie,bookworm,bullseye,forky,sid|amd64|stable|non-free|explicit'], keys: ['opera-signing-key|https://deb.opera.com/archive.key|/etc/apt/keyrings/opera.gpg|ascii-armored|6C86BE214648376680CA957B11EE8C00B693A745|trixie,bookworm,bullseye,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'signal', name: 'Signal', documentationUrl: 'https://signal.org/download/linux/', verifiedAt: '2026-08-29', locations: ['https://updates.signal.org/desktop/apt/|trixie,bookworm,bullseye,forky,sid|amd64|xenial|main|explicit'], keys: ['signal-signing-key|https://updates.signal.org/desktop/apt/keys.asc|/usr/share/keyrings/signal-desktop-keyring.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'proton-vpn', name: 'Proton VPN', documentationUrl: 'https://protonvpn.com/support/linux-vpn-setup', verifiedAt: '2026-08-29', locations: ['https://repo.protonvpn.com/debian|trixie|amd64,arm64|stable|main|explicit'], keys: ['proton-vpn-signing-key|https://repo.protonvpn.com/debian/public_key.asc|/etc/apt/keyrings/protonvpn-stable-archive-keyring.gpg|ascii-armored||trixie'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: ['proton-vpn-supported-environment'] },
  { id: 'mullvad', name: 'Mullvad', documentationUrl: 'https://mullvad.net/en/help/install-mullvad-app-linux', verifiedAt: '2026-08-29', locations: ['https://repository.mullvad.net/deb/stable|trixie,bookworm,forky,sid|amd64,arm64|stable|main|explicit'], keys: ['mullvad-signing-key|https://repository.mullvad.net/deb/mullvad-keyring.asc|/usr/share/keyrings/mullvad-keyring.asc|ascii-armored|A1198702FC3E0A09A9AE5B75D5A1D4F266DE8DDF|trixie,bookworm,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'tor', name: 'Tor', documentationUrl: 'https://support.torproject.org/little-t-tor/getting-started/installing/', verifiedAt: '2026-08-29', locations: ['https://deb.torproject.org/torproject.org|trixie|amd64|trixie|main|explicit', 'https://deb.torproject.org/torproject.org|trixie|arm64|trixie|main|explicit', 'https://deb.torproject.org/torproject.org|bookworm|amd64|bookworm|main|explicit', 'https://deb.torproject.org/torproject.org|bookworm|arm64|bookworm|main|explicit', 'https://deb.torproject.org/torproject.org|bullseye|amd64|bullseye|main|explicit', 'https://deb.torproject.org/torproject.org|bullseye|arm64|bullseye|main|explicit'], keys: ['tor-signing-key|https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc|/usr/share/keyrings/deb.torproject.org-keyring.gpg|ascii-armored|A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89|trixie,bookworm,bullseye'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: ['tor-not-browser'] },
  { id: 'docker', name: 'Docker', documentationUrl: 'https://docs.docker.com/engine/install/debian/', verifiedAt: '2026-08-29', locations: ['https://download.docker.com/linux/debian|trixie|amd64|trixie|stable|explicit', 'https://download.docker.com/linux/debian|trixie|arm64|trixie|stable|explicit', 'https://download.docker.com/linux/debian|trixie|armhf|trixie|stable|explicit', 'https://download.docker.com/linux/debian|bookworm|amd64|bookworm|stable|explicit', 'https://download.docker.com/linux/debian|bookworm|arm64|bookworm|stable|explicit', 'https://download.docker.com/linux/debian|bookworm|armhf|bookworm|stable|explicit', 'https://download.docker.com/linux/debian|bullseye|amd64|bullseye|stable|explicit', 'https://download.docker.com/linux/debian|bullseye|arm64|bullseye|stable|explicit', 'https://download.docker.com/linux/debian|bullseye|armhf|bullseye|stable|explicit'], keys: ['docker-signing-key|https://download.docker.com/linux/debian/gpg|/etc/apt/keyrings/docker.asc|ascii-armored||trixie,bookworm,bullseye'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: ['docker-firewall'] },
  { id: 'kubernetes-v1-36', name: 'Kubernetes v1.36', documentationUrl: 'https://v1-36.docs.kubernetes.io/docs/tasks/tools/install-kubectl-linux/', verifiedAt: '2026-08-29', locations: ['https://pkgs.k8s.io/core:/stable:/v1.36/deb/|trixie,bookworm,bullseye,forky,sid|amd64,arm64|/||explicit'], keys: ['kubernetes-v1-36-signing-key|https://pkgs.k8s.io/core:/stable:/v1.36/deb/Release.key|/etc/apt/keyrings/kubernetes-apt-keyring.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'google-cloud', name: 'Google Cloud', documentationUrl: 'https://docs.cloud.google.com/sdk/docs/install-sdk', verifiedAt: '2026-08-29', locations: ['https://packages.cloud.google.com/apt|trixie,bookworm,bullseye|amd64,arm64|cloud-sdk|main|explicit'], keys: ['google-cloud-signing-key|https://packages.cloud.google.com/apt/doc/apt-key.gpg|/usr/share/keyrings/cloud.google.gpg|binary||trixie,bookworm,bullseye'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'microsoft-azure-cli', name: 'Microsoft Azure CLI', documentationUrl: 'https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux', verifiedAt: '2026-08-29', locations: ['https://packages.microsoft.com/repos/azure-cli/|bookworm|amd64|bookworm|main|explicit', 'https://packages.microsoft.com/repos/azure-cli/|bookworm|arm64|bookworm|main|explicit', 'https://packages.microsoft.com/repos/azure-cli/|bullseye|amd64|bullseye|main|explicit', 'https://packages.microsoft.com/repos/azure-cli/|bullseye|arm64|bullseye|main|explicit'], keys: ['microsoft-azure-cli-signing-key|https://packages.microsoft.com/keys/microsoft.asc|/etc/apt/keyrings/microsoft-azure-cli.gpg|ascii-armored|BC528686B50D79E339D3721CEB3E94ADBE1229CF|bookworm,bullseye'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'github-cli', name: 'GitHub CLI', documentationUrl: 'https://github.com/cli/cli/blob/trunk/docs/install_linux.md', verifiedAt: '2026-08-29', locations: ['https://cli.github.com/packages|trixie,bookworm,bullseye,forky,sid|amd64,arm64|stable|main|explicit'], keys: ['github-cli-signing-key|https://cli.github.com/packages/githubcli-archive-keyring.gpg|/usr/share/keyrings/githubcli-archive-keyring.gpg|binary|2C6106201985B60E6C7AC87323F3D4EA75716059,7F38BBB59D064DBCB3D84D725612B36462313325|trixie,bookworm,bullseye,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'hashicorp', name: 'HashiCorp', documentationUrl: 'https://developer.hashicorp.com/terraform/install', verifiedAt: '2026-08-29', locations: ['https://apt.releases.hashicorp.com|trixie|amd64|trixie|main|explicit', 'https://apt.releases.hashicorp.com|trixie|arm64|trixie|main|explicit', 'https://apt.releases.hashicorp.com|bookworm|amd64|bookworm|main|explicit', 'https://apt.releases.hashicorp.com|bookworm|arm64|bookworm|main|explicit', 'https://apt.releases.hashicorp.com|bullseye|amd64|bullseye|main|explicit', 'https://apt.releases.hashicorp.com|bullseye|arm64|bullseye|main|explicit'], keys: ['hashicorp-signing-key|https://apt.releases.hashicorp.com/gpg|/usr/share/keyrings/hashicorp-archive-keyring.gpg|ascii-armored|798AEC654E5C15428C8E42EEAA16FCBCA621E701|trixie,bookworm,bullseye'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'postgresql-pgdg', name: 'PostgreSQL PGDG', documentationUrl: 'https://wiki.postgresql.org/wiki/Apt', verifiedAt: '2026-08-29', locations: ['https://apt.postgresql.org/pub/repos/apt/|trixie|amd64|trixie-pgdg|main|explicit', 'https://apt.postgresql.org/pub/repos/apt/|trixie|arm64|trixie-pgdg|main|explicit', 'https://apt.postgresql.org/pub/repos/apt/|bookworm|amd64|bookworm-pgdg|main|explicit', 'https://apt.postgresql.org/pub/repos/apt/|bookworm|arm64|bookworm-pgdg|main|explicit', 'https://apt.postgresql.org/pub/repos/apt/|bullseye|amd64|bullseye-pgdg|main|explicit', 'https://apt.postgresql.org/pub/repos/apt/|bullseye|arm64|bullseye-pgdg|main|explicit', 'https://apt.postgresql.org/pub/repos/apt/|forky|amd64|forky-pgdg|main|explicit', 'https://apt.postgresql.org/pub/repos/apt/|forky|arm64|forky-pgdg|main|explicit', 'https://apt.postgresql.org/pub/repos/apt/|sid|amd64|sid-pgdg|main|explicit', 'https://apt.postgresql.org/pub/repos/apt/|sid|arm64|sid-pgdg|main|explicit'], keys: ['postgresql-pgdg-signing-key|https://www.postgresql.org/media/keys/ACCC4CF8.asc|/usr/share/keyrings/postgresql-apt.gpg|ascii-armored|B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8|trixie,bookworm,bullseye,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'mongodb-community-8-0', name: 'MongoDB Community 8.0', documentationUrl: 'https://www.mongodb.com/docs/v8.0/tutorial/install-mongodb-on-debian/', verifiedAt: '2026-08-29', locations: ['https://repo.mongodb.org/apt/debian|bookworm|amd64|bookworm/mongodb-org/8.0|main|explicit'], keys: ['mongodb-community-8-0-signing-key|https://pgp.mongodb.com/server-8.0.asc|/usr/share/keyrings/mongodb-server-8.0.gpg|ascii-armored||bookworm'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'grafana', name: 'Grafana', documentationUrl: 'https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/', verifiedAt: '2026-08-29', locations: ['https://apt.grafana.com|trixie,bookworm,bullseye,forky,sid|amd64,arm64|stable|main|explicit'], keys: ['grafana-signing-key|https://apt.grafana.com/gpg-full.key|/etc/apt/keyrings/grafana.asc|ascii-armored|4E40DDF6D76E284A4A6780E48C8C34C524098CB6,0E22EB88E39E12277A7760AE9E439B102CF3C0C6,B53AE77BADB630A683046005963FA27710458545|trixie,bookworm,bullseye,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'nvidia-container-toolkit', name: 'NVIDIA Container Toolkit', documentationUrl: 'https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html', verifiedAt: '2026-08-29', locations: ['https://nvidia.github.io/libnvidia-container/stable/deb/amd64|trixie|amd64|/||explicit', 'https://nvidia.github.io/libnvidia-container/stable/deb/arm64|trixie|arm64|/||explicit', 'https://nvidia.github.io/libnvidia-container/stable/deb/amd64|bookworm|amd64|/||explicit', 'https://nvidia.github.io/libnvidia-container/stable/deb/arm64|bookworm|arm64|/||explicit', 'https://nvidia.github.io/libnvidia-container/stable/deb/amd64|bullseye|amd64|/||explicit', 'https://nvidia.github.io/libnvidia-container/stable/deb/arm64|bullseye|arm64|/||explicit', 'https://nvidia.github.io/libnvidia-container/stable/deb/amd64|forky|amd64|/||explicit', 'https://nvidia.github.io/libnvidia-container/stable/deb/arm64|forky|arm64|/||explicit', 'https://nvidia.github.io/libnvidia-container/stable/deb/amd64|sid|amd64|/||explicit', 'https://nvidia.github.io/libnvidia-container/stable/deb/arm64|sid|arm64|/||explicit'], keys: ['nvidia-container-toolkit-signing-key|https://nvidia.github.io/libnvidia-container/gpgkey|/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: ['nvidia-container-toolkit-prerequisites'] },
  { id: 'mariadb-community-11-8', name: 'MariaDB Community 11.8', documentationUrl: 'https://mariadb.com/docs/server/server-management/install-and-upgrade-mariadb/installing-mariadb/binary-packages/gpg', verifiedAt: '2026-08-29', locations: ['https://dlm.mariadb.com/repo/mariadb-server/11.8/repo/debian|trixie|amd64|trixie|main|explicit', 'https://dlm.mariadb.com/repo/mariadb-server/11.8/repo/debian|trixie|arm64|trixie|main|explicit', 'https://dlm.mariadb.com/repo/mariadb-server/11.8/repo/debian|bookworm|amd64|bookworm|main|explicit', 'https://dlm.mariadb.com/repo/mariadb-server/11.8/repo/debian|bookworm|arm64|bookworm|main|explicit', 'https://dlm.mariadb.com/repo/mariadb-server/11.8/repo/debian|bullseye|amd64|bullseye|main|explicit', 'https://dlm.mariadb.com/repo/mariadb-server/11.8/repo/debian|bullseye|arm64|bullseye|main|explicit', 'https://dlm.mariadb.com/repo/mariadb-server/11.8/repo/debian|sid|amd64|sid|main|explicit', 'https://dlm.mariadb.com/repo/mariadb-server/11.8/repo/debian|sid|arm64|sid|main|explicit'], keys: ['mariadb-community-11-8-signing-key|https://mariadb.org/mariadb_release_signing_key.pgp|/etc/apt/keyrings/mariadb-server-11-8.pgp|ascii-armored|177F4010FE56CA3336300305F1656F24C74CD1D8|trixie,bookworm,bullseye,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: ['mariadb-no-setup-script'] },
  { id: 'redis-open-source', name: 'Redis Open Source', documentationUrl: 'https://redis.io/docs/latest/operate/oss_and_stack/install/install-stack/', verifiedAt: '2026-08-29', locations: ['https://packages.redis.io/deb|trixie|amd64|trixie|main|explicit', 'https://packages.redis.io/deb|trixie|arm64|trixie|main|explicit', 'https://packages.redis.io/deb|bookworm|amd64|bookworm|main|explicit', 'https://packages.redis.io/deb|bookworm|arm64|bookworm|main|explicit'], keys: ['redis-open-source-signing-key|https://packages.redis.io/gpg|/usr/share/keyrings/redis-archive-keyring.gpg|ascii-armored||trixie,bookworm'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'clickhouse', name: 'ClickHouse', documentationUrl: 'https://clickhouse.com/docs/en/getting-started/install/', verifiedAt: '2026-08-29', locations: ['https://packages.clickhouse.com/deb|trixie,bookworm,bullseye,forky,sid|amd64,arm64|stable|main|generic-debian'], keys: ['clickhouse-signing-key|https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key|/usr/share/keyrings/clickhouse-keyring.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: ['clickhouse-generic-debian'] },
  { id: 'influxdb-3-core', name: 'InfluxDB 3 Core', documentationUrl: 'https://docs.influxdata.com/influxdb3/core/install/', verifiedAt: '2026-08-29', locations: ['https://repos.influxdata.com/debian|trixie,bookworm,forky,sid|amd64,arm64|stable|main|explicit'], keys: ['influxdb-3-core-signing-key|https://repos.influxdata.com/influxdata-archive.key|/usr/share/keyrings/influxdata-archive.gpg|ascii-armored|24C975CBA61A024EE1B631787C3D57159FC2F927|trixie,bookworm,forky,sid'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
  { id: 'zabbix-7-4', name: 'Zabbix 7.4', documentationUrl: 'https://www.zabbix.com/documentation/current/en/manual/installation/install_from_packages', verifiedAt: '2026-08-29', locations: ['https://repo.zabbix.com/zabbix/7.4/stable/debian|trixie|amd64|trixie|main|explicit', 'https://repo.zabbix.com/zabbix/7.4/stable/debian|trixie|arm64|trixie|main|explicit', 'https://repo.zabbix.com/zabbix/7.4/stable/debian|bookworm|amd64|bookworm|main|explicit', 'https://repo.zabbix.com/zabbix/7.4/stable/debian|bookworm|arm64|bookworm|main|explicit', 'https://repo.zabbix.com/zabbix/7.4/stable/debian|bullseye|amd64|bullseye|main|explicit', 'https://repo.zabbix.com/zabbix/7.4/stable/debian|bullseye|arm64|bullseye|main|explicit'], keys: ['zabbix-7-4-signing-key|https://repo.zabbix.com/zabbix-official-repo.key|/etc/apt/keyrings/zabbix-official-repo.gpg|ascii-armored||trixie,bookworm,bullseye'], auxiliaryTrustFiles: [], preferenceFiles: [], warnings: [] },
] as const

const expectedAdditionalSources = [
  {"id":"onepassword","name":"1Password","documentationUrl":"https://support.1password.com/install-linux/","verifiedAt":"2026-08-29","locations":["https://downloads.1password.com/linux/debian/amd64|trixie,bookworm,bullseye|amd64|stable|main|explicit","https://downloads.1password.com/linux/debian/arm64|trixie,bookworm,bullseye|arm64|stable|main|explicit"],"keys":["onepassword-signing-key|https://downloads.1password.com/linux/keys/1password.asc|/usr/share/keyrings/1password-archive-keyring.gpg|ascii-armored|3FEF9748469ADBE15DA7CA80AC2D62742012EA22|trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[{"id":"onepassword-policy","url":"https://downloads.1password.com/linux/debian/debsig/1password.pol","destination":"debsig-policy","mediaType":"application/xml"},{"id":"onepassword-keyring","url":"https://downloads.1password.com/linux/keys/1password.asc","destination":"debsig-keyring","mediaType":"application/pgp-keys","fingerprint":"3FEF9748469ADBE15DA7CA80AC2D62742012EA22"}],"preferenceFiles":[],"warnings":[]},
  {"id":"visual-studio-code","name":"Visual Studio Code","documentationUrl":"https://code.visualstudio.com/docs/setup/linux","verifiedAt":"2026-08-29","locations":["https://packages.microsoft.com/repos/code|trixie,bookworm,bullseye|amd64,arm64,armhf|stable|main|explicit"],"keys":["visual-studio-code-signing-key|https://packages.microsoft.com/keys/microsoft.asc|/etc/apt/keyrings/vscode.gpg|ascii-armored|BC528686B50D79E339D3721CEB3E94ADBE1229CF|trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"microsoft-prod","name":"Microsoft Products","documentationUrl":"https://learn.microsoft.com/en-us/linux/packages","verifiedAt":"2026-08-29","locations":["https://packages.microsoft.com/debian/13/prod|trixie|amd64,arm64|trixie|main|explicit","https://packages.microsoft.com/debian/12/prod|bookworm|amd64,arm64|bookworm|main|explicit"],"keys":["microsoft-prod-signing-key|https://packages.microsoft.com/keys/microsoft.asc|/etc/apt/keyrings/microsoft-prod.gpg|ascii-armored|BC528686B50D79E339D3721CEB3E94ADBE1229CF|trixie,bookworm"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"tailscale","name":"Tailscale","documentationUrl":"https://tailscale.com/kb/1031/install-linux","verifiedAt":"2026-08-29","locations":["https://pkgs.tailscale.com/stable/debian|trixie|amd64,arm64,armhf,i386|trixie|main|explicit","https://pkgs.tailscale.com/stable/debian|bookworm|amd64,arm64,armhf,i386|bookworm|main|explicit","https://pkgs.tailscale.com/stable/debian|bullseye|amd64,arm64,armhf,i386|bullseye|main|explicit","https://pkgs.tailscale.com/stable/debian|forky|amd64,arm64,armhf,i386|forky|main|explicit","https://pkgs.tailscale.com/stable/debian|sid|amd64,arm64,armhf,i386|sid|main|explicit"],"keys":["tailscale-trixie-key|https://pkgs.tailscale.com/stable/debian/trixie.noarmor.gpg|/usr/share/keyrings/tailscale-trixie-archive-keyring.gpg|binary||trixie","tailscale-bookworm-key|https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg|/usr/share/keyrings/tailscale-bookworm-archive-keyring.gpg|binary||bookworm","tailscale-bullseye-key|https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg|/usr/share/keyrings/tailscale-bullseye-archive-keyring.gpg|binary||bullseye","tailscale-forky-key|https://pkgs.tailscale.com/stable/debian/forky.noarmor.gpg|/usr/share/keyrings/tailscale-forky-archive-keyring.gpg|binary||forky","tailscale-sid-key|https://pkgs.tailscale.com/stable/debian/sid.noarmor.gpg|/usr/share/keyrings/tailscale-sid-archive-keyring.gpg|binary||sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"cloudflare-warp","name":"Cloudflare WARP","documentationUrl":"https://pkg.cloudflareclient.com/","verifiedAt":"2026-08-29","locations":["https://pkg.cloudflareclient.com/|trixie|amd64|trixie|main|explicit","https://pkg.cloudflareclient.com/|trixie|arm64|trixie|main|explicit","https://pkg.cloudflareclient.com/|bookworm|amd64|bookworm|main|explicit","https://pkg.cloudflareclient.com/|bookworm|arm64|bookworm|main|explicit"],"keys":["cloudflare-warp-signing-key|https://pkg.cloudflareclient.com/pubkey.gpg|/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg|binary||trixie,bookworm"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"cloudflared","name":"cloudflared","documentationUrl":"https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/","verifiedAt":"2026-08-29","locations":["https://pkg.cloudflare.com/cloudflared|trixie,bookworm,bullseye,forky,sid|amd64,arm64,armhf|any|main|generic-debian"],"keys":["cloudflared-signing-key|https://pkg.cloudflare.com/cloudflare-main.gpg|/usr/share/keyrings/cloudflare-main.gpg|binary||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"opentofu","name":"OpenTofu","documentationUrl":"https://opentofu.org/docs/intro/install/deb/","verifiedAt":"2026-08-29","locations":["https://packages.opentofu.org/opentofu/tofu/any/|trixie,bookworm,bullseye,forky,sid|amd64,arm64,armhf,i386|any|main|generic-debian"],"keys":["opentofu-release-key|https://get.opentofu.org/opentofu.gpg|/etc/apt/keyrings/opentofu.gpg|binary||trixie,bookworm,bullseye,forky,sid","opentofu-package-key|https://packages.opentofu.org/opentofu/tofu/gpgkey|/etc/apt/keyrings/opentofu-repo.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"anydesk","name":"AnyDesk","documentationUrl":"https://deb.anydesk.com/howto.html","verifiedAt":"2026-08-29","locations":["https://deb.anydesk.com|trixie,bookworm,bullseye|amd64,arm64|all|main|generic-debian"],"keys":["anydesk-signing-key|https://keys.anydesk.com/repos/DEB-GPG-KEY|/etc/apt/keyrings/keys.anydesk.com.asc|ascii-armored||trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"sublime","name":"Sublime HQ","documentationUrl":"https://www.sublimetext.com/docs/linux_repositories.html","verifiedAt":"2026-08-29","locations":["https://download.sublimetext.com/|trixie,bookworm,bullseye,forky,sid|amd64,arm64|apt/stable/||generic-debian"],"keys":["sublime-signing-key|https://download.sublimetext.com/sublimehq-pub.gpg|/etc/apt/keyrings/sublimehq-pub.gpg|binary||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"element","name":"Element","documentationUrl":"https://element.io/download","verifiedAt":"2026-08-29","locations":["https://packages.element.io/debian/|trixie,bookworm,bullseye|amd64,arm64|default|main|explicit"],"keys":["element-signing-key|https://packages.element.io/debian/element-io-archive-keyring.gpg|/usr/share/keyrings/element-io-archive-keyring.gpg|binary||trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"oracle-virtualbox","name":"Oracle VirtualBox","documentationUrl":"https://www.virtualbox.org/wiki/Linux_Downloads","verifiedAt":"2026-08-29","locations":["https://download.virtualbox.org/virtualbox/debian|trixie|amd64|trixie|contrib|explicit","https://download.virtualbox.org/virtualbox/debian|bookworm|amd64|bookworm|contrib|explicit","https://download.virtualbox.org/virtualbox/debian|bullseye|amd64|bullseye|contrib|explicit"],"keys":["oracle-virtualbox-signing-key|https://www.virtualbox.org/download/oracle_vbox_2016.asc|/usr/share/keyrings/oracle-virtualbox-2016.gpg|ascii-armored|B9F8D658297AF3EFC18D5CDFA2F683C52980AECF|trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"gitlab-ce","name":"GitLab Community Edition","documentationUrl":"https://docs.gitlab.com/install/package/debian/","verifiedAt":"2026-08-29","locations":["https://packages.gitlab.com/gitlab/gitlab-ce/debian/|trixie|amd64|trixie|main|explicit","https://packages.gitlab.com/gitlab/gitlab-ce/debian/|trixie|arm64|trixie|main|explicit","https://packages.gitlab.com/gitlab/gitlab-ce/debian/|bookworm|amd64|bookworm|main|explicit","https://packages.gitlab.com/gitlab/gitlab-ce/debian/|bookworm|arm64|bookworm|main|explicit","https://packages.gitlab.com/gitlab/gitlab-ce/debian/|bullseye|amd64|bullseye|main|explicit","https://packages.gitlab.com/gitlab/gitlab-ce/debian/|bullseye|arm64|bullseye|main|explicit"],"keys":["gitlab-ce-signing-key|https://packages.gitlab.com/gpgkey/gpg.key|/etc/apt/keyrings/gitlab.gpg|ascii-armored||trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"gitlab-runner","name":"GitLab Runner","documentationUrl":"https://docs.gitlab.com/runner/install/linux-repository/","verifiedAt":"2026-08-29","locations":["https://packages.gitlab.com/runner/gitlab-runner/debian/|trixie|amd64|trixie|main|explicit","https://packages.gitlab.com/runner/gitlab-runner/debian/|trixie|arm64|trixie|main|explicit","https://packages.gitlab.com/runner/gitlab-runner/debian/|bookworm|amd64|bookworm|main|explicit","https://packages.gitlab.com/runner/gitlab-runner/debian/|bookworm|arm64|bookworm|main|explicit","https://packages.gitlab.com/runner/gitlab-runner/debian/|bullseye|amd64|bullseye|main|explicit","https://packages.gitlab.com/runner/gitlab-runner/debian/|bullseye|arm64|bullseye|main|explicit","https://packages.gitlab.com/runner/gitlab-runner/debian/|forky|amd64|forky|main|explicit","https://packages.gitlab.com/runner/gitlab-runner/debian/|forky|arm64|forky|main|explicit"],"keys":["gitlab-runner-signing-key|https://packages.gitlab.com/gpgkey/gpg.key|/etc/apt/keyrings/gitlab-runner.gpg|ascii-armored||trixie,bookworm,bullseye,forky"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"jenkins-lts","name":"Jenkins LTS","documentationUrl":"https://www.jenkins.io/doc/book/installing/linux/","verifiedAt":"2026-08-29","locations":["https://pkg.jenkins.io/debian-stable|trixie|amd64,arm64|binary/||explicit"],"keys":["jenkins-lts-signing-key|https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key|/usr/share/keyrings/jenkins-lts-keyring.asc|ascii-armored||trixie"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"nginx-stable","name":"NGINX Stable","documentationUrl":"https://nginx.org/en/linux_packages.html","verifiedAt":"2026-08-29","locations":["https://nginx.org/packages/debian|trixie|amd64|trixie|nginx|explicit","https://nginx.org/packages/debian|trixie|arm64|trixie|nginx|explicit","https://nginx.org/packages/debian|bookworm|amd64|bookworm|nginx|explicit","https://nginx.org/packages/debian|bookworm|arm64|bookworm|nginx|explicit","https://nginx.org/packages/debian|bullseye|amd64|bullseye|nginx|explicit","https://nginx.org/packages/debian|bullseye|arm64|bullseye|nginx|explicit"],"keys":["nginx-stable-signing-key|https://nginx.org/keys/nginx_signing.key|/usr/share/keyrings/nginx-archive-keyring.gpg|ascii-armored|573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62,8540A6F18833A80E9C1653A42FD21310B49F6B46,9E9BE90EACBCDE69FE9B204CBCDCD8A38D88A2B3|trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[{"id":"nginx","content":"Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n"}],"warnings":[]},
  {"id":"elastic-9","name":"Elastic 9","documentationUrl":"https://www.elastic.co/docs/deploy-manage/deploy/self-managed/install-elasticsearch-with-debian-package","verifiedAt":"2026-08-29","locations":["https://artifacts.elastic.co/packages/9.x/apt|trixie,bookworm|amd64,arm64|stable|main|explicit"],"keys":["elastic-9-signing-key|https://artifacts.elastic.co/GPG-KEY-elasticsearch|/usr/share/keyrings/elastic-archive-keyring.gpg|ascii-armored|46095ACC8548582C1A2699A9D27D666CD88E42B4|trixie,bookworm"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"syncthing","name":"Syncthing","documentationUrl":"https://apt.syncthing.net/","verifiedAt":"2026-08-29","locations":["https://apt.syncthing.net/|trixie,bookworm,bullseye,forky,sid|amd64,arm64,armhf|syncthing|stable-v2|generic-debian"],"keys":["syncthing-signing-key|https://syncthing.net/release-key.gpg|/etc/apt/keyrings/syncthing-archive-keyring.gpg|binary||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[{"id":"syncthing","content":"Package: *\nPin: origin apt.syncthing.net\nPin-Priority: 990\n"}],"warnings":[]},
  {"id":"corretto","name":"Amazon Corretto","documentationUrl":"https://docs.aws.amazon.com/corretto/latest/corretto-21-ug/generic-linux-install.html","verifiedAt":"2026-08-29","locations":["https://apt.corretto.aws|trixie,bookworm,bullseye,forky,sid|amd64,arm64|stable|main|generic-debian"],"keys":["corretto-signing-key|https://apt.corretto.aws/corretto.key|/usr/share/keyrings/corretto-keyring.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"adoptium","name":"Eclipse Adoptium","documentationUrl":"https://adoptium.net/installation/linux/","verifiedAt":"2026-08-29","locations":["https://packages.adoptium.net/artifactory/deb|trixie|amd64|trixie|main|explicit","https://packages.adoptium.net/artifactory/deb|trixie|arm64|trixie|main|explicit","https://packages.adoptium.net/artifactory/deb|bookworm|amd64|bookworm|main|explicit","https://packages.adoptium.net/artifactory/deb|bookworm|arm64|bookworm|main|explicit","https://packages.adoptium.net/artifactory/deb|bullseye|amd64|bullseye|main|explicit","https://packages.adoptium.net/artifactory/deb|bullseye|arm64|bullseye|main|explicit"],"keys":["adoptium-signing-key|https://packages.adoptium.net/artifactory/api/gpg/key/public|/etc/apt/keyrings/adoptium.gpg|ascii-armored||trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"caddy","name":"Caddy","documentationUrl":"https://caddyserver.com/docs/install","verifiedAt":"2026-08-29","locations":["https://dl.cloudsmith.io/public/caddy/stable/deb/debian|trixie,bookworm,bullseye,forky,sid|amd64,arm64,armhf|any-version|main|generic-debian"],"keys":["caddy-signing-key|https://dl.cloudsmith.io/public/caddy/stable/gpg.key|/usr/share/keyrings/caddy-stable-archive-keyring.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"yarn","name":"Yarn Classic","documentationUrl":"https://classic.yarnpkg.com/lang/en/docs/install/","verifiedAt":"2026-08-29","locations":["https://dl.yarnpkg.com/debian/|trixie,bookworm,bullseye,forky,sid|amd64,arm64,armhf,i386|stable|main|generic-debian"],"keys":["yarn-signing-key|https://dl.yarnpkg.com/debian/pubkey.gpg|/usr/share/keyrings/yarnkey.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"mozilla-thunderbird","name":"Mozilla Thunderbird","documentationUrl":"https://support.mozilla.org/en-US/kb/installing-thunderbird-linux","verifiedAt":"2026-08-29","locations":["https://packages.mozilla.org/apt|trixie,bookworm,bullseye|amd64|thunderbird-deb|main|explicit"],"keys":["mozilla-thunderbird-signing-key|https://packages.mozilla.org/apt/repo-signing-key.gpg|/etc/apt/keyrings/packages.mozilla.org.asc|ascii-armored|35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3|trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[{"id":"mozilla-thunderbird","content":"Package: *\nPin: origin packages.mozilla.org\nPin-Priority: 1000\n"}],"warnings":[]},
  {"id":"gitlab-ee","name":"GitLab Enterprise Edition","documentationUrl":"https://docs.gitlab.com/install/package/debian/","verifiedAt":"2026-08-29","locations":["https://packages.gitlab.com/gitlab/gitlab-ee/debian/|trixie|amd64|trixie|main|explicit","https://packages.gitlab.com/gitlab/gitlab-ee/debian/|trixie|arm64|trixie|main|explicit","https://packages.gitlab.com/gitlab/gitlab-ee/debian/|bookworm|amd64|bookworm|main|explicit","https://packages.gitlab.com/gitlab/gitlab-ee/debian/|bookworm|arm64|bookworm|main|explicit","https://packages.gitlab.com/gitlab/gitlab-ee/debian/|bullseye|amd64|bullseye|main|explicit","https://packages.gitlab.com/gitlab/gitlab-ee/debian/|bullseye|arm64|bullseye|main|explicit"],"keys":["gitlab-ee-signing-key|https://packages.gitlab.com/gpgkey/gpg.key|/etc/apt/keyrings/gitlab.gpg|ascii-armored||trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"jenkins-weekly","name":"Jenkins Weekly","documentationUrl":"https://www.jenkins.io/doc/book/installing/linux/","verifiedAt":"2026-08-29","locations":["https://pkg.jenkins.io/debian|trixie|amd64,arm64|binary/||explicit"],"keys":["jenkins-weekly-signing-key|https://pkg.jenkins.io/debian/jenkins.io-2026.key|/usr/share/keyrings/jenkins-weekly-keyring.asc|ascii-armored||trixie"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"nginx-mainline","name":"NGINX Mainline","documentationUrl":"https://nginx.org/en/linux_packages.html","verifiedAt":"2026-08-29","locations":["https://nginx.org/packages/mainline/debian|trixie|amd64|trixie|nginx|explicit","https://nginx.org/packages/mainline/debian|trixie|arm64|trixie|nginx|explicit","https://nginx.org/packages/mainline/debian|bookworm|amd64|bookworm|nginx|explicit","https://nginx.org/packages/mainline/debian|bookworm|arm64|bookworm|nginx|explicit","https://nginx.org/packages/mainline/debian|bullseye|amd64|bullseye|nginx|explicit","https://nginx.org/packages/mainline/debian|bullseye|arm64|bullseye|nginx|explicit"],"keys":["nginx-mainline-signing-key|https://nginx.org/keys/nginx_signing.key|/usr/share/keyrings/nginx-archive-keyring.gpg|ascii-armored|573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62,8540A6F18833A80E9C1653A42FD21310B49F6B46,9E9BE90EACBCDE69FE9B204CBCDCD8A38D88A2B3|trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[{"id":"nginx","content":"Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n"}],"warnings":[]},
  {"id":"azul-zulu","name":"Azul Zulu","documentationUrl":"https://docs.azul.com/core/install/debian","verifiedAt":"2026-08-29","locations":["https://repos.azul.com/zulu/deb|trixie,bookworm,bullseye,forky,sid|amd64,arm64|stable|main|generic-debian"],"keys":["azul-zulu-signing-key|https://repos.azul.com/azul-repo.key|/usr/share/keyrings/azul.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"bellsoft-liberica","name":"BellSoft Liberica","documentationUrl":"https://bell-sw.com/pages/repositories/","verifiedAt":"2026-08-29","locations":["https://apt.bell-sw.com/|trixie,bookworm,bullseye,forky,sid|amd64,arm64|stable|main|generic-debian"],"keys":["bellsoft-liberica-signing-key|https://download.bell-sw.com/pki/GPG-KEY-bellsoft|/usr/share/keyrings/bellsoft.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"teamviewer","name":"TeamViewer","documentationUrl":"https://www.teamviewer.com/en/global/support/knowledge-base/teamviewer-classic/installation/linux/linux/","verifiedAt":"2026-08-29","locations":["https://linux.teamviewer.com/deb|trixie,bookworm,bullseye,forky,sid|amd64|stable|main|generic-debian"],"keys":["teamviewer-signing-key|https://linux.teamviewer.com/pubkey/currentkey.asc|/usr/share/keyrings/teamviewer-keyring.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"steam","name":"Steam","documentationUrl":"https://repo.steampowered.com/steam/","verifiedAt":"2026-08-29","locations":["https://repo.steampowered.com/steam|trixie,bookworm,bullseye,forky,sid|amd64|stable|steam|generic-debian"],"keys":["steam-signing-key|https://repo.steampowered.com/steam/archive/stable/steam.gpg|/usr/share/keyrings/steam.gpg|binary||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":["steam-i386-multiarch"]},
  {"id":"google-earth","name":"Google Earth","documentationUrl":"https://support.google.com/earth/answer/168344","verifiedAt":"2026-08-29","locations":["https://dl.google.com/linux/earth/deb/|trixie,bookworm,bullseye,forky,sid|amd64|stable|main|generic-debian"],"keys":["google-earth-signing-key|https://dl.google.com/linux/linux_signing_key.pub|/etc/apt/keyrings/google-earth.asc|ascii-armored|EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796|trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"typora","name":"Typora","documentationUrl":"https://support.typora.io/Typora-on-Linux/","verifiedAt":"2026-08-29","locations":["https://downloads.typora.io/linux|trixie,bookworm,bullseye,forky,sid|amd64,arm64|./||generic-debian"],"keys":["typora-signing-key|https://downloads.typora.io/typora.gpg|/usr/share/keyrings/typora.gpg|binary||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"warp","name":"Warp Terminal","documentationUrl":"https://docs.warp.dev/getting-started/quickstart/installation-and-setup","verifiedAt":"2026-08-29","locations":["https://releases.warp.dev/linux/deb|trixie,bookworm,bullseye,forky,sid|amd64,arm64|stable|main|generic-debian"],"keys":["warp-signing-key|https://releases.warp.dev/linux/keys/warp.asc|/etc/apt/keyrings/warpdotdev.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"nordvpn","name":"NordVPN","documentationUrl":"https://support.nordvpn.com/hc/en-us/articles/20226600447633-Installing-NordVPN-on-Linux-distributions","verifiedAt":"2026-08-29","locations":["https://repo.nordvpn.com/deb/nordvpn/debian|trixie,bookworm,bullseye,forky,sid|amd64,arm64|stable|main|generic-debian"],"keys":["nordvpn-signing-key|https://repo.nordvpn.com/gpg/nordvpn_public.asc|/usr/share/keyrings/nordvpn-keyring.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"ivpn","name":"IVPN","documentationUrl":"https://www.ivpn.net/apps-linux/","verifiedAt":"2026-08-29","locations":["https://repo.ivpn.net/stable/debian|trixie,bookworm,bullseye,forky,sid|amd64,arm64|./generic|main|generic-debian"],"keys":["ivpn-signing-key|https://repo.ivpn.net/stable/debian/generic.gpg|/usr/share/keyrings/ivpn-archive-keyring.gpg|binary||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"teleport-18","name":"Teleport 18","documentationUrl":"https://goteleport.com/docs/installation/linux/","verifiedAt":"2026-08-29","locations":["https://apt.releases.teleport.dev/debian|trixie|amd64|trixie|stable/v18|explicit","https://apt.releases.teleport.dev/debian|trixie|arm64|trixie|stable/v18|explicit","https://apt.releases.teleport.dev/debian|bookworm|amd64|bookworm|stable/v18|explicit","https://apt.releases.teleport.dev/debian|bookworm|arm64|bookworm|stable/v18|explicit","https://apt.releases.teleport.dev/debian|bullseye|amd64|bullseye|stable/v18|explicit","https://apt.releases.teleport.dev/debian|bullseye|arm64|bullseye|stable/v18|explicit"],"keys":["teleport-18-signing-key|https://apt.releases.teleport.dev/gpg|/usr/share/keyrings/teleport-archive-keyring.asc|ascii-armored||trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"wazuh","name":"Wazuh","documentationUrl":"https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html","verifiedAt":"2026-08-29","locations":["https://packages.wazuh.com/4.x/apt/|trixie,bookworm,bullseye,forky,sid|amd64,arm64,i386|stable|main|generic-debian"],"keys":["wazuh-signing-key|https://packages.wazuh.com/key/GPG-KEY-WAZUH|/usr/share/keyrings/wazuh.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":["wazuh-manager-enrollment"]},
  {"id":"apache-couchdb","name":"Apache CouchDB","documentationUrl":"https://docs.couchdb.org/en/stable/install/unix.html","verifiedAt":"2026-08-29","locations":["https://apache.jfrog.io/artifactory/couchdb-deb/|trixie|amd64|trixie|main|explicit","https://apache.jfrog.io/artifactory/couchdb-deb/|trixie|arm64|trixie|main|explicit","https://apache.jfrog.io/artifactory/couchdb-deb/|bookworm|amd64|bookworm|main|explicit","https://apache.jfrog.io/artifactory/couchdb-deb/|bookworm|arm64|bookworm|main|explicit","https://apache.jfrog.io/artifactory/couchdb-deb/|bullseye|amd64|bullseye|main|explicit","https://apache.jfrog.io/artifactory/couchdb-deb/|bullseye|arm64|bullseye|main|explicit"],"keys":["apache-couchdb-signing-key|https://couchdb.apache.org/repo/keys.asc|/usr/share/keyrings/couchdb-archive-keyring.gpg|ascii-armored||trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":["couchdb-interactive-configuration"]},
  {"id":"neo4j","name":"Neo4j","documentationUrl":"https://neo4j.com/docs/operations-manual/current/installation/linux/debian/","verifiedAt":"2026-08-29","locations":["https://debian.neo4j.com|trixie,bookworm,bullseye|amd64,arm64|stable|latest|explicit"],"keys":["neo4j-signing-key|https://debian.neo4j.com/neotechnology.gpg.key|/usr/share/keyrings/neo4j.gpg|ascii-armored||trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"icinga","name":"Icinga","documentationUrl":"https://icinga.com/docs/icinga-2/latest/doc/02-installation/01-Debian/","verifiedAt":"2026-08-29","locations":["https://packages.icinga.com/debian|trixie|amd64|icinga-trixie|main|explicit","https://packages.icinga.com/debian|trixie|arm64|icinga-trixie|main|explicit","https://packages.icinga.com/debian|bookworm|amd64|icinga-bookworm|main|explicit","https://packages.icinga.com/debian|bookworm|arm64|icinga-bookworm|main|explicit","https://packages.icinga.com/debian|bullseye|amd64|icinga-bullseye|main|explicit","https://packages.icinga.com/debian|bullseye|arm64|icinga-bullseye|main|explicit"],"keys":["icinga-signing-key|https://packages.icinga.com/icinga.key|/usr/share/keyrings/icinga-archive-keyring.gpg|ascii-armored||trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"mysql-8-4","name":"MySQL Community 8.4 LTS","documentationUrl":"https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/","verifiedAt":"2026-08-29","locations":["https://repo.mysql.com/apt/debian/|trixie|amd64|trixie|mysql-8.4-lts|explicit","https://repo.mysql.com/apt/debian/|bookworm|amd64|bookworm|mysql-8.4-lts|explicit","https://repo.mysql.com/apt/debian/|bullseye|amd64|bullseye|mysql-8.4-lts|explicit"],"keys":["mysql-8-4-signing-key|https://repo.mysql.com/RPM-GPG-KEY-mysql-2025|/usr/share/keyrings/mysql-apt-config.gpg|ascii-armored||trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":["mysql-interactive-configuration"]},
  {"id":"opensearch-3","name":"OpenSearch 3","documentationUrl":"https://docs.opensearch.org/latest/install-and-configure/install-opensearch/debian/","verifiedAt":"2026-08-29","locations":["https://artifacts.opensearch.org/releases/bundle/opensearch/3.x/apt|trixie,bookworm,bullseye,forky,sid|amd64,arm64|stable|main|generic-debian"],"keys":["opensearch-3-signing-key|https://artifacts.opensearch.org/publickeys/opensearch-release.pgp|/usr/share/keyrings/opensearch-keyring.gpg|ascii-armored|C5B7498965EFD1C2924BA9D539D319879310D3FC|trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":["opensearch-security-bootstrap"]},
  {"id":"datadog","name":"Datadog Agent","documentationUrl":"https://docs.datadoghq.com/agent/supported_platforms/","verifiedAt":"2026-08-29","locations":["https://apt.datadoghq.com|trixie,bookworm,bullseye,forky,sid|amd64,arm64|stable|7|generic-debian"],"keys":["datadog-signing-key|https://keys.datadoghq.com/DATADOG_APT_KEY_CURRENT.public|/usr/share/keyrings/datadog-archive-keyring.gpg|ascii-armored|D18886567EABAD8B2D2526900D826EB906462314,5F1E256061D813B125E156E8E6266D4AC0962C7D,D75CEA17048B9ACBF186794B32637D44F14F620E,A2923DFF56EDA6E76E55E492D3A80E30382E94DE|trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":["datadog-api-key-required"]},
  {"id":"falco","name":"Falco","documentationUrl":"https://falco.org/docs/setup/packages/","verifiedAt":"2026-08-29","locations":["https://download.falco.org/packages/deb|trixie,bookworm,bullseye,forky,sid|amd64,arm64|stable|main|generic-debian"],"keys":["falco-signing-key|https://falco.org/repo/falcosecurity-packages.asc|/usr/share/keyrings/falco-archive-keyring.gpg|ascii-armored|478B2FBBC75F4237B731DA4365106822B35B1B1F|trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":["falco-driver-setup"]},
  {"id":"trivy","name":"Trivy","documentationUrl":"https://trivy.dev/latest/getting-started/installation/","verifiedAt":"2026-08-29","locations":["https://aquasecurity.github.io/trivy-repo/deb|trixie,bookworm,bullseye,forky,sid|amd64,arm64|generic|main|generic-debian"],"keys":["trivy-signing-key|https://aquasecurity.github.io/trivy-repo/deb/public.key|/usr/share/keyrings/trivy.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"crowdsec","name":"CrowdSec","documentationUrl":"https://docs.crowdsec.net/u/getting_started/installation/linux/","verifiedAt":"2026-08-29","locations":["https://packagecloud.io/crowdsec/crowdsec/any|trixie,bookworm,bullseye,forky,sid|amd64,arm64|any|main|generic-debian"],"keys":["crowdsec-signing-key|https://packagecloud.io/crowdsec/crowdsec/gpgkey|/etc/apt/keyrings/crowdsec.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"fluent-bit","name":"Fluent Bit","documentationUrl":"https://docs.fluentbit.io/manual/installation/downloads/linux/debian","verifiedAt":"2026-08-29","locations":["https://packages.fluentbit.io/debian/trixie|trixie|amd64,arm64|trixie|main|explicit","https://packages.fluentbit.io/debian/bookworm|bookworm|amd64,arm64|bookworm|main|explicit","https://packages.fluentbit.io/debian/bullseye|bullseye|amd64,arm64|bullseye|main|explicit"],"keys":["fluent-bit-signing-key|https://packages.fluentbit.io/fluentbit.key|/usr/share/keyrings/fluentbit-keyring.gpg|ascii-armored|C3C0A28534B9293EAF51FABD9F9DDC083888C1CD|trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"dbeaver","name":"DBeaver Community","documentationUrl":"https://dbeaver.io/download/","verifiedAt":"2026-08-29","locations":["https://dbeaver.io/debs/dbeaver-ce|trixie,bookworm,bullseye,forky,sid|amd64,arm64|/||generic-debian"],"keys":["dbeaver-signing-key|https://dbeaver.io/debs/dbeaver.gpg.key|/usr/share/keyrings/dbeaver.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"buildkite-agent","name":"Buildkite Agent","documentationUrl":"https://buildkite.com/docs/agent/v3/installation","verifiedAt":"2026-08-29","locations":["https://apt.buildkite.com/buildkite-agent|trixie,bookworm,bullseye,forky,sid|amd64,arm64|stable|main|generic-debian"],"keys":["buildkite-agent-signing-key|https://apt.buildkite.com/buildkite-agent/gpgkey|/usr/share/keyrings/buildkite-agent-archive-keyring.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":["buildkite-agent-token-required"]},
  {"id":"buildkite-cli","name":"Buildkite CLI","documentationUrl":"https://buildkite.com/docs/platform/cli/installation","verifiedAt":"2026-08-29","locations":["https://packages.buildkite.com/buildkite/cli-deb/any/|trixie,bookworm,bullseye,forky,sid|amd64,arm64|any|main|generic-debian"],"keys":["buildkite-cli-signing-key|https://packages.buildkite.com/buildkite/cli-deb/gpgkey|/usr/share/keyrings/buildkite-cli-archive-keyring.gpg|ascii-armored||trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"zerotier-one","name":"ZeroTier One","documentationUrl":"https://www.zerotier.com/download/","verifiedAt":"2026-08-29","locations":["https://download.zerotier.com/debian/trixie|trixie|amd64,arm64,armhf,i386|trixie|main|explicit","https://download.zerotier.com/debian/bookworm|bookworm|amd64,arm64,armhf,i386|bookworm|main|explicit","https://download.zerotier.com/debian/bullseye|bullseye|amd64,arm64,armhf,i386|bullseye|main|explicit"],"keys":["zerotier-one-signing-key|https://download.zerotier.com/contact%40zerotier.com.gpg|/usr/share/keyrings/zerotier-debian-package-key.gpg|ascii-armored||trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"netbird","name":"NetBird","documentationUrl":"https://docs.netbird.io/get-started/install/linux","verifiedAt":"2026-08-29","locations":["https://pkgs.netbird.io/debian|bookworm|amd64,arm64,armhf|stable|main|explicit"],"keys":["netbird-signing-key|https://pkgs.netbird.io/debian/public.key|/usr/share/keyrings/netbird-archive-keyring.gpg|ascii-armored||bookworm"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"openvpn-community","name":"OpenVPN Community","documentationUrl":"https://community.openvpn.net/Pages/OpenVPN%20software%20repos","verifiedAt":"2026-08-29","locations":["https://build.openvpn.net/debian/openvpn/stable|trixie|amd64|trixie|main|explicit","https://build.openvpn.net/debian/openvpn/stable|trixie|arm64|trixie|main|explicit","https://build.openvpn.net/debian/openvpn/stable|bookworm|amd64|bookworm|main|explicit","https://build.openvpn.net/debian/openvpn/stable|bookworm|arm64|bookworm|main|explicit","https://build.openvpn.net/debian/openvpn/stable|bullseye|amd64|bullseye|main|explicit","https://build.openvpn.net/debian/openvpn/stable|bullseye|arm64|bullseye|main|explicit"],"keys":["openvpn-community-signing-key|https://swupdate.openvpn.net/repos/repo-public.gpg|/etc/apt/keyrings/openvpn-repo-public.asc|ascii-armored||trixie,bookworm,bullseye"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"librewolf","name":"LibreWolf","documentationUrl":"https://librewolf.net/installation/debian/","verifiedAt":"2026-08-29","locations":["https://repo.librewolf.net|trixie,bookworm,bullseye,forky,sid|amd64,arm64|librewolf|main|generic-debian"],"keys":["librewolf-signing-key|https://repo.librewolf.net/pubkey.gpg|/etc/apt/keyrings/librewolf.asc|ascii-armored|662E3CDD6FE329002D0CA5BB40339DD82B12EF16|trixie,bookworm,bullseye,forky,sid"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
  {"id":"lutris","name":"Lutris","documentationUrl":"https://lutris.net/downloads","verifiedAt":"2026-08-29","locations":["https://download.opensuse.org/repositories/home:/strycore:/lutris/Debian_13/|trixie|amd64|./||explicit"],"keys":["lutris-signing-key|https://download.opensuse.org/repositories/home:/strycore:/lutris/Debian_13/Release.key|/etc/apt/keyrings/lutris.gpg|ascii-armored||trixie"],"auxiliaryTrustFiles":[],"preferenceFiles":[],"warnings":[]},
] as const

function sourceMetadata(source: RepositorySource) {
  return {
    id: source.id,
    name: source.name,
    documentationUrl: source.documentationUrl,
    verifiedAt: source.verifiedAt,
    locations: source.locations.map((location) => [
      location.uri,
      location.releases.join(','),
      location.architectures.join(','),
      location.suite,
      location.components.join(','),
      location.supportLevel,
    ].join('|')),
    keys: source.keys.map((key) => [
      key.id,
      key.url,
      key.keyringPath,
      key.format,
      key.fingerprints.join(','),
      key.releases.join(','),
    ].join('|')),
    auxiliaryTrustFiles: source.auxiliaryTrustFiles,
    preferenceFiles: source.preferenceFiles,
    warnings: source.warnings,
  }
}

describe('repository source migration', () => {
  it('retains the exact authoritative definition for every original source', () => {
    expect(REPOSITORY_SOURCES.slice(0, expectedSources.length).map(sourceMetadata)).toEqual(expectedSources)
  })

  it('retains the complete exact metadata table for all approved source definitions', () => {
    expect(REPOSITORY_SOURCES.slice(expectedSources.length).map(sourceMetadata)).toEqual(expectedAdditionalSources)
  })

  it('models shared, release-scoped, multi-key, exact-path, auxiliary and preference cases', () => {
    const onepassword = getRepositorySource('onepassword')
    expect(onepassword).toMatchObject({
      locations: [
        { uri: 'https://downloads.1password.com/linux/debian/amd64', architectures: ['amd64'], suite: 'stable', components: ['main'] },
        { uri: 'https://downloads.1password.com/linux/debian/arm64', architectures: ['arm64'], suite: 'stable', components: ['main'] },
      ],
      auxiliaryTrustFiles: [
        { id: 'onepassword-policy', url: 'https://downloads.1password.com/linux/debian/debsig/1password.pol', destination: 'debsig-policy', mediaType: 'application/xml' },
        { id: 'onepassword-keyring', url: 'https://downloads.1password.com/linux/keys/1password.asc', destination: 'debsig-keyring', mediaType: 'application/pgp-keys', fingerprint: '3FEF9748469ADBE15DA7CA80AC2D62742012EA22' },
      ],
    })

    expect(getRepositorySource('opentofu')?.keys).toEqual([
      { id: 'opentofu-release-key', url: 'https://get.opentofu.org/opentofu.gpg', keyringPath: '/etc/apt/keyrings/opentofu.gpg', format: 'binary', fingerprints: [], releases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'] },
      { id: 'opentofu-package-key', url: 'https://packages.opentofu.org/opentofu/tofu/gpgkey', keyringPath: '/etc/apt/keyrings/opentofu-repo.gpg', format: 'ascii-armored', fingerprints: [], releases: ['trixie', 'bookworm', 'bullseye', 'forky', 'sid'] },
    ])

    expect(getRepositorySource('tailscale')?.keys.map(({ url, releases }) => ({ url, releases }))).toEqual([
      { url: 'https://pkgs.tailscale.com/stable/debian/trixie.noarmor.gpg', releases: ['trixie'] },
      { url: 'https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg', releases: ['bookworm'] },
      { url: 'https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg', releases: ['bullseye'] },
      { url: 'https://pkgs.tailscale.com/stable/debian/forky.noarmor.gpg', releases: ['forky'] },
      { url: 'https://pkgs.tailscale.com/stable/debian/sid.noarmor.gpg', releases: ['sid'] },
    ])

    expect(getRepositorySource('microsoft-prod')?.locations.map(({ uri, releases, suite }) => ({ uri, releases, suite }))).toEqual([
      { uri: 'https://packages.microsoft.com/debian/13/prod', releases: ['trixie'], suite: 'trixie' },
      { uri: 'https://packages.microsoft.com/debian/12/prod', releases: ['bookworm'], suite: 'bookworm' },
    ])
    expect(getRepositorySource('sublime')?.locations[0]).toMatchObject({ suite: 'apt/stable/', components: [] })
    expect(getRepositorySource('jenkins-lts')?.locations[0]).toMatchObject({ suite: 'binary/', components: [] })
    expect(getRepositorySource('jenkins-weekly')?.locations[0]).toMatchObject({ suite: 'binary/', components: [] })

    expect(getRepositorySource('nginx-stable')?.preferenceFiles).toEqual([{ id: 'nginx', content: 'Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n' }])
    const nginxFingerprints = [
      '573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62',
      '8540A6F18833A80E9C1653A42FD21310B49F6B46',
      '9E9BE90EACBCDE69FE9B204CBCDCD8A38D88A2B3',
    ]
    expect(getRepositorySource('nginx-stable')?.keys[0]?.fingerprints).toEqual(nginxFingerprints)
    expect(getRepositorySource('nginx-mainline')?.keys[0]?.fingerprints).toEqual(nginxFingerprints)
    expect(getRepositorySource('syncthing')?.preferenceFiles).toEqual([{ id: 'syncthing', content: 'Package: *\nPin: origin apt.syncthing.net\nPin-Priority: 990\n' }])
  })

  it('uses only the researched official HTTPS ZeroTier and NetBird feeds', () => {
    expect(getRepositorySource('zerotier-one')).toMatchObject({
      documentationUrl: 'https://www.zerotier.com/download/',
      locations: [
        { uri: 'https://download.zerotier.com/debian/trixie', releases: ['trixie'], architectures: ['amd64', 'arm64', 'armhf', 'i386'], suite: 'trixie', components: ['main'], supportLevel: 'explicit' },
        { uri: 'https://download.zerotier.com/debian/bookworm', releases: ['bookworm'], architectures: ['amd64', 'arm64', 'armhf', 'i386'], suite: 'bookworm', components: ['main'], supportLevel: 'explicit' },
        { uri: 'https://download.zerotier.com/debian/bullseye', releases: ['bullseye'], architectures: ['amd64', 'arm64', 'armhf', 'i386'], suite: 'bullseye', components: ['main'], supportLevel: 'explicit' },
      ],
      keys: [{
        id: 'zerotier-one-signing-key',
        url: 'https://download.zerotier.com/contact%40zerotier.com.gpg',
        keyringPath: '/usr/share/keyrings/zerotier-debian-package-key.gpg',
        format: 'ascii-armored',
        releases: ['trixie', 'bookworm', 'bullseye'],
      }],
    })
    expect(getRepositorySource('netbird')).toMatchObject({
      documentationUrl: 'https://docs.netbird.io/get-started/install/linux',
      locations: [{
        uri: 'https://pkgs.netbird.io/debian',
        releases: ['bookworm'],
        architectures: ['amd64', 'arm64', 'armhf'],
        suite: 'stable',
        components: ['main'],
        supportLevel: 'explicit',
      }],
      keys: [{
        id: 'netbird-signing-key',
        url: 'https://pkgs.netbird.io/debian/public.key',
        keyringPath: '/usr/share/keyrings/netbird-archive-keyring.gpg',
        format: 'ascii-armored',
        releases: ['bookworm'],
      }],
    })
  })

  it('provides an immutable source catalog', () => {
    expect(Object.isFrozen(REPOSITORY_SOURCES)).toBe(true)
    expect(REPOSITORY_SOURCES.every(Object.isFrozen)).toBe(true)
  })

  it('resolves known source IDs and leaves unknown IDs unresolved', () => {
    expect(getRepositorySource('hashicorp')?.name).toBe('HashiCorp')
    expect(getRepositorySource('unknown-source')).toBeUndefined()
  })
})
