-- phpMyAdmin SQL Dump
-- version 4.6.6
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Apr 27, 2017 at 06:52 PM
-- Server version: 5.5.55-0+deb8u1
-- PHP Version: 5.6.30-0+deb8u1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `c1_debgen`
--

-- --------------------------------------------------------

--
-- Table structure for table `deb_release`
--

CREATE TABLE `deb_release` (
  `release_id` int(15) NOT NULL,
  `release_code` varchar(255) NOT NULL,
  `release_name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `deb_release`
--

INSERT INTO `deb_release` (`release_id`, `release_code`, `release_name`) VALUES
(1, 'oldstable', 'Oldstable (Wheezy)'),
(2, 'stable', 'Stable (Jessie)'),
(3, 'testing', 'Testing (Stretch)'),
(4, 'unstable', 'Unstable (Sid)');

-- --------------------------------------------------------

--
-- Table structure for table `lastchanges`
--

CREATE TABLE `lastchanges` (
  `lc_id` int(11) NOT NULL,
  `lc_date` date NOT NULL,
  `lc_text` tinytext NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `lastchanges`
--

INSERT INTO `lastchanges` (`lc_id`, `lc_date`, `lc_text`) VALUES
(1, '2009-12-12', 'Last Changes section added'),
(4, '2009-12-12', 'Added option to click the text next to the select boxes in order to un/check them'),
(5, '2010-01-08', 'Added a rss feed for the updates to the site'),
(6, '2010-01-28', 'Fixed Skype repo (added the missing \'deb\')'),
(7, '2010-01-28', 'Unofficial Maintainers repo added to Lenny'),
(8, '2010-01-28', 'Unofficial Maintainers repo added to Squeeze'),
(9, '2010-01-28', 'Unofficial Maintainers repo added to Sid'),
(10, '2011-03-15', 'MAJOR UPDATE:\r\n\r\n-Altered \'stable\' from Lenny to Squeeze\r\n- Differentiate 3rd party repos between \"release names\" (e.g. Squeeze) and \"development status\" (e.g. stable) - this will enable better and faster update the next time\r\n- Removed Debian Volatile'),
(11, '2011-04-21', 'Updated GPG Key location for VirtualBox'),
(12, '2011-04-21', 'Added Belarus to country list'),
(13, '2011-04-21', 'Fixed Sid and Experimental generation bug'),
(14, '2016-04-23', 'Restored old project site since new one wasn\'t working and maintained anymore.'),
(15, '2016-04-23', 'Added FusionDirectory repo to Jessie'),
(17, '2016-04-23', 'Added Opera and Opera (Beta Release) repos'),
(18, '2016-04-23', 'Added Proxmox VE repo to Jessie'),
(19, '2016-04-23', 'Added CRAN for Debian repo to Jessie'),
(20, '2016-04-23', 'Added Tor Project repos'),
(21, '2016-04-23', 'Added PlayOnLinux repo to Jessie'),
(22, '2016-04-23', 'Added PlayOnLinux repo to Stretch'),
(23, '2016-04-23', 'Added Swiftfox repos'),
(24, '2016-04-23', 'Added EDuke32 repo to Jessie'),
(25, '2016-04-23', 'Added EDuke32 repo to Stretch'),
(26, '2016-04-23', 'Added ownCloud Desktop Client repo to Jessie'),
(27, '2016-04-23', 'Added Daniil\'s Bash Video Download repos'),
(28, '2016-04-23', 'Added Dropbox repo to Jessie'),
(29, '2016-04-23', 'Added Google Chrome Browser repos'),
(30, '2016-04-23', 'Added Google Earth repos'),
(31, '2016-04-23', 'Added Lazarus repos'),
(32, '2016-04-23', 'Added Lazarus (Testing) repos'),
(33, '2016-04-23', 'Added MEGA Sync Client repo to Jessie'),
(34, '2016-04-23', 'Added MEGA Sync Client repo to Stretch'),
(35, '2016-04-23', 'Added muCommander repos'),
(36, '2016-04-23', 'Added muCommander (testing) repos'),
(37, '2016-04-23', 'Added Samsung Unified Linux Driver Repository (SULDR) repos'),
(38, '2016-04-23', 'Added Spotify repos'),
(39, '2016-04-23', 'Added Steam for Linux repos'),
(40, '2016-04-23', 'Added VirtualBox repo to Jessie'),
(41, '2016-04-23', 'Added Yuuguu repos'),
(42, '2016-04-24', 'Added Mono for Debian repos'),
(43, '2016-04-24', 'Added Debian Mozilla team repo to Jessie'),
(44, '2016-04-25', 'New Maintainer for DebGen (Malte K.)'),
(45, '2016-04-29', 'Updated VirtualBox gpg key for Jessie'),
(46, '2016-05-06', 'Added Syncthing repo.'),
(47, '2016-05-11', 'Fix Error in Virtualbox Repo'),
(48, '2016-05-11', 'Added Wine Original Repo'),
(49, '2016-05-11', 'Added MariaDB Repo for wheeze, jessie and sid'),
(50, '2016-06-15', 'Remove Skype Repos (Skype closed his Repo for Debian)'),
(51, '2016-06-15', 'Fixed: Removed all sudo commands from key recieving'),
(52, '2016-06-29', 'Added: Jessie Backports\r\n'),
(53, '2016-06-29', 'Added: OpenMediaVault'),
(54, '2016-10-09', 'Added Resilio Sync'),
(55, '2016-10-09', 'Added Ceph'),
(56, '2016-11-15', 'Added Dropbox (unstable)'),
(57, '2016-11-20', 'Added Mozilla Firefox Release, Beta, Aurora for Jessie'),
(60, '2016-11-20', 'Added Mozilla Firefox Aurora for Unstable'),
(59, '2016-11-20', 'Added Mozilla Firefox Aurora for Testing'),
(61, '2017-02-20', 'Added: Docker Jessie'),
(62, '2017-02-20', 'Added: Docker Stretch'),
(63, '2017-02-20', 'Added: Jessie Backports'),
(64, '2017-02-20', 'Added: Wheezy Backports'),
(65, '2017-02-20', 'Fixed: http://repo.daniil.it GPG Key issues'),
(66, '2017-02-20', 'Fixed: http://mega.nz GPG Key issues'),
(67, '2017-02-20', 'Fixed: http://update.yuuguu.com GPG Key issues'),
(68, '2017-02-20', 'Removed: GetSwiftFox (Server Does Not exists anymore)'),
(69, '2017-02-20', 'Removed: Google Chrome 32Bit Support'),
(70, '2017-02-20', 'Added: FusionDirectory Jessie'),
(71, '2017-02-20', 'Added: FusionDirectory Wheezy'),
(72, '2017-02-20', 'Removed: debian-maintainers.org (Server Does Not exists anymore)'),
(73, '2017-02-21', 'New Release / New Design'),
(74, '2017-02-22', 'Added: TOX Repo'),
(75, '2017-02-22', 'Added: Jabber.at ejabberd Repo'),
(76, '2017-02-22', 'Added: Jabber.at gajim Repo'),
(77, '2017-02-22', 'Added: Jabber.at mcabber Repo'),
(78, '2017-02-22', 'Added: Vivaldi Browser Repo'),
(79, '2017-02-22', 'Added: Android Studio Repo'),
(80, '2017-02-24', 'Added: Jessie Backports'),
(81, '2017-02-24', 'Added: Wheezy Backports'),
(82, '2017-02-28', 'Added: Paper GTK Theme'),
(83, '2017-02-28', 'Added: Papirus GTK Theme'),
(84, '2017-03-22', 'Removed: Android Studio Repo'),
(85, '2017-03-22', 'Fixed: Deb Multimedia'),
(86, '2017-03-22', 'Added: Support for deb.debian.org'),
(87, '2017-04-19', 'Added: Squash TM'),
(88, '2017-04-19', 'Added: Skype');

-- --------------------------------------------------------

--
-- Table structure for table `repos`
--

CREATE TABLE `repos` (
  `repo_id` int(15) NOT NULL,
  `repo_name` varchar(255) NOT NULL,
  `repo_desc` text NOT NULL,
  `repo_url` text NOT NULL,
  `repo_url_src` text NOT NULL,
  `repo_gpg` text NOT NULL,
  `repo_arch` text NOT NULL,
  `repo_homepage` text NOT NULL,
  `repo_documentation` text NOT NULL,
  `repo_release` int(15) NOT NULL,
  `repo_checked` int(15) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `repos`
--

INSERT INTO `repos` (`repo_id`, `repo_name`, `repo_desc`, `repo_url`, `repo_url_src`, `repo_gpg`, `repo_arch`, `repo_homepage`, `repo_documentation`, `repo_release`, `repo_checked`) VALUES
(3, 'Debian Multimedia', 'The Debian Multimedia repository is a repository that contains a lot of up-to-date multimedia related packages like mplayer, mencoder, transcode, dvd::rip, ffmpeg, avidemux, acidrip, kplayer, lame, kdenlive, xvid, mjpegtools, codecs, w32codecs etc.', 'deb http://www.deb-multimedia.org oldstable main non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 5C808C2B65558117', 'all', 'http://deb-multimedia.org/', 'http://deb-multimedia.org/', 1, 1),
(4, 'Debian Multimedia', 'The Debian Multimedia repository is a repository that contains a lot of up-to-date multimedia related packages like mplayer, mencoder, transcode, dvd::rip, ffmpeg, avidemux, acidrip, kplayer, lame, kdenlive, xvid, mjpegtools, codecs, w32codecs etc.', 'deb http://www.deb-multimedia.org jessie main non-free\r\ndeb http://www.deb-multimedia.org jessie-backports main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 5C808C2B65558117', 'amd64,armel,armhf,i386,kfreebsd-amd64,kfreebsd-i386,mips,mipsel,powerpc', 'http://deb-multimedia.org/', 'http://deb-multimedia.org/', 2, 1),
(5, 'Debian Multimedia', 'The Debian Multimedia repository is a repository that contains a lot of up-to-date multimedia related packages like mplayer, mencoder, transcode, dvd::rip, ffmpeg, avidemux, acidrip, kplayer, lame, kdenlive, xvid, mjpegtools, codecs, w32codecs etc.', 'deb http://www.deb-multimedia.org testing main non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 5C808C2B65558117', 'all', 'http://deb-multimedia.org/', 'http://deb-multimedia.org/', 3, 1),
(6, 'Debian Multimedia', 'The Debian Multimedia repository is a repository that contains a lot of up-to-date multimedia related packages like mplayer, mencoder, transcode, dvd::rip, ffmpeg, avidemux, acidrip, kplayer, lame, kdenlive, xvid, mjpegtools, codecs, w32codecs etc.', 'deb http://www.deb-multimedia.org unstable main non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 5C808C2B65558117', 'all', 'http://deb-multimedia.org/', 'http://deb-multimedia.org/', 4, 1),
(7, 'Lazarus', 'Open Source GUI RAD IDE for free Pascal', 'deb http://www.hu.freepascal.org/lazarus/ lazarus-oldstable universe', '', 'gpg --keyserver hkp://pgp.mit.edu:11371 --recv-keys 6A11800F  && gpg --export --armor 0F7992B0  | apt-key add -', 'all', 'http://www.lazarus.freepascal.org/', 'http://wiki.lazarus.freepascal.org/Lazarus_release_version_for_Ubuntu', 1, 1),
(8, 'Lazarus', 'Open Source GUI RAD IDE for free Pascal', 'deb http://www.hu.freepascal.org/lazarus/ lazarus-stable universe', '', 'gpg --keyserver hkp://pgp.mit.edu:11371 --recv-keys 6A11800F  && gpg --export --armor 0F7992B0 | apt-key add -', 'all', 'http://www.lazarus.freepascal.org/', 'http://wiki.lazarus.freepascal.org/Lazarus_release_version_for_Ubuntu', 2, 1),
(9, 'Lazarus', 'Open Source GUI RAD IDE for free Pascal', 'deb http://www.hu.freepascal.org/lazarus/ lazarus-stable universe', '', 'gpg --keyserver hkp://pgp.mit.edu:11371 --recv-keys 6A11800F  && gpg --export --armor 0F7992B0 | apt-key add -', 'i386', 'http://www.lazarus.freepascal.org/', 'http://wiki.lazarus.freepascal.org/Lazarus_release_version_for_Ubuntu', 4, 1),
(10, 'Google Chrome Browser', 'Google Chrome runs websites and applications with lightning speed.', 'deb http://dl.google.com/linux/chrome/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 1, 1),
(11, 'Google Chrome Browser', 'Google Chrome runs websites and applications with lightning speed.', 'deb http://dl.google.com/linux/chrome/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 2, 1),
(12, 'Google Chrome Browser', 'Google Chrome runs websites and applications with lightning speed.', 'deb http://dl.google.com/linux/chrome/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 3, 1),
(13, 'Google Chrome Browser', 'Google Chrome runs websites and applications with lightning speed.', 'deb http://dl.google.com/linux/chrome/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 4, 1),
(14, 'Google Earth', 'Get the world?s geographic information at your fingertips. Take a virtual journey to any location in the world. Explore 3D buildings, imagery, and terrain. Find cities, places and local businesses.', 'deb http://dl.google.com/linux/earth/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 1, 1),
(15, 'Google Earth', 'Get the world?s geographic information at your fingertips. Take a virtual journey to any location in the world. Explore 3D buildings, imagery, and terrain. Find cities, places and local businesses.', 'deb http://dl.google.com/linux/earth/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 2, 1),
(16, 'Google Earth', 'Get the world?s geographic information at your fingertips. Take a virtual journey to any location in the world. Explore 3D buildings, imagery, and terrain. Find cities, places and local businesses.', 'deb http://dl.google.com/linux/earth/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 3, 1),
(17, 'Google Earth', 'Get the world?s geographic information at your fingertips. Take a virtual journey to any location in the world. Explore 3D buildings, imagery, and terrain. Find cities, places and local businesses.', 'deb http://dl.google.com/linux/earth/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 4, 1),
(18, 'Docker', 'Docker containers wrap up a piece of software in a complete filesystem that contains everything it needs to run: code, runtime, system tools, system libraries ? anything you can install on a server. This guarantees that it will always run the same, regardless of the environment it is running in.', 'deb https://apt.dockerproject.org/repo/ debian-stretch main', '', 'curl -fsSL https://apt.dockerproject.org/gpg | sudo apt-key add -', 'all', 'https://docker.com', 'https://docs.docker.com', 3, 1),
(19, 'Docker', 'Docker containers wrap up a piece of software in a complete filesystem that contains everything it needs to run: code, runtime, system tools, system libraries ? anything you can install on a server. This guarantees that it will always run the same, regardless of the environment it is running in.', 'deb https://apt.dockerproject.org/repo/ debian-jessie main', '', 'curl -fsSL https://apt.dockerproject.org/gpg | sudo apt-key add -', 'all', 'https://docker.com', 'https://docs.docker.com', 2, 1),
(20, 'Mozilla Firefox Aurora', 'Firefox Aurora from Mozilla', 'deb http://mozilla.debian.net/ experimental firefox-aurora', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 85A3D26506C4AE2A', 'all', 'https://mozilla.org', 'https://support.mozilla.org/', 3, 1),
(21, 'Mozilla Firefox Aurora', 'Firefox Aurora from Mozilla', 'deb http://mozilla.debian.net/ experimental firefox-aurora', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 85A3D26506C4AE2A', 'all', 'https://mozilla.org', 'https://support.mozilla.org/', 4, 1),
(22, 'Virtualbox', 'Oracle VM VirtualBox (formerly Sun VirtualBox, Sun xVM VirtualBox and Innotek VirtualBox) is a free and open-source hypervisor for x86 computers currently being developed by Oracle Corporation. Developed initially by Innotek GmbH, it was acquired by Sun Microsystems in 2008 which was in turn acquired by Oracle in 2010.', 'deb http://download.virtualbox.org/virtualbox/debian jessie contrib non-free', '', 'wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -\r\nwget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -', 'i386,amd64', 'https://www.virtualbox.org', 'https://www.virtualbox.org/wiki/', 2, 1),
(23, 'Virtualbox', 'Oracle VM VirtualBox (formerly Sun VirtualBox, Sun xVM VirtualBox and Innotek VirtualBox) is a free and open-source hypervisor for x86 computers currently being developed by Oracle Corporation. Developed initially by Innotek GmbH, it was acquired by Sun Microsystems in 2008 which was in turn acquired by Oracle in 2010.', 'deb http://download.virtualbox.org/virtualbox/debian wheezy contrib', '', 'wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -\r\nwget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -', 'i386,amd64', 'https://www.virtualbox.org', 'https://www.virtualbox.org/wiki/', 1, 1),
(24, 'Spotify', 'Spotify is a music, podcast, and video streaming service, officially launched on 7 October 2008. It is developed by startup Spotify AB in Stockholm, Sweden. It provides digital rights management-protected content from record labels and media companies. Spotify is a freemium service, meaning that basic features are free with advertisements, while additional features, including improved streaming quality and offline music downloads, are offered via paid subscriptions.', 'deb http://repository.spotify.com stable non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 13B00F1FD2C19886', 'all', 'https://www.spotify.com/en/download/linux/', 'https://www.spotify.com/de/download/linux/', 1, 1),
(25, 'Spotify', 'Spotify is a music, podcast, and video streaming service, officially launched on 7 October 2008. It is developed by startup Spotify AB in Stockholm, Sweden. It provides digital rights management-protected content from record labels and media companies. Spotify is a freemium service, meaning that basic features are free with advertisements, while additional features, including improved streaming quality and offline music downloads, are offered via paid subscriptions.', 'deb http://repository.spotify.com stable non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 13B00F1FD2C19886', 'all', 'https://www.spotify.com/en/download/linux/', 'https://www.spotify.com/de/download/linux/', 2, 1),
(26, 'Spotify', 'Spotify is a music, podcast, and video streaming service, officially launched on 7 October 2008. It is developed by startup Spotify AB in Stockholm, Sweden. It provides digital rights management-protected content from record labels and media companies. Spotify is a freemium service, meaning that basic features are free with advertisements, while additional features, including improved streaming quality and offline music downloads, are offered via paid subscriptions.', 'deb http://repository.spotify.com stable non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 13B00F1FD2C19886', 'all', 'https://www.spotify.com/en/download/linux/', 'https://www.spotify.com/de/download/linux/', 3, 1),
(27, 'Spotify', 'Spotify is a music, podcast, and video streaming service, officially launched on 7 October 2008. It is developed by startup Spotify AB in Stockholm, Sweden. It provides digital rights management-protected content from record labels and media companies. Spotify is a freemium service, meaning that basic features are free with advertisements, while additional features, including improved streaming quality and offline music downloads, are offered via paid subscriptions.', 'deb http://repository.spotify.com stable non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 13B00F1FD2C19886', 'all', 'https://www.spotify.com/en/download/linux/', 'https://www.spotify.com/de/download/linux/', 4, 1),
(28, 'Steam', 'Steam is a digital distribution platform developed by Valve Corporation, which offers digital rights management (DRM), multiplayer gaming, and social networking services. Steam provides the user with installation and automatic updating of games on multiple computers, and community features such as friends lists and groups, cloud saving, and in-game voice and chat functionality. The software provides a freely available application programming interface (API) called Steamworks, which developers can use to integrate many of Steam\'s functions into their products, including networking, matchmaking, in-game achievements, micro-transactions, and support for user-created content through Steam Workshop. Though initially developed for use on Microsoft Windows operating systems, versions for OS X and Linux were later released. Mobile apps with connected functionality with the main software were later released for iOS, Android, and Windows Phone devices in the 2010s.', 'deb http://repo.steampowered.com/steam/ precise steam', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F24AEA9FB05498B7', 'i386,amd64', 'http://store.steampowered.com/', 'http://store.steampowered.com/about/', 1, 1),
(29, 'Steam', 'Steam is a digital distribution platform developed by Valve Corporation, which offers digital rights management (DRM), multiplayer gaming, and social networking services. Steam provides the user with installation and automatic updating of games on multiple computers, and community features such as friends lists and groups, cloud saving, and in-game voice and chat functionality. The software provides a freely available application programming interface (API) called Steamworks, which developers can use to integrate many of Steam\'s functions into their products, including networking, matchmaking, in-game achievements, micro-transactions, and support for user-created content through Steam Workshop. Though initially developed for use on Microsoft Windows operating systems, versions for OS X and Linux were later released. Mobile apps with connected functionality with the main software were later released for iOS, Android, and Windows Phone devices in the 2010s.', 'deb http://repo.steampowered.com/steam/ precise steam', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F24AEA9FB05498B7', 'i386,amd64', 'http://store.steampowered.com/', 'http://store.steampowered.com/about/', 2, 1),
(30, 'Steam', 'Steam is a digital distribution platform developed by Valve Corporation, which offers digital rights management (DRM), multiplayer gaming, and social networking services. Steam provides the user with installation and automatic updating of games on multiple computers, and community features such as friends lists and groups, cloud saving, and in-game voice and chat functionality. The software provides a freely available application programming interface (API) called Steamworks, which developers can use to integrate many of Steam\'s functions into their products, including networking, matchmaking, in-game achievements, micro-transactions, and support for user-created content through Steam Workshop. Though initially developed for use on Microsoft Windows operating systems, versions for OS X and Linux were later released. Mobile apps with connected functionality with the main software were later released for iOS, Android, and Windows Phone devices in the 2010s.', 'deb http://repo.steampowered.com/steam/ precise steam', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F24AEA9FB05498B7', 'i386,amd64', 'http://store.steampowered.com/', 'http://store.steampowered.com/about/', 3, 1),
(31, 'Steam', 'Steam is a digital distribution platform developed by Valve Corporation, which offers digital rights management (DRM), multiplayer gaming, and social networking services. Steam provides the user with installation and automatic updating of games on multiple computers, and community features such as friends lists and groups, cloud saving, and in-game voice and chat functionality. The software provides a freely available application programming interface (API) called Steamworks, which developers can use to integrate many of Steam\'s functions into their products, including networking, matchmaking, in-game achievements, micro-transactions, and support for user-created content through Steam Workshop. Though initially developed for use on Microsoft Windows operating systems, versions for OS X and Linux were later released. Mobile apps with connected functionality with the main software were later released for iOS, Android, and Windows Phone devices in the 2010s.', 'deb http://repo.steampowered.com/steam/ precise steam', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F24AEA9FB05498B7', 'i386,amd64', 'http://store.steampowered.com/', 'http://store.steampowered.com/about/', 4, 1),
(32, 'Wine', 'Wine (recursive acronym for Wine Is Not an Emulator) is a free and open source compatibility layer software application that aims to allow applications designed for Microsoft Windows to run on Unix-like operating systems. Wine also provides a software library, known as Winelib, against which developers can compile Windows applications to help port them to Unix-like systems.[7]', 'deb https://dl.winehq.org/wine-builds/debian/ wheezy main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 818A435C5FCBF54A', 'i386', 'https://winehq.org/', 'https://wiki.winehq.org/Debian', 1, 1),
(33, 'Wine', 'Wine (recursive acronym for Wine Is Not an Emulator) is a free and open source compatibility layer software application that aims to allow applications designed for Microsoft Windows to run on Unix-like operating systems. Wine also provides a software library, known as Winelib, against which developers can compile Windows applications to help port them to Unix-like systems.[7]', 'deb https://dl.winehq.org/wine-builds/debian/ jessie main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 818A435C5FCBF54A', 'i386', 'https://winehq.org/', 'https://wiki.winehq.org/Debian', 2, 1),
(34, 'Wine', 'Wine (recursive acronym for Wine Is Not an Emulator) is a free and open source compatibility layer software application that aims to allow applications designed for Microsoft Windows to run on Unix-like operating systems. Wine also provides a software library, known as Winelib, against which developers can compile Windows applications to help port them to Unix-like systems.[7]', 'deb https://dl.winehq.org/wine-builds/debian/ stretch main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 818A435C5FCBF54A', 'i386', 'https://winehq.org/', 'https://wiki.winehq.org/Debian', 3, 1),
(35, 'Wine', 'Wine (recursive acronym for Wine Is Not an Emulator) is a free and open source compatibility layer software application that aims to allow applications designed for Microsoft Windows to run on Unix-like operating systems. Wine also provides a software library, known as Winelib, against which developers can compile Windows applications to help port them to Unix-like systems.[7]', 'deb https://dl.winehq.org/wine-builds/debian/ sid main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 818A435C5FCBF54A', 'i386', 'https://winehq.org/', 'https://wiki.winehq.org/Debian', 4, 1),
(36, 'Opera', 'Opera is a web browser for Windows, macOS, and Linux operating systems. It is developed by Opera Software. As of November 2016, the browser is owned by a Chinese group of investors under the name Golden Brick Capital Private Equity Fund I Limited Partnership.', 'deb https://deb.opera.com/opera-stable/ stable non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 63F7D4AFF6D61D45', 'all', 'http://opera.com', 'http://deb.opera.com/manual.html', 1, 1),
(37, 'Opera', 'Opera is a web browser for Windows, macOS, and Linux operating systems. It is developed by Opera Software. As of November 2016, the browser is owned by a Chinese group of investors under the name Golden Brick Capital Private Equity Fund I Limited Partnership.', 'deb https://deb.opera.com/opera-stable/ stable non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 63F7D4AFF6D61D45', 'all', 'http://opera.com', 'http://deb.opera.com/manual.html', 2, 1),
(38, 'Opera', 'Opera is a web browser for Windows, macOS, and Linux operating systems. It is developed by Opera Software. As of November 2016, the browser is owned by a Chinese group of investors under the name Golden Brick Capital Private Equity Fund I Limited Partnership.', 'deb https://deb.opera.com/opera-stable/ stable non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 63F7D4AFF6D61D45', 'all', 'http://opera.com', 'http://deb.opera.com/manual.html', 3, 1),
(39, 'Opera', 'Opera is a web browser for Windows, macOS, and Linux operating systems. It is developed by Opera Software. As of November 2016, the browser is owned by a Chinese group of investors under the name Golden Brick Capital Private Equity Fund I Limited Partnership.', 'deb https://deb.opera.com/opera-stable/ stable non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 63F7D4AFF6D61D45', 'all', 'http://opera.com', 'http://deb.opera.com/manual.html', 4, 1),
(40, 'Esmska', 'Program for sending SMS over the Internet. Anyone can write support for additional gateways.', 'deb http://download.opensuse.org/repositories/Java:/esmska/common-deb/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 29255F95E60A19CD', 'all', 'https://github.com/kparal/esmska', 'https://github.com/kparal/esmska/wiki', 1, 1),
(41, 'Esmska', 'Program for sending SMS over the Internet. Anyone can write support for additional gateways.', 'deb http://download.opensuse.org/repositories/Java:/esmska/common-deb/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 29255F95E60A19CD', 'all', 'https://github.com/kparal/esmska', 'https://github.com/kparal/esmska/wiki', 2, 1),
(42, 'Esmska', 'Program for sending SMS over the Internet. Anyone can write support for additional gateways.', 'deb http://download.opensuse.org/repositories/Java:/esmska/common-deb/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 29255F95E60A19CD', 'all', 'https://github.com/kparal/esmska', 'https://github.com/kparal/esmska/wiki', 3, 1),
(43, 'Esmska', 'Program for sending SMS over the Internet. Anyone can write support for additional gateways.', 'deb http://download.opensuse.org/repositories/Java:/esmska/common-deb/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 29255F95E60A19CD', 'all', 'https://github.com/kparal/esmska', 'https://github.com/kparal/esmska/wiki', 4, 1),
(44, 'muCommander', 'muCommander is a lightweight, cross-platform file manager with a dual-pane interface. It runs on any operating system with Java support (Mac OS X, Windows, Linux, *BSD, Solaris...).', 'deb http://apt.mucommander.com stable main non-free contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 030BBF253A687AFF', 'all', 'http://www.mucommander.com/', 'http://apt.mucommander.com', 1, 1),
(45, 'muCommander', 'muCommander is a lightweight, cross-platform file manager with a dual-pane interface. It runs on any operating system with Java support (Mac OS X, Windows, Linux, *BSD, Solaris...).', 'deb http://apt.mucommander.com stable main non-free contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 030BBF253A687AFF', 'all', 'http://www.mucommander.com/', 'http://apt.mucommander.com', 2, 1),
(46, 'muCommander', 'muCommander is a lightweight, cross-platform file manager with a dual-pane interface. It runs on any operating system with Java support (Mac OS X, Windows, Linux, *BSD, Solaris...).', 'deb http://apt.mucommander.com stable main non-free contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 030BBF253A687AFF', 'all', 'http://www.mucommander.com/', 'http://apt.mucommander.com', 3, 1),
(47, 'muCommander', 'muCommander is a lightweight, cross-platform file manager with a dual-pane interface. It runs on any operating system with Java support (Mac OS X, Windows, Linux, *BSD, Solaris...).', 'deb http://apt.mucommander.com stable main non-free contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 030BBF253A687AFF', 'all', 'http://www.mucommander.com/', 'http://apt.mucommander.com', 4, 1),
(48, 'PlayOnLinux', 'PlayOnLinux is a piece of software which allows you to easily install and use numerous games and apps designed to run with Microsoft? Windows?.\r\nFew games are compatible with GNU/Linux at the moment and it certainly is a factor preventing the migration to this system. PlayOnLinux brings a cost-free, accessible and efficient solution to this problem.', 'deb http://deb.playonlinux.com/ wheezy main', '', 'wget -q \"http://deb.playonlinux.com/public.gpg\" -O- | apt-key add -', 'all', 'https://www.playonlinux.com/', 'https://www.playonlinux.com/en/download.html', 1, 1),
(49, 'PlayOnLinux', 'PlayOnLinux is a piece of software which allows you to easily install and use numerous games and apps designed to run with Microsoft? Windows?.\r\nFew games are compatible with GNU/Linux at the moment and it certainly is a factor preventing the migration to this system. PlayOnLinux brings a cost-free, accessible and efficient solution to this problem.', 'deb http://deb.playonlinux.com/ jessie main', '', 'wget -q \"http://deb.playonlinux.com/public.gpg\" -O- | apt-key add -', 'all', 'https://www.playonlinux.com/', 'https://www.playonlinux.com/en/download.html', 2, 1),
(50, 'ownCloud Client', 'OwnCloud (stylized ownCloud) is a suite of client-server software for creating file hosting services and using them. OwnCloud is functionally very similar to the widely used Dropbox, with the primary functional difference being that OwnCloud is free and open-source, and thereby allowing anyone to install and operate it without charge on a private server. It also supports extensions that allow it to work like Google Drive, with online document editing, calendar and contact synchronization, and more. Its openness eschews enforced quotas on storage space or the number of connected clients, instead having hard limits (like on storage space or number of users) defined only by the physical capabilities of the server.', 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_7.0/ /', '', 'wget http://download.opensuse.org/repositories/isv:ownCloud:desktop/Debian_8.0/Release.key && apt-key add - < Release.key && rm Release.key', 'all', 'https://owncloud.org/', 'https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client', 1, 1),
(51, 'ownCloud Client', 'OwnCloud (stylized ownCloud) is a suite of client-server software for creating file hosting services and using them. OwnCloud is functionally very similar to the widely used Dropbox, with the primary functional difference being that OwnCloud is free and open-source, and thereby allowing anyone to install and operate it without charge on a private server. It also supports extensions that allow it to work like Google Drive, with online document editing, calendar and contact synchronization, and more. Its openness eschews enforced quotas on storage space or the number of connected clients, instead having hard limits (like on storage space or number of users) defined only by the physical capabilities of the server.', 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/ /', '', 'wget http://download.opensuse.org/repositories/isv:ownCloud:desktop/Debian_8.0/Release.key && apt-key add - < Release.key && rm Release.key', 'all', 'https://owncloud.org/', 'https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client', 2, 1),
(52, 'Dropbox', 'Dropbox is a file hosting service operated by American company Dropbox, Inc., headquartered in San Francisco, California, that offers cloud storage, file synchronization, personal cloud, and client software. Dropbox was founded in 2007, by MIT students Drew Houston and Arash Ferdowsi, as a startup company, with initial funding from seed accelerator Y Combinator.', 'deb http://linux.dropbox.com/debian wheezy main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys FC918B335044912E', 'all', 'https://www.dropbox.com/', 'https://www.dropbox.com/en/help/246', 1, 1),
(53, 'Dropbox', 'Dropbox is a file hosting service operated by American company Dropbox, Inc., headquartered in San Francisco, California, that offers cloud storage, file synchronization, personal cloud, and client software. Dropbox was founded in 2007, by MIT students Drew Houston and Arash Ferdowsi, as a startup company, with initial funding from seed accelerator Y Combinator.', 'deb http://linux.dropbox.com/debian jessie main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys FC918B335044912E', 'all', 'https://www.dropbox.com/', 'https://www.dropbox.com/en/help/246', 2, 1),
(54, 'Dropbox', 'Dropbox is a file hosting service operated by American company Dropbox, Inc., headquartered in San Francisco, California, that offers cloud storage, file synchronization, personal cloud, and client software. Dropbox was founded in 2007, by MIT students Drew Houston and Arash Ferdowsi, as a startup company, with initial funding from seed accelerator Y Combinator.', 'deb http://linux.dropbox.com/debian sid main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys FC918B335044912E', 'all', 'https://www.dropbox.com/', 'https://www.dropbox.com/en/help/246', 4, 1),
(55, 'TOR', 'Tor is free software for enabling anonymous communication. The name is derived from an acronym for the original software project name \"The Onion Router\".', 'deb http://deb.torproject.org/torproject.org wheezy main', 'deb-src http://deb.torproject.org/torproject.org wheezy main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 74A941BA219EC810', 'i386,amd64,armel,armhf', 'https://www.torproject.org', 'https://www.torproject.org/docs/debian', 1, 1),
(56, 'TOR', 'Tor is free software for enabling anonymous communication. The name is derived from an acronym for the original software project name \"The Onion Router\".', 'deb http://deb.torproject.org/torproject.org jessie main', 'deb-src http://deb.torproject.org/torproject.org wheezy main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 74A941BA219EC810', 'i386,amd64,armel,armhf', 'https://www.torproject.org', 'https://www.torproject.org/docs/debian', 2, 1),
(57, 'TOR', 'Tor is free software for enabling anonymous communication. The name is derived from an acronym for the original software project name \"The Onion Router\".', 'deb http://deb.torproject.org/torproject.org stretch main', 'deb-src http://deb.torproject.org/torproject.org wheezy main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 74A941BA219EC810', 'i386,amd64,armel,armhf', 'https://www.torproject.org', 'https://www.torproject.org/docs/debian', 3, 1),
(58, 'TOR', 'Tor is free software for enabling anonymous communication. The name is derived from an acronym for the original software project name \"The Onion Router\".', 'deb http://deb.torproject.org/torproject.org sid main', 'deb-src http://deb.torproject.org/torproject.org wheezy main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 74A941BA219EC810', 'i386,amd64,armel,armhf', 'https://www.torproject.org', 'https://www.torproject.org/docs/debian', 4, 1),
(59, 'Syncthing', 'Syncthing is a free, open-source peer-to-peer file synchronization application available for Windows, Mac, Linux, Android, Solaris, Darwin and BSD. It can sync files between devices on a local network, or between remote devices over the Internet. Data security and data safety is built into the design of the software.', 'deb https://apt.syncthing.net/ syncthing stable', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D26E6ED000654A3E', 'all', 'https://syncthing.net/', 'https://apt.syncthing.net/', 1, 1),
(60, 'Syncthing', 'Syncthing is a free, open-source peer-to-peer file synchronization application available for Windows, Mac, Linux, Android, Solaris, Darwin and BSD. It can sync files between devices on a local network, or between remote devices over the Internet. Data security and data safety is built into the design of the software.', 'deb https://apt.syncthing.net/ syncthing stable', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D26E6ED000654A3E', 'all', 'https://syncthing.net/', 'https://apt.syncthing.net/', 4, 1),
(61, 'Webmin', 'Webmin is a web-based interface for system administration for Unix. Using any modern web browser, you can setup user accounts, Apache, DNS, file sharing and much more. Webmin removes the need to manually edit Unix configuration files like /etc/passwd, and lets you manage a system from the console or remotely. See the standard modules page for a list of all the functions built into Webmin.', 'deb http://download.webmin.com/download/repository sarge contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D97A3AE911F63C51', 'all', 'http://www.webmin.com/index.html', 'http://www.webmin.com/deb.html', 1, 1),
(62, 'Webmin', 'Webmin is a web-based interface for system administration for Unix. Using any modern web browser, you can setup user accounts, Apache, DNS, file sharing and much more. Webmin removes the need to manually edit Unix configuration files like /etc/passwd, and lets you manage a system from the console or remotely. See the standard modules page for a list of all the functions built into Webmin.', 'deb http://download.webmin.com/download/repository sarge contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D97A3AE911F63C51', 'all', 'http://www.webmin.com/index.html', 'http://www.webmin.com/deb.html', 2, 1),
(63, 'Webmin', 'Webmin is a web-based interface for system administration for Unix. Using any modern web browser, you can setup user accounts, Apache, DNS, file sharing and much more. Webmin removes the need to manually edit Unix configuration files like /etc/passwd, and lets you manage a system from the console or remotely. See the standard modules page for a list of all the functions built into Webmin.', 'deb http://download.webmin.com/download/repository sarge contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D97A3AE911F63C51', 'all', 'http://www.webmin.com/index.html', 'http://www.webmin.com/deb.html', 3, 1),
(64, 'Webmin', 'Webmin is a web-based interface for system administration for Unix. Using any modern web browser, you can setup user accounts, Apache, DNS, file sharing and much more. Webmin removes the need to manually edit Unix configuration files like /etc/passwd, and lets you manage a system from the console or remotely. See the standard modules page for a list of all the functions built into Webmin.', 'deb http://download.webmin.com/download/repository sarge contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D97A3AE911F63C51', 'all', 'http://www.webmin.com/index.html', 'http://www.webmin.com/deb.html', 4, 1),
(65, 'openmediavault', 'openmediavault is the next generation network attached storage (NAS) solution based on Debian Linux. It contains services like SSH, (S)FTP, SMB/CIFS, DAAP media server, RSync, BitTorrent client and many more. Thanks to the modular design of the framework it can be enhanced via plugins.', 'deb http://packages.openmediavault.org/public erasmus main', 'deb-src http://packages.openmediavault.org/public erasmus main', 'apt-get update && apt-get install openmediavault-keyring && apt-get update', 'all', 'http://www.openmediavault.org', 'http://www.openmediavault.org/download.html', 1, 1),
(66, 'openmediavault', 'openmediavault is the next generation network attached storage (NAS) solution based on Debian Linux. It contains services like SSH, (S)FTP, SMB/CIFS, DAAP media server, RSync, BitTorrent client and many more. Thanks to the modular design of the framework it can be enhanced via plugins.', 'deb http://packages.openmediavault.org/public erasmus main', 'deb-src http://packages.openmediavault.org/public erasmus main', 'apt-get update && apt-get install openmediavault-keyring && apt-get update', 'all', 'http://www.openmediavault.org', 'http://www.openmediavault.org/download.html', 2, 1),
(67, 'openmediavault', 'openmediavault is the next generation network attached storage (NAS) solution based on Debian Linux. It contains services like SSH, (S)FTP, SMB/CIFS, DAAP media server, RSync, BitTorrent client and many more. Thanks to the modular design of the framework it can be enhanced via plugins.', 'deb http://packages.openmediavault.org/public erasmus main', 'deb-src http://packages.openmediavault.org/public erasmus main', 'apt-get update && apt-get install openmediavault-keyring && apt-get update', 'all', 'http://www.openmediavault.org', 'http://www.openmediavault.org/download.html', 3, 1),
(68, 'openmediavault', 'openmediavault is the next generation network attached storage (NAS) solution based on Debian Linux. It contains services like SSH, (S)FTP, SMB/CIFS, DAAP media server, RSync, BitTorrent client and many more. Thanks to the modular design of the framework it can be enhanced via plugins.', 'deb http://packages.openmediavault.org/public erasmus main', 'deb-src http://packages.openmediavault.org/public erasmus main', 'apt-get update && apt-get install openmediavault-keyring && apt-get update', 'all', 'http://www.openmediavault.org', 'http://www.openmediavault.org/download.html', 4, 1),
(69, 'DotDeb', 'Dotdeb is an extra repository providing up-to-date packages for your Debian servers', 'deb http://packages.dotdeb.org stable all\r\n', 'deb-src http://packages.dotdeb.org stable all', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E9C74FEEA2098A6E', 'all', 'https://www.dotdeb.org', 'https://www.dotdeb.org/instructions/', 2, 1),
(70, 'DotDeb', 'Dotdeb is an extra repository providing up-to-date packages for your Debian servers', 'deb http://packages.dotdeb.org stable all\r\n', 'deb-src http://packages.dotdeb.org stable all', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E9C74FEEA2098A6E', 'all', 'https://www.dotdeb.org', 'https://www.dotdeb.org/instructions/', 3, 1),
(71, 'DotDeb', 'Dotdeb is an extra repository providing up-to-date packages for your Debian servers', 'deb http://packages.dotdeb.org stable all\r\n', 'deb-src http://packages.dotdeb.org stable all', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E9C74FEEA2098A6E', 'all', 'https://www.dotdeb.org', 'https://www.dotdeb.org/instructions/', 4, 1),
(72, 'DotDeb', 'Dotdeb is an extra repository providing up-to-date packages for your Debian servers', 'deb http://packages.dotdeb.org oldstable all\r\n', 'deb-src http://packages.dotdeb.org oldstable all', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E9C74FEEA2098A6E', 'all', 'https://www.dotdeb.org', 'https://www.dotdeb.org/instructions/', 1, 1),
(73, 'MEGA Sync Client', 'Easy automated syncing between your computers and your MEGA cloud drive.', 'deb http://mega.nz/linux/MEGAsync/Debian_9.0/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 4B4E7A9523ACD201', 'all', 'https://mega.nz/', 'https://mega.nz/linux/MEGAsync/', 3, 1),
(74, 'MEGA Sync Client', 'Easy automated syncing between your computers and your MEGA cloud drive.', 'deb http://mega.nz/linux/MEGAsync/Debian_9.0/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 4B4E7A9523ACD201', 'all', 'https://mega.nz/', 'https://mega.nz/linux/MEGAsync/', 4, 1),
(75, 'MEGA Sync Client', 'Easy automated syncing between your computers and your MEGA cloud drive.', 'deb http://mega.nz/linux/MEGAsync/Debian_8.0/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 4B4E7A9523ACD201', 'all', 'https://mega.nz/', 'https://mega.nz/linux/MEGAsync/', 2, 1),
(84, 'FusionDirectory', 'FusionDirectory provides a solution to daily management of data stored in an LDAP directory. ', 'deb http://repos.fusiondirectory.org/debian-jessie jessie main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E184859262B4981F', 'all', 'https://www.fusiondirectory.org/', 'https://www.fusiondirectory.org/debian/', 2, 1),
(85, 'FusionDirectory', 'FusionDirectory provides a solution to daily management of data stored in an LDAP directory. ', 'deb http://repos.fusiondirectory.org/debian-jessie jessie main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E184859262B4981F', 'all', 'https://www.fusiondirectory.org/', 'https://www.fusiondirectory.org/debian/', 3, 1),
(86, 'FusionDirectory', 'FusionDirectory provides a solution to daily management of data stored in an LDAP directory. ', 'deb http://repos.fusiondirectory.org/debian-jessie jessie main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E184859262B4981F', 'all', 'https://www.fusiondirectory.org/', 'https://www.fusiondirectory.org/debian/', 4, 1),
(87, 'FusionDirectory', 'FusionDirectory provides a solution to daily management of data stored in an LDAP directory. ', 'deb http://repos.fusiondirectory.org/debian-wheezy wheezy main\r\ndeb http://repos.fusiondirectory.org/debian-extra wheezy main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E184859262B4981F', 'all', 'https://www.fusiondirectory.org/', 'https://www.fusiondirectory.org/debian/', 1, 1),
(88, 'video-dl', 'I\'ve created a suite of programs to download videos from lots of websites, including, but not limited to, the Italian Rai.tv website, the Mediaset website and the LA7 website.', 'deb http://repo.daniil.it lenny main', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 72B97FD1D9672C93', 'all', 'http://daniil.it/video-dl', 'http://daniil.it/video-dl/#bash-script-installation-instructions', 1, 1),
(89, 'video-dl', 'I\'ve created a suite of programs to download videos from lots of websites, including, but not limited to, the Italian Rai.tv website, the Mediaset website and the LA7 website.', 'deb http://repo.daniil.it lenny main', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 72B97FD1D9672C93', 'all', 'http://daniil.it/video-dl', 'http://daniil.it/video-dl/#bash-script-installation-instructions', 2, 1),
(90, 'video-dl', 'I\'ve created a suite of programs to download videos from lots of websites, including, but not limited to, the Italian Rai.tv website, the Mediaset website and the LA7 website.', 'deb http://repo.daniil.it lenny main', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 72B97FD1D9672C93', 'all', 'http://daniil.it/video-dl', 'http://daniil.it/video-dl/#bash-script-installation-instructions', 3, 1),
(91, 'video-dl', 'I\'ve created a suite of programs to download videos from lots of websites, including, but not limited to, the Italian Rai.tv website, the Mediaset website and the LA7 website.', 'deb http://repo.daniil.it lenny main', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 72B97FD1D9672C93', 'all', 'http://daniil.it/video-dl', 'http://daniil.it/video-dl/#bash-script-installation-instructions', 4, 1),
(92, 'Resilio Sync', 'Resilient, fast and scalable file synchronization', 'deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 05CD43032484414B', 'all', 'https://www.resilio.com/', 'https://help.getsync.com/hc/en-us/articles/206178924', 1, 1),
(93, 'Resilio Sync', 'Resilient, fast and scalable file synchronization', 'deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 05CD43032484414B', 'all', 'https://www.resilio.com/', 'https://help.getsync.com/hc/en-us/articles/206178924', 2, 1),
(94, 'Resilio Sync', 'Resilient, fast and scalable file synchronization', 'deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 05CD43032484414B', 'all', 'https://www.resilio.com/', 'https://help.getsync.com/hc/en-us/articles/206178924', 3, 1),
(95, 'Resilio Sync', 'Resilient, fast and scalable file synchronization', 'deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 05CD43032484414B', 'all', 'https://www.resilio.com/', 'https://help.getsync.com/hc/en-us/articles/206178924', 4, 1),
(96, 'Proxmox', 'Proxmox Virtual Environment is a complete server virtualization management solution, based on KVM and container virtualization.', 'deb http://download.proxmox.com/debian jessie pve-no-subscription', '', 'wget -O- \"http://download.proxmox.com/debian/key.asc\" | apt-key add -', 'amd64', 'https://proxmox.com', 'https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Jessie', 2, 1),
(97, 'Proxmox', 'Proxmox Virtual Environment is a complete server virtualization management solution, based on KVM and container virtualization.', 'deb http://download.proxmox.com/debian wheezy pve-no-subscription', '', 'wget -O- \"http://download.proxmox.com/debian/key.asc\" | apt-key add -', 'amd64', 'https://proxmox.com', 'https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Jessie', 1, 1),
(98, 'MariaDB', 'The MariaDB database server is published as free and open source software under the General Public License version 2. You can download and use it as much as you want free of charge. All use of the binaries from mariadb.org is at your own risk as stated in the GPLv2. While we do our best to make the world?s best database software, the MariaDB Foundation does not provide any guarantees and cannot be hold liable for any issues you may encounter.', 'deb http://mirror.rackspeed.de/mariadb.org/repo/10.1/debian wheezy main', 'deb-src http://mirror.rackspeed.de/mariadb.org/repo/10.1/debian wheezy main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys F1656F24C74CD1D8', 'i386,amd64', 'https://mariadb.org/', 'https://downloads.mariadb.org/mariadb/repositories/#mirror=rackspeed&distro=Debian&distro_release=wheezy--wheezy&version=10.1', 1, 1),
(99, 'MariaDB', 'The MariaDB database server is published as free and open source software under the General Public License version 2. You can download and use it as much as you want free of charge. All use of the binaries from mariadb.org is at your own risk as stated in the GPLv2. While we do our best to make the world?s best database software, the MariaDB Foundation does not provide any guarantees and cannot be hold liable for any issues you may encounter.', 'deb http://mirror.rackspeed.de/mariadb.org/repo/10.1/debian jessie main', 'deb-src http://mirror.rackspeed.de/mariadb.org/repo/10.1/debian jessie main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys F1656F24C74CD1D8', 'i386,amd64,ppc64el', 'https://mariadb.org/', 'https://downloads.mariadb.org/mariadb/repositories/#mirror=rackspeed&distro=Debian&distro_release=wheezy--wheezy&version=10.1', 2, 1),
(100, 'MariaDB', 'The MariaDB database server is published as free and open source software under the General Public License version 2. You can download and use it as much as you want free of charge. All use of the binaries from mariadb.org is at your own risk as stated in the GPLv2. While we do our best to make the world?s best database software, the MariaDB Foundation does not provide any guarantees and cannot be hold liable for any issues you may encounter.', 'deb http://mirror.rackspeed.de/mariadb.org/repo/10.1/debian stretch main', 'deb-src http://mirror.rackspeed.de/mariadb.org/repo/10.1/debian stretch main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys F1656F24C74CD1D8', 'amd64', 'https://mariadb.org/', 'https://downloads.mariadb.org/mariadb/repositories/#mirror=rackspeed&distro=Debian&distro_release=wheezy--wheezy&version=10.1', 3, 1),
(101, 'MariaDB', 'The MariaDB database server is published as free and open source software under the General Public License version 2. You can download and use it as much as you want free of charge. All use of the binaries from mariadb.org is at your own risk as stated in the GPLv2. While we do our best to make the world?s best database software, the MariaDB Foundation does not provide any guarantees and cannot be hold liable for any issues you may encounter.', 'deb http://mirror.rackspeed.de/mariadb.org/repo/10.1/debian sid main', 'deb-src http://mirror.rackspeed.de/mariadb.org/repo/10.1/debian sid main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys F1656F24C74CD1D8', 'amd64,i386', 'https://mariadb.org/', 'https://downloads.mariadb.org/mariadb/repositories/#mirror=rackspeed&distro=Debian&distro_release=wheezy--wheezy&version=10.1', 4, 1),
(102, 'Lazarus', 'Open Source GUI RAD IDE for free Pascal', 'deb http://www.hu.freepascal.org/lazarus/ lazarus-stable universe', '', 'gpg --keyserver hkp://pgp.mit.edu:11371 --recv-keys 6A11800F  && gpg --export --armor 0F7992B0 | apt-key add -', 'i386', 'http://www.lazarus.freepascal.org/', 'http://wiki.lazarus.freepascal.org/Lazarus_release_version_for_Ubuntu', 3, 1);
INSERT INTO `repos` (`repo_id`, `repo_name`, `repo_desc`, `repo_url`, `repo_url_src`, `repo_gpg`, `repo_arch`, `repo_homepage`, `repo_documentation`, `repo_release`, `repo_checked`) VALUES
(103, 'TOX', 'A New Kind of Instant Messaging\r\nWhether it\'s corporations or governments, digital surveillance today is widespread. Tox is easy-to-use software that connects you with friends and family without anyone else listening in. While other big-name services require you to pay for features, Tox is completely free and comes without advertising — forever.', 'deb https://pkg.tox.chat/debian stable jessie ', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys A2B076511A171ABE', 'i386,amd64', 'https://tox.chat/index.html', 'https://wiki.tox.chat/doku.php', 2, 1),
(104, 'TOX', 'A New Kind of Instant Messaging\r\nWhether it\'s corporations or governments, digital surveillance today is widespread. Tox is easy-to-use software that connects you with friends and family without anyone else listening in. While other big-name services require you to pay for features, Tox is completely free and comes without advertising — forever.', 'deb https://pkg.tox.chat/debian stable stretch ', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys A2B076511A171ABE', 'i386,amd64', 'https://tox.chat/index.html', 'https://wiki.tox.chat/doku.php', 3, 1),
(105, 'TOX', 'A New Kind of Instant Messaging\r\nWhether it\'s corporations or governments, digital surveillance today is widespread. Tox is easy-to-use software that connects you with friends and family without anyone else listening in. While other big-name services require you to pay for features, Tox is completely free and comes without advertising — forever.', 'deb https://pkg.tox.chat/debian stable sid ', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys A2B076511A171ABE', 'i386,amd64', 'https://tox.chat/index.html', 'https://wiki.tox.chat/doku.php', 4, 1),
(106, 'Jabber.at ejabberd Repo', 'Jabber.at Repo for ejabbered', 'deb https://apt.jabber.at wheezy ejabberd', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 1, 1),
(107, 'Jabber.at ejabberd Repo', 'Jabber.at Repo for ejabbered', 'deb https://apt.jabber.at jessie ejabberd', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 2, 1),
(108, 'Jabber.at ejabberd Repo', 'Jabber.at Repo for ejabbered', 'deb https://apt.jabber.at stretch ejabberd', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 3, 1),
(109, 'Jabber.at ejabberd Repo', 'Jabber.at Repo for ejabbered', 'deb https://apt.jabber.at unstable ejabberd', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 4, 1),
(110, 'Jabber.at gajim Repo', 'Jabber.at Repo for gajim', 'deb https://apt.jabber.at wheezy gajim', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 1, 1),
(111, 'Jabber.at gajim Repo', 'Jabber.at Repo for gajim', 'deb https://apt.jabber.at jessie gajim', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 2, 1),
(112, 'Jabber.at gajim Repo', 'Jabber.at Repo for gajim', 'deb https://apt.jabber.at stretch gajim', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 3, 1),
(113, 'Jabber.at gajim Repo', 'Jabber.at Repo for gajim', 'deb https://apt.jabber.at unstable gajim', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 4, 1),
(114, 'Jabber.at mcabber Repo', 'Jabber.at Repo for mcabber', 'deb https://apt.jabber.at wheezy mcabber', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 1, 1),
(115, 'Jabber.at mcabber Repo', 'Jabber.at Repo for mcabber', 'deb https://apt.jabber.at jessie mcabber', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 2, 1),
(116, 'Jabber.at mcabber Repo', 'Jabber.at Repo for mcabber', 'deb https://apt.jabber.at stretch mcabber', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 3, 1),
(117, 'Jabber.at mcabber Repo', 'Jabber.at Repo for mcabber', 'deb https://apt.jabber.at unstable mcabber', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 4, 1),
(118, 'Vivaldi Browser', 'Vivaldi is a freeware, cross-platform web browser developed by Vivaldi Technologies, a company founded by Opera Software co-founder and former CEO Jon Stephenson von Tetzchner and Tatsuki Tomita. The browser was officially launched on April 12, 2016', 'deb http://repo.vivaldi.com/stable/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 2CC26F777B8B44A1', 'i386,amd64', 'https://vivaldi.net/', 'https://forum.vivaldi.net/topic/1803/vivaldi-repo/15', 1, 1),
(119, 'Vivaldi Browser', 'Vivaldi is a freeware, cross-platform web browser developed by Vivaldi Technologies, a company founded by Opera Software co-founder and former CEO Jon Stephenson von Tetzchner and Tatsuki Tomita. The browser was officially launched on April 12, 2016', 'deb http://repo.vivaldi.com/stable/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 2CC26F777B8B44A1', 'i386,amd64', 'https://vivaldi.net/', 'https://forum.vivaldi.net/topic/1803/vivaldi-repo/15', 2, 1),
(120, 'Vivaldi Browser', 'Vivaldi is a freeware, cross-platform web browser developed by Vivaldi Technologies, a company founded by Opera Software co-founder and former CEO Jon Stephenson von Tetzchner and Tatsuki Tomita. The browser was officially launched on April 12, 2016', 'deb http://repo.vivaldi.com/stable/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 2CC26F777B8B44A1', 'i386,amd64', 'https://vivaldi.net/', 'https://forum.vivaldi.net/topic/1803/vivaldi-repo/15', 3, 1),
(121, 'Vivaldi Browser', 'Vivaldi is a freeware, cross-platform web browser developed by Vivaldi Technologies, a company founded by Opera Software co-founder and former CEO Jon Stephenson von Tetzchner and Tatsuki Tomita. The browser was officially launched on April 12, 2016', 'deb http://repo.vivaldi.com/stable/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 2CC26F777B8B44A1', 'i386,amd64', 'https://vivaldi.net/', 'https://forum.vivaldi.net/topic/1803/vivaldi-repo/15', 4, 1),
(126, 'Paper GTK Theme', 'Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons. Each icon has been meticulously designed for pixel-perfect viewing.', 'deb http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'deb-src http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 3766223989993A70', 'all', 'https://snwh.org/paper', 'https://snwh.org/paper/support', 1, 1),
(127, 'Paper GTK Theme', 'Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons. Each icon has been meticulously designed for pixel-perfect viewing.', 'deb http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'deb-src http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 3766223989993A70', 'all', 'https://snwh.org/paper', 'https://snwh.org/paper/support', 2, 1),
(128, 'Paper GTK Theme', 'Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons. Each icon has been meticulously designed for pixel-perfect viewing.', 'deb http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'deb-src http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 3766223989993A70', 'all', 'https://snwh.org/paper', 'https://snwh.org/paper/support', 3, 1),
(129, 'Paper GTK Theme', 'Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons. Each icon has been meticulously designed for pixel-perfect viewing.', 'deb http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'deb-src http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 3766223989993A70', 'all', 'https://snwh.org/paper', 'https://snwh.org/paper/support', 4, 1),
(130, 'Papirus GTK Theme', 'Papirus is a free and open source SVG icon theme for Linux, based on Paper Icon Set with a lot of new icons and a few extras, like Hardcode-Tray support, KDE colorscheme support, Folder Color support, and others.', 'deb http://ppa.launchpad.net/papirus/papirus/ubuntu yakkety main ', 'deb-src http://ppa.launchpad.net/papirus/papirus/ubuntu yakkety main ', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E58A9D36647CAE7F', 'all', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 1, 1),
(131, 'Papirus GTK Theme', 'Papirus is a free and open source SVG icon theme for Linux, based on Paper Icon Set with a lot of new icons and a few extras, like Hardcode-Tray support, KDE colorscheme support, Folder Color support, and others.', 'deb http://ppa.launchpad.net/papirus/papirus/ubuntu yakkety main ', 'deb-src http://ppa.launchpad.net/papirus/papirus/ubuntu yakkety main ', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E58A9D36647CAE7F', 'all', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 2, 1),
(132, 'Papirus GTK Theme', 'Papirus is a free and open source SVG icon theme for Linux, based on Paper Icon Set with a lot of new icons and a few extras, like Hardcode-Tray support, KDE colorscheme support, Folder Color support, and others.', 'deb http://ppa.launchpad.net/papirus/papirus/ubuntu yakkety main ', 'deb-src http://ppa.launchpad.net/papirus/papirus/ubuntu yakkety main ', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E58A9D36647CAE7F', 'all', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 3, 1),
(133, 'Papirus GTK Theme', 'Papirus is a free and open source SVG icon theme for Linux, based on Paper Icon Set with a lot of new icons and a few extras, like Hardcode-Tray support, KDE colorscheme support, Folder Color support, and others.', 'deb http://ppa.launchpad.net/papirus/papirus/ubuntu yakkety main ', 'deb-src http://ppa.launchpad.net/papirus/papirus/ubuntu yakkety main ', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E58A9D36647CAE7F', 'all', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 4, 1),
(134, 'Squash TM', 'Squash TM is an open source tool for test repository management: requirements management, test cases, campaign and more... Squash TM is full web and natively inter- and multi- projects. ', 'deb http://repo.squashtest.org/debian wheezy main', '', 'wget -q -O - http://repo.squashtest.org/repo.squashtest.org.gpg.key | apt-key add -', 'amd64,i386', 'http://www.squashtest.org', 'https://sites.google.com/a/henix.fr/wiki-squash-tm/', 1, 1),
(135, 'Squash TM', 'Squash TM is an open source tool for test repository management: requirements management, test cases, campaign and more... Squash TM is full web and natively inter- and multi- projects. ', 'deb http://repo.squashtest.org/debian jessie main', '', 'wget -q -O - http://repo.squashtest.org/repo.squashtest.org.gpg.key | apt-key add -', 'amd64,i386', 'http://www.squashtest.org', 'https://sites.google.com/a/henix.fr/wiki-squash-tm/', 2, 1),
(136, 'Skype', 'Skype is an instant messaging app that provides online text message and video chat services. Users may transmit both text and video messages and may exchange digital documents such as images, text, and video. Skype allows video conference calls.', 'deb https://repo.skype.com/deb stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1F3045A5DF7587C3', 'amd64', 'https://skype.com', 'https://support.skype.com/en/skype/linux/', 2, 1),
(137, 'Skype', 'Skype is an instant messaging app that provides online text message and video chat services. Users may transmit both text and video messages and may exchange digital documents such as images, text, and video. Skype allows video conference calls.', 'deb https://repo.skype.com/deb stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1F3045A5DF7587C3', 'amd64', 'https://skype.com', 'https://support.skype.com/en/skype/linux/', 3, 1),
(138, 'Skype', 'Skype is an instant messaging app that provides online text message and video chat services. Users may transmit both text and video messages and may exchange digital documents such as images, text, and video. Skype allows video conference calls.', 'deb https://repo.skype.com/deb stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1F3045A5DF7587C3', 'amd64', 'https://skype.com', 'https://support.skype.com/en/skype/linux/', 4, 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `deb_release`
--
ALTER TABLE `deb_release`
  ADD PRIMARY KEY (`release_id`);

--
-- Indexes for table `lastchanges`
--
ALTER TABLE `lastchanges`
  ADD PRIMARY KEY (`lc_id`);

--
-- Indexes for table `repos`
--
ALTER TABLE `repos`
  ADD PRIMARY KEY (`repo_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `deb_release`
--
ALTER TABLE `deb_release`
  MODIFY `release_id` int(15) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
--
-- AUTO_INCREMENT for table `lastchanges`
--
ALTER TABLE `lastchanges`
  MODIFY `lc_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=89;
--
-- AUTO_INCREMENT for table `repos`
--
ALTER TABLE `repos`
  MODIFY `repo_id` int(15) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=139;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
