-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Erstellungszeit: 10. Jan 2018 um 06:51
-- Server-Version: 10.1.26-MariaDB-0+deb9u1
-- PHP-Version: 7.0.19-1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: `c1_debgen`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `repos`
--

CREATE TABLE `repos` (
  `repo_id` int(15) NOT NULL,
  `repo_name` varchar(255) NOT NULL,
  `repo_desc` text NOT NULL,
  `repo_url` text NOT NULL,
  `repo_url_src` text NOT NULL,
  `repo_gpg` text NOT NULL,
  `repo_arch` text NOT NULL,
  `repo_homepage` text NOT NULL,
  `repo_documentation` text NOT NULL,
  `repo_release` int(15) NOT NULL,
  `repo_checked` int(15) NOT NULL,
  `issue` tinyint(1) NOT NULL,
  `issue_key` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Daten für Tabelle `repos`
--

INSERT INTO `repos` (`repo_id`, `repo_name`, `repo_desc`, `repo_url`, `repo_url_src`, `repo_gpg`, `repo_arch`, `repo_homepage`, `repo_documentation`, `repo_release`, `repo_checked`, `issue`, `issue_key`) VALUES
(3, 'Debian Multimedia', 'The Debian Multimedia repository is a repository that contains a lot of up-to-date multimedia related packages like mplayer, mencoder, transcode, dvd::rip, ffmpeg, avidemux, acidrip, kplayer, lame, kdenlive, xvid, mjpegtools, codecs, w32codecs etc.', 'deb http://www.deb-multimedia.org oldstable main non-free', '', 'wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb && dpkg -i deb-multimedia-keyring_2016.8.1_all.deb', 'amd64,i386', 'http://deb-multimedia.org/', 'http://deb-multimedia.org/', 1, 1, 0, 0),
(4, 'Debian Multimedia', 'The Debian Multimedia repository is a repository that contains a lot of up-to-date multimedia related packages like mplayer, mencoder, transcode, dvd::rip, ffmpeg, avidemux, acidrip, kplayer, lame, kdenlive, xvid, mjpegtools, codecs, w32codecs etc.', 'deb https://www.deb-multimedia.org stable main non-free', '', 'wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb && dpkg -i deb-multimedia-keyring_2016.8.1_all.deb', 'amd64,i386', 'http://deb-multimedia.org/', 'http://deb-multimedia.org/', 2, 1, 1, 1),
(5, 'Debian Multimedia', 'The Debian Multimedia repository is a repository that contains a lot of up-to-date multimedia related packages like mplayer, mencoder, transcode, dvd::rip, ffmpeg, avidemux, acidrip, kplayer, lame, kdenlive, xvid, mjpegtools, codecs, w32codecs etc.', 'deb http://www.deb-multimedia.org testing main non-free', '', 'wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb && dpkg -i deb-multimedia-keyring_2016.8.1_all.deb', 'amd64,i386', 'http://deb-multimedia.org/', 'http://deb-multimedia.org/', 3, 1, 0, 0),
(6, 'Debian Multimedia', 'The Debian Multimedia repository is a repository that contains a lot of up-to-date multimedia related packages like mplayer, mencoder, transcode, dvd::rip, ffmpeg, avidemux, acidrip, kplayer, lame, kdenlive, xvid, mjpegtools, codecs, w32codecs etc.', 'deb http://www.deb-multimedia.org unstable main non-free', '', 'wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb && dpkg -i deb-multimedia-keyring_2016.8.1_all.deb', 'amd64,i386', 'http://deb-multimedia.org/', 'http://deb-multimedia.org/', 4, 1, 0, 0),
(7, 'Lazarus', 'Open Source GUI RAD IDE for free Pascal', 'deb http://www.hu.freepascal.org/lazarus/ lazarus-oldstable universe', '', 'gpg --keyserver hkp://pgp.mit.edu:11371 --recv-keys 6A11800F  && gpg --export --armor 0F7992B0  | apt-key add -', 'all', 'http://www.lazarus.freepascal.org/', 'http://wiki.lazarus.freepascal.org/Lazarus_release_version_for_Ubuntu', 1, 1, 0, 0),
(8, 'Lazarus', 'Open Source GUI RAD IDE for free Pascal', 'deb http://www.hu.freepascal.org/lazarus/ lazarus-stable universe', '', 'gpg --keyserver hkp://pgp.mit.edu:11371 --recv-keys 6A11800F  && gpg --export --armor 0F7992B0 | apt-key add -', 'all', 'http://www.lazarus.freepascal.org/', 'http://wiki.lazarus.freepascal.org/Lazarus_release_version_for_Ubuntu', 2, 1, 0, 0),
(9, 'Lazarus', 'Open Source GUI RAD IDE for free Pascal', 'deb http://www.hu.freepascal.org/lazarus/ lazarus-stable universe', '', 'gpg --keyserver hkp://pgp.mit.edu:11371 --recv-keys 6A11800F  && gpg --export --armor 0F7992B0 | apt-key add -', 'i386', 'http://www.lazarus.freepascal.org/', 'http://wiki.lazarus.freepascal.org/Lazarus_release_version_for_Ubuntu', 4, 1, 0, 0),
(10, 'Google Chrome Browser', 'Google Chrome runs websites and applications with lightning speed.', 'deb http://dl.google.com/linux/chrome/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 1, 1, 0, 0),
(11, 'Google Chrome Browser', 'Google Chrome runs websites and applications with lightning speed.', 'deb http://dl.google.com/linux/chrome/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 2, 1, 1, 1),
(12, 'Google Chrome Browser', 'Google Chrome runs websites and applications with lightning speed.', 'deb http://dl.google.com/linux/chrome/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 3, 1, 0, 0),
(13, 'Google Chrome Browser', 'Google Chrome runs websites and applications with lightning speed.', 'deb http://dl.google.com/linux/chrome/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 4, 1, 0, 0),
(14, 'Google Earth', 'Get the world?s geographic information at your fingertips. Take a virtual journey to any location in the world. Explore 3D buildings, imagery, and terrain. Find cities, places and local businesses.', 'deb http://dl.google.com/linux/earth/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 1, 1, 0, 0),
(15, 'Google Earth', 'Get the world?s geographic information at your fingertips. Take a virtual journey to any location in the world. Explore 3D buildings, imagery, and terrain. Find cities, places and local businesses.', 'deb http://dl.google.com/linux/earth/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 2, 1, 1, 1),
(16, 'Google Earth', 'Get the world?s geographic information at your fingertips. Take a virtual journey to any location in the world. Explore 3D buildings, imagery, and terrain. Find cities, places and local businesses.', 'deb http://dl.google.com/linux/earth/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 3, 1, 0, 0),
(17, 'Google Earth', 'Get the world?s geographic information at your fingertips. Take a virtual journey to any location in the world. Explore 3D buildings, imagery, and terrain. Find cities, places and local businesses.', 'deb http://dl.google.com/linux/earth/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1397BC53640DB551', 'amd64', 'http://www.google.com/linuxrepositories/', 'http://www.google.com/linuxrepositories/', 4, 1, 0, 0),
(20, 'Mozilla Firefox Aurora', 'Firefox Aurora from Mozilla', 'deb http://mozilla.debian.net/ experimental firefox-aurora', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 85A3D26506C4AE2A', 'all', 'https://mozilla.org', 'https://support.mozilla.org/', 3, 1, 1, 0),
(21, 'Mozilla Firefox Aurora', 'Firefox Aurora from Mozilla', 'deb http://mozilla.debian.net/ experimental firefox-aurora', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 85A3D26506C4AE2A', 'all', 'https://mozilla.org', 'https://support.mozilla.org/', 4, 1, 0, 0),
(22, 'Virtualbox', 'Oracle VM VirtualBox (formerly Sun VirtualBox, Sun xVM VirtualBox and Innotek VirtualBox) is a free and open-source hypervisor for x86 computers currently being developed by Oracle Corporation. Developed initially by Innotek GmbH, it was acquired by Sun Microsystems in 2008 which was in turn acquired by Oracle in 2010.', 'deb http://download.virtualbox.org/virtualbox/debian jessie contrib non-free', '', 'wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -\r\nwget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -', 'i386,amd64', 'https://www.virtualbox.org', 'https://www.virtualbox.org/wiki/', 1, 1, 0, 0),
(23, 'Virtualbox', 'Oracle VM VirtualBox (formerly Sun VirtualBox, Sun xVM VirtualBox and Innotek VirtualBox) is a free and open-source hypervisor for x86 computers currently being developed by Oracle Corporation. Developed initially by Innotek GmbH, it was acquired by Sun Microsystems in 2008 which was in turn acquired by Oracle in 2010.', 'deb http://download.virtualbox.org/virtualbox/debian stretch contrib', '', 'wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -\r\nwget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -', 'i386,amd64', 'https://www.virtualbox.org', 'https://www.virtualbox.org/wiki/', 2, 1, 1, 1),
(24, 'Spotify', 'Spotify is a music, podcast, and video streaming service, officially launched on 7 October 2008. It is developed by startup Spotify AB in Stockholm, Sweden. It provides digital rights management-protected content from record labels and media companies. Spotify is a freemium service, meaning that basic features are free with advertisements, while additional features, including improved streaming quality and offline music downloads, are offered via paid subscriptions.', 'deb http://repository.spotify.com stable non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys EFDC8610341D9410', 'all', 'https://www.spotify.com/en/download/linux/', 'https://www.spotify.com/de/download/linux/', 1, 1, 0, 0),
(25, 'Spotify', 'Spotify is a music, podcast, and video streaming service, officially launched on 7 October 2008. It is developed by startup Spotify AB in Stockholm, Sweden. It provides digital rights management-protected content from record labels and media companies. Spotify is a freemium service, meaning that basic features are free with advertisements, while additional features, including improved streaming quality and offline music downloads, are offered via paid subscriptions.', 'deb http://repository.spotify.com stable non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys EFDC8610341D9410', 'all', 'https://www.spotify.com/en/download/linux/', 'https://www.spotify.com/de/download/linux/', 2, 1, 1, 1),
(26, 'Spotify', 'Spotify is a music, podcast, and video streaming service, officially launched on 7 October 2008. It is developed by startup Spotify AB in Stockholm, Sweden. It provides digital rights management-protected content from record labels and media companies. Spotify is a freemium service, meaning that basic features are free with advertisements, while additional features, including improved streaming quality and offline music downloads, are offered via paid subscriptions.', 'deb http://repository.spotify.com stable non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys EFDC8610341D9410', 'all', 'https://www.spotify.com/en/download/linux/', 'https://www.spotify.com/de/download/linux/', 3, 1, 0, 0),
(27, 'Spotify', 'Spotify is a music, podcast, and video streaming service, officially launched on 7 October 2008. It is developed by startup Spotify AB in Stockholm, Sweden. It provides digital rights management-protected content from record labels and media companies. Spotify is a freemium service, meaning that basic features are free with advertisements, while additional features, including improved streaming quality and offline music downloads, are offered via paid subscriptions.', 'deb http://repository.spotify.com stable non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys EFDC8610341D9410', 'all', 'https://www.spotify.com/en/download/linux/', 'https://www.spotify.com/de/download/linux/', 4, 1, 0, 0),
(28, 'Steam', 'Steam is a digital distribution platform developed by Valve Corporation, which offers digital rights management (DRM), multiplayer gaming, and social networking services. Steam provides the user with installation and automatic updating of games on multiple computers, and community features such as friends lists and groups, cloud saving, and in-game voice and chat functionality. The software provides a freely available application programming interface (API) called Steamworks, which developers can use to integrate many of Steam\'s functions into their products, including networking, matchmaking, in-game achievements, micro-transactions, and support for user-created content through Steam Workshop. Though initially developed for use on Microsoft Windows operating systems, versions for OS X and Linux were later released. Mobile apps with connected functionality with the main software were later released for iOS, Android, and Windows Phone devices in the 2010s.', 'deb http://repo.steampowered.com/steam/ precise steam', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F24AEA9FB05498B7', 'i386,amd64', 'http://store.steampowered.com/', 'http://store.steampowered.com/about/', 1, 1, 0, 0),
(29, 'Steam', 'Steam is a digital distribution platform developed by Valve Corporation, which offers digital rights management (DRM), multiplayer gaming, and social networking services. Steam provides the user with installation and automatic updating of games on multiple computers, and community features such as friends lists and groups, cloud saving, and in-game voice and chat functionality. The software provides a freely available application programming interface (API) called Steamworks, which developers can use to integrate many of Steam\'s functions into their products, including networking, matchmaking, in-game achievements, micro-transactions, and support for user-created content through Steam Workshop. Though initially developed for use on Microsoft Windows operating systems, versions for OS X and Linux were later released. Mobile apps with connected functionality with the main software were later released for iOS, Android, and Windows Phone devices in the 2010s.', 'deb http://repo.steampowered.com/steam/ precise steam', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F24AEA9FB05498B7', 'i386,amd64', 'http://store.steampowered.com/', 'http://store.steampowered.com/about/', 2, 1, 1, 1),
(30, 'Steam', 'Steam is a digital distribution platform developed by Valve Corporation, which offers digital rights management (DRM), multiplayer gaming, and social networking services. Steam provides the user with installation and automatic updating of games on multiple computers, and community features such as friends lists and groups, cloud saving, and in-game voice and chat functionality. The software provides a freely available application programming interface (API) called Steamworks, which developers can use to integrate many of Steam\'s functions into their products, including networking, matchmaking, in-game achievements, micro-transactions, and support for user-created content through Steam Workshop. Though initially developed for use on Microsoft Windows operating systems, versions for OS X and Linux were later released. Mobile apps with connected functionality with the main software were later released for iOS, Android, and Windows Phone devices in the 2010s.', 'deb http://repo.steampowered.com/steam/ precise steam', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F24AEA9FB05498B7', 'i386,amd64', 'http://store.steampowered.com/', 'http://store.steampowered.com/about/', 3, 1, 0, 0),
(31, 'Steam', 'Steam is a digital distribution platform developed by Valve Corporation, which offers digital rights management (DRM), multiplayer gaming, and social networking services. Steam provides the user with installation and automatic updating of games on multiple computers, and community features such as friends lists and groups, cloud saving, and in-game voice and chat functionality. The software provides a freely available application programming interface (API) called Steamworks, which developers can use to integrate many of Steam\'s functions into their products, including networking, matchmaking, in-game achievements, micro-transactions, and support for user-created content through Steam Workshop. Though initially developed for use on Microsoft Windows operating systems, versions for OS X and Linux were later released. Mobile apps with connected functionality with the main software were later released for iOS, Android, and Windows Phone devices in the 2010s.', 'deb http://repo.steampowered.com/steam/ precise steam', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F24AEA9FB05498B7', 'i386,amd64', 'http://store.steampowered.com/', 'http://store.steampowered.com/about/', 4, 1, 0, 0),
(33, 'Wine', 'Wine (recursive acronym for Wine Is Not an Emulator) is a free and open source compatibility layer software application that aims to allow applications designed for Microsoft Windows to run on Unix-like operating systems. Wine also provides a software library, known as Winelib, against which developers can compile Windows applications to help port them to Unix-like systems.[7]', 'deb https://dl.winehq.org/wine-builds/debian/ jessie main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 818A435C5FCBF54A', 'i386', 'https://winehq.org/', 'https://wiki.winehq.org/Debian', 1, 1, 1, 1),
(34, 'Wine', 'Wine (recursive acronym for Wine Is Not an Emulator) is a free and open source compatibility layer software application that aims to allow applications designed for Microsoft Windows to run on Unix-like operating systems. Wine also provides a software library, known as Winelib, against which developers can compile Windows applications to help port them to Unix-like systems.[7]', 'deb https://dl.winehq.org/wine-builds/debian/ stretch main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 818A435C5FCBF54A', 'i386', 'https://winehq.org/', 'https://wiki.winehq.org/Debian', 2, 1, 1, 1),
(35, 'Wine', 'Wine (recursive acronym for Wine Is Not an Emulator) is a free and open source compatibility layer software application that aims to allow applications designed for Microsoft Windows to run on Unix-like operating systems. Wine also provides a software library, known as Winelib, against which developers can compile Windows applications to help port them to Unix-like systems.[7]', 'deb https://dl.winehq.org/wine-builds/debian/ sid main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 818A435C5FCBF54A', 'i386', 'https://winehq.org/', 'https://wiki.winehq.org/Debian', 4, 1, 0, 0),
(36, 'Opera', 'Opera is a web browser for Windows, macOS, and Linux operating systems. It is developed by Opera Software. As of November 2016, the browser is owned by a Chinese group of investors under the name Golden Brick Capital Private Equity Fund I Limited Partnership.', 'deb https://deb.opera.com/opera-stable/ stable non-free', '', 'wget -O - http://deb.opera.com/archive.key | apt-key add -', 'amd64,i386', 'http://opera.com', 'http://deb.opera.com/manual.html', 1, 1, 0, 0),
(37, 'Opera', 'Opera is a web browser for Windows, macOS, and Linux operating systems. It is developed by Opera Software. As of November 2016, the browser is owned by a Chinese group of investors under the name Golden Brick Capital Private Equity Fund I Limited Partnership.', 'deb https://deb.opera.com/opera-stable/ stable non-free', '', 'wget -O - http://deb.opera.com/archive.key | apt-key add -', 'amd64,i386', 'http://opera.com', 'http://deb.opera.com/manual.html', 2, 1, 1, 0),
(38, 'Opera', 'Opera is a web browser for Windows, macOS, and Linux operating systems. It is developed by Opera Software. As of November 2016, the browser is owned by a Chinese group of investors under the name Golden Brick Capital Private Equity Fund I Limited Partnership.', 'deb https://deb.opera.com/opera-stable/ stable non-free', '', 'wget -O - http://deb.opera.com/archive.key | apt-key add -', 'amd64,i386', 'http://opera.com', 'http://deb.opera.com/manual.html', 3, 1, 0, 0),
(39, 'Opera', 'Opera is a web browser for Windows, macOS, and Linux operating systems. It is developed by Opera Software. As of November 2016, the browser is owned by a Chinese group of investors under the name Golden Brick Capital Private Equity Fund I Limited Partnership.', 'deb https://deb.opera.com/opera-stable/ stable non-free', '', 'wget -O - http://deb.opera.com/archive.key | apt-key add -', 'amd64,i386', 'http://opera.com', 'http://deb.opera.com/manual.html', 4, 1, 0, 0),
(40, 'Esmska', 'Program for sending SMS over the Internet. Anyone can write support for additional gateways.', 'deb http://download.opensuse.org/repositories/Java:/esmska/common-deb/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 29255F95E60A19CD', 'all', 'https://github.com/kparal/esmska', 'https://github.com/kparal/esmska/wiki', 1, 1, 0, 0),
(41, 'Esmska', 'Program for sending SMS over the Internet. Anyone can write support for additional gateways.', 'deb http://download.opensuse.org/repositories/Java:/esmska/common-deb/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 29255F95E60A19CD', 'all', 'https://github.com/kparal/esmska', 'https://github.com/kparal/esmska/wiki', 2, 1, 1, 1),
(42, 'Esmska', 'Program for sending SMS over the Internet. Anyone can write support for additional gateways.', 'deb http://download.opensuse.org/repositories/Java:/esmska/common-deb/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 29255F95E60A19CD', 'all', 'https://github.com/kparal/esmska', 'https://github.com/kparal/esmska/wiki', 3, 1, 1, 0),
(43, 'Esmska', 'Program for sending SMS over the Internet. Anyone can write support for additional gateways.', 'deb http://download.opensuse.org/repositories/Java:/esmska/common-deb/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 29255F95E60A19CD', 'all', 'https://github.com/kparal/esmska', 'https://github.com/kparal/esmska/wiki', 4, 1, 0, 0),
(44, 'muCommander', 'muCommander is a lightweight, cross-platform file manager with a dual-pane interface. It runs on any operating system with Java support (Mac OS X, Windows, Linux, *BSD, Solaris...).', 'deb http://apt.mucommander.com stable main non-free contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 030BBF253A687AFF', 'all', 'http://www.mucommander.com/', 'http://apt.mucommander.com', 1, 1, 0, 0),
(45, 'muCommander', 'muCommander is a lightweight, cross-platform file manager with a dual-pane interface. It runs on any operating system with Java support (Mac OS X, Windows, Linux, *BSD, Solaris...).', 'deb http://apt.mucommander.com stable main non-free contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 030BBF253A687AFF', 'all', 'http://www.mucommander.com/', 'http://apt.mucommander.com', 2, 1, 1, 1),
(46, 'muCommander', 'muCommander is a lightweight, cross-platform file manager with a dual-pane interface. It runs on any operating system with Java support (Mac OS X, Windows, Linux, *BSD, Solaris...).', 'deb http://apt.mucommander.com stable main non-free contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 030BBF253A687AFF', 'all', 'http://www.mucommander.com/', 'http://apt.mucommander.com', 3, 1, 1, 0),
(47, 'muCommander', 'muCommander is a lightweight, cross-platform file manager with a dual-pane interface. It runs on any operating system with Java support (Mac OS X, Windows, Linux, *BSD, Solaris...).', 'deb http://apt.mucommander.com stable main non-free contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 030BBF253A687AFF', 'all', 'http://www.mucommander.com/', 'http://apt.mucommander.com', 4, 1, 0, 0),
(49, 'PlayOnLinux', 'PlayOnLinux is a piece of software which allows you to easily install and use numerous games and apps designed to run with Microsoft? Windows?.\r\nFew games are compatible with GNU/Linux at the moment and it certainly is a factor preventing the migration to this system. PlayOnLinux brings a cost-free, accessible and efficient solution to this problem.', 'deb http://deb.playonlinux.com/ jessie main', '', 'wget -q \"http://deb.playonlinux.com/public.gpg\" -O- | apt-key add -', 'all', 'https://www.playonlinux.com/', 'https://www.playonlinux.com/en/download.html', 1, 1, 0, 0),
(50, 'ownCloud Client', 'OwnCloud (stylized ownCloud) is a suite of client-server software for creating file hosting services and using them. OwnCloud is functionally very similar to the widely used Dropbox, with the primary functional difference being that OwnCloud is free and open-source, and thereby allowing anyone to install and operate it without charge on a private server. It also supports extensions that allow it to work like Google Drive, with online document editing, calendar and contact synchronization, and more. Its openness eschews enforced quotas on storage space or the number of connected clients, instead having hard limits (like on storage space or number of users) defined only by the physical capabilities of the server.', 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0/ /', '', 'wget http://download.opensuse.org/repositories/isv:ownCloud:desktop/Debian_8.0/Release.key && apt-key add - < Release.key && rm Release.key', 'all', 'https://owncloud.org/', 'https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client', 2, 1, 0, 0),
(51, 'ownCloud Client', 'OwnCloud (stylized ownCloud) is a suite of client-server software for creating file hosting services and using them. OwnCloud is functionally very similar to the widely used Dropbox, with the primary functional difference being that OwnCloud is free and open-source, and thereby allowing anyone to install and operate it without charge on a private server. It also supports extensions that allow it to work like Google Drive, with online document editing, calendar and contact synchronization, and more. Its openness eschews enforced quotas on storage space or the number of connected clients, instead having hard limits (like on storage space or number of users) defined only by the physical capabilities of the server.', 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/ /', '', 'wget http://download.opensuse.org/repositories/isv:ownCloud:desktop/Debian_8.0/Release.key && apt-key add - < Release.key && rm Release.key', 'all', 'https://owncloud.org/', 'https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client', 1, 1, 0, 0),
(52, 'Dropbox', 'Dropbox is a file hosting service operated by American company Dropbox, Inc., headquartered in San Francisco, California, that offers cloud storage, file synchronization, personal cloud, and client software. Dropbox was founded in 2007, by MIT students Drew Houston and Arash Ferdowsi, as a startup company, with initial funding from seed accelerator Y Combinator.', 'deb http://linux.dropbox.com/debian wheezy main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys FC918B335044912E', 'all', 'https://www.dropbox.com/', 'https://www.dropbox.com/en/help/246', 1, 1, 0, 0),
(53, 'Dropbox', 'Dropbox is a file hosting service operated by American company Dropbox, Inc., headquartered in San Francisco, California, that offers cloud storage, file synchronization, personal cloud, and client software. Dropbox was founded in 2007, by MIT students Drew Houston and Arash Ferdowsi, as a startup company, with initial funding from seed accelerator Y Combinator.', 'deb http://linux.dropbox.com/debian jessie main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys FC918B335044912E', 'all', 'https://www.dropbox.com/', 'https://www.dropbox.com/en/help/246', 2, 1, 1, 1),
(54, 'Dropbox', 'Dropbox is a file hosting service operated by American company Dropbox, Inc., headquartered in San Francisco, California, that offers cloud storage, file synchronization, personal cloud, and client software. Dropbox was founded in 2007, by MIT students Drew Houston and Arash Ferdowsi, as a startup company, with initial funding from seed accelerator Y Combinator.', 'deb http://linux.dropbox.com/debian sid main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys FC918B335044912E', 'all', 'https://www.dropbox.com/', 'https://www.dropbox.com/en/help/246', 4, 1, 0, 0),
(55, 'TOR', 'Tor is free software for enabling anonymous communication. The name is derived from an acronym for the original software project name \"The Onion Router\".', 'deb http://deb.torproject.org/torproject.org oldstable main', 'deb-src http://deb.torproject.org/torproject.org oldstable main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 74A941BA219EC810', 'i386,amd64,armel,armhf', 'https://www.torproject.org', 'https://www.torproject.org/docs/debian', 1, 1, 0, 0),
(56, 'TOR', 'Tor is free software for enabling anonymous communication. The name is derived from an acronym for the original software project name \"The Onion Router\".', 'deb http://deb.torproject.org/torproject.org stable main', 'deb-src http://deb.torproject.org/torproject.org stable main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 74A941BA219EC810', 'i386,amd64,armel,armhf', 'https://www.torproject.org', 'https://www.torproject.org/docs/debian', 2, 1, 1, 1),
(57, 'TOR', 'Tor is free software for enabling anonymous communication. The name is derived from an acronym for the original software project name \"The Onion Router\".', 'deb http://deb.torproject.org/torproject.org testing main', 'deb-src http://deb.torproject.org/torproject.org testing main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 74A941BA219EC810', 'i386,amd64,armel,armhf', 'https://www.torproject.org', 'https://www.torproject.org/docs/debian', 3, 1, 1, 0),
(58, 'TOR', 'Tor is free software for enabling anonymous communication. The name is derived from an acronym for the original software project name \"The Onion Router\".', 'deb http://deb.torproject.org/torproject.org unstable main', 'deb-src http://deb.torproject.org/torproject.org unstable main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 74A941BA219EC810', 'i386,amd64,armel,armhf', 'https://www.torproject.org', 'https://www.torproject.org/docs/debian', 4, 1, 0, 0),
(59, 'Syncthing', 'Syncthing is a free, open-source peer-to-peer file synchronization application available for Windows, Mac, Linux, Android, Solaris, Darwin and BSD. It can sync files between devices on a local network, or between remote devices over the Internet. Data security and data safety is built into the design of the software.', 'deb https://apt.syncthing.net/ syncthing stable', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D26E6ED000654A3E', 'all', 'https://syncthing.net/', 'https://apt.syncthing.net/', 1, 1, 0, 0),
(60, 'Syncthing', 'Syncthing is a free, open-source peer-to-peer file synchronization application available for Windows, Mac, Linux, Android, Solaris, Darwin and BSD. It can sync files between devices on a local network, or between remote devices over the Internet. Data security and data safety is built into the design of the software.', 'deb https://apt.syncthing.net/ syncthing stable', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D26E6ED000654A3E', 'all', 'https://syncthing.net/', 'https://apt.syncthing.net/', 4, 1, 0, 0),
(61, 'Webmin', 'Webmin is a web-based interface for system administration for Unix. Using any modern web browser, you can setup user accounts, Apache, DNS, file sharing and much more. Webmin removes the need to manually edit Unix configuration files like /etc/passwd, and lets you manage a system from the console or remotely. See the standard modules page for a list of all the functions built into Webmin.', 'deb http://download.webmin.com/download/repository sarge contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D97A3AE911F63C51', 'all', 'http://www.webmin.com/index.html', 'http://www.webmin.com/deb.html', 1, 1, 0, 0),
(62, 'Webmin', 'Webmin is a web-based interface for system administration for Unix. Using any modern web browser, you can setup user accounts, Apache, DNS, file sharing and much more. Webmin removes the need to manually edit Unix configuration files like /etc/passwd, and lets you manage a system from the console or remotely. See the standard modules page for a list of all the functions built into Webmin.', 'deb http://download.webmin.com/download/repository sarge contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D97A3AE911F63C51', 'all', 'http://www.webmin.com/index.html', 'http://www.webmin.com/deb.html', 2, 1, 1, 1),
(63, 'Webmin', 'Webmin is a web-based interface for system administration for Unix. Using any modern web browser, you can setup user accounts, Apache, DNS, file sharing and much more. Webmin removes the need to manually edit Unix configuration files like /etc/passwd, and lets you manage a system from the console or remotely. See the standard modules page for a list of all the functions built into Webmin.', 'deb http://download.webmin.com/download/repository sarge contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D97A3AE911F63C51', 'all', 'http://www.webmin.com/index.html', 'http://www.webmin.com/deb.html', 3, 1, 1, 1),
(64, 'Webmin', 'Webmin is a web-based interface for system administration for Unix. Using any modern web browser, you can setup user accounts, Apache, DNS, file sharing and much more. Webmin removes the need to manually edit Unix configuration files like /etc/passwd, and lets you manage a system from the console or remotely. See the standard modules page for a list of all the functions built into Webmin.', 'deb http://download.webmin.com/download/repository sarge contrib', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D97A3AE911F63C51', 'all', 'http://www.webmin.com/index.html', 'http://www.webmin.com/deb.html', 4, 1, 0, 0),
(65, 'openmediavault', 'openmediavault is the next generation network attached storage (NAS) solution based on Debian Linux. It contains services like SSH, (S)FTP, SMB/CIFS, DAAP media server, RSync, BitTorrent client and many more. Thanks to the modular design of the framework it can be enhanced via plugins.', 'deb http://packages.openmediavault.org/public erasmus main', 'deb-src http://packages.openmediavault.org/public erasmus main', 'apt-get update && apt-get install openmediavault-keyring && apt-get update', 'all', 'http://www.openmediavault.org', 'http://www.openmediavault.org/download.html', 1, 1, 1, 1),
(66, 'openmediavault', 'openmediavault is the next generation network attached storage (NAS) solution based on Debian Linux. It contains services like SSH, (S)FTP, SMB/CIFS, DAAP media server, RSync, BitTorrent client and many more. Thanks to the modular design of the framework it can be enhanced via plugins.', 'deb http://packages.openmediavault.org/public erasmus main', 'deb-src http://packages.openmediavault.org/public erasmus main', 'apt-get update && apt-get install openmediavault-keyring && apt-get update', 'all', 'http://www.openmediavault.org', 'http://www.openmediavault.org/download.html', 2, 1, 1, 1),
(67, 'openmediavault', 'openmediavault is the next generation network attached storage (NAS) solution based on Debian Linux. It contains services like SSH, (S)FTP, SMB/CIFS, DAAP media server, RSync, BitTorrent client and many more. Thanks to the modular design of the framework it can be enhanced via plugins.', 'deb http://packages.openmediavault.org/public erasmus main', 'deb-src http://packages.openmediavault.org/public erasmus main', 'apt-get update && apt-get install openmediavault-keyring && apt-get update', 'all', 'http://www.openmediavault.org', 'http://www.openmediavault.org/download.html', 3, 1, 0, 0),
(68, 'openmediavault', 'openmediavault is the next generation network attached storage (NAS) solution based on Debian Linux. It contains services like SSH, (S)FTP, SMB/CIFS, DAAP media server, RSync, BitTorrent client and many more. Thanks to the modular design of the framework it can be enhanced via plugins.', 'deb http://packages.openmediavault.org/public erasmus main', 'deb-src http://packages.openmediavault.org/public erasmus main', 'apt-get update && apt-get install openmediavault-keyring && apt-get update', 'all', 'http://www.openmediavault.org', 'http://www.openmediavault.org/download.html', 4, 1, 0, 0),
(69, 'DotDeb', 'Dotdeb is an extra repository providing up-to-date packages for your Debian servers', 'deb http://packages.dotdeb.org jessie all', 'deb-src http://packages.dotdeb.org jessie all', 'wget https://www.dotdeb.org/dotdeb.gpg && apt-key add dotdeb.gpg', 'all', 'https://www.dotdeb.org', 'https://www.dotdeb.org/instructions/', 1, 1, 0, 0),
(73, 'MEGA Sync Client', 'Easy automated syncing between your computers and your MEGA cloud drive.', 'deb http://mega.nz/linux/MEGAsync/Debian_9.0/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 4B4E7A9523ACD201', 'all', 'https://mega.nz/', 'https://mega.nz/linux/MEGAsync/', 2, 1, 1, 1),
(74, 'MEGA Sync Client', 'Easy automated syncing between your computers and your MEGA cloud drive.', 'deb http://mega.nz/linux/MEGAsync/Debian_9.0/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 4B4E7A9523ACD201', 'all', 'https://mega.nz/', 'https://mega.nz/linux/MEGAsync/', 4, 1, 1, 0),
(75, 'MEGA Sync Client', 'Easy automated syncing between your computers and your MEGA cloud drive.', 'deb http://mega.nz/linux/MEGAsync/Debian_8.0/ ./', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 4B4E7A9523ACD201', 'all', 'https://mega.nz/', 'https://mega.nz/linux/MEGAsync/', 1, 1, 0, 0),
(84, 'FusionDirectory', 'FusionDirectory provides a solution to daily management of data stored in an LDAP directory. ', 'deb http://repos.fusiondirectory.org/debian-jessie jessie main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E184859262B4981F', 'all', 'https://www.fusiondirectory.org/', 'https://www.fusiondirectory.org/debian/', 2, 1, 1, 0),
(85, 'FusionDirectory', 'FusionDirectory provides a solution to daily management of data stored in an LDAP directory. ', 'deb http://repos.fusiondirectory.org/debian-jessie jessie main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E184859262B4981F', 'all', 'https://www.fusiondirectory.org/', 'https://www.fusiondirectory.org/debian/', 3, 1, 1, 1),
(86, 'FusionDirectory', 'FusionDirectory provides a solution to daily management of data stored in an LDAP directory. ', 'deb http://repos.fusiondirectory.org/debian-jessie jessie main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E184859262B4981F', 'all', 'https://www.fusiondirectory.org/', 'https://www.fusiondirectory.org/debian/', 4, 1, 1, 0),
(87, 'FusionDirectory', 'FusionDirectory provides a solution to daily management of data stored in an LDAP directory. ', 'deb http://repos.fusiondirectory.org/debian-wheezy wheezy main\r\ndeb http://repos.fusiondirectory.org/debian-extra wheezy main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E184859262B4981F', 'all', 'https://www.fusiondirectory.org/', 'https://www.fusiondirectory.org/debian/', 1, 1, 0, 0),
(88, 'video-dl', 'I\'ve created a suite of programs to download videos from lots of websites, including, but not limited to, the Italian Rai.tv website, the Mediaset website and the LA7 website.', 'deb http://repo.daniil.it lenny main', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 72B97FD1D9672C93', 'all', 'http://daniil.it/video-dl', 'http://daniil.it/video-dl/#bash-script-installation-instructions', 1, 1, 0, 0),
(89, 'video-dl', 'I\'ve created a suite of programs to download videos from lots of websites, including, but not limited to, the Italian Rai.tv website, the Mediaset website and the LA7 website.', 'deb http://repo.daniil.it lenny main', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 72B97FD1D9672C93', 'all', 'http://daniil.it/video-dl', 'http://daniil.it/video-dl/#bash-script-installation-instructions', 2, 1, 1, 1),
(90, 'video-dl', 'I\'ve created a suite of programs to download videos from lots of websites, including, but not limited to, the Italian Rai.tv website, the Mediaset website and the LA7 website.', 'deb http://repo.daniil.it lenny main', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 72B97FD1D9672C93', 'all', 'http://daniil.it/video-dl', 'http://daniil.it/video-dl/#bash-script-installation-instructions', 3, 1, 1, 1),
(91, 'video-dl', 'I\'ve created a suite of programs to download videos from lots of websites, including, but not limited to, the Italian Rai.tv website, the Mediaset website and the LA7 website.', 'deb http://repo.daniil.it lenny main', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 72B97FD1D9672C93', 'all', 'http://daniil.it/video-dl', 'http://daniil.it/video-dl/#bash-script-installation-instructions', 4, 1, 0, 0),
(92, 'Resilio Sync', 'Resilient, fast and scalable file synchronization', 'deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 05CD43032484414B', 'all', 'https://www.resilio.com/', 'https://help.getsync.com/hc/en-us/articles/206178924', 1, 1, 0, 0),
(93, 'Resilio Sync', 'Resilient, fast and scalable file synchronization', 'deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 05CD43032484414B', 'all', 'https://www.resilio.com/', 'https://help.getsync.com/hc/en-us/articles/206178924', 2, 1, 1, 1),
(94, 'Resilio Sync', 'Resilient, fast and scalable file synchronization', 'deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 05CD43032484414B', 'all', 'https://www.resilio.com/', 'https://help.getsync.com/hc/en-us/articles/206178924', 3, 1, 0, 0),
(95, 'Resilio Sync', 'Resilient, fast and scalable file synchronization', 'deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 05CD43032484414B', 'all', 'https://www.resilio.com/', 'https://help.getsync.com/hc/en-us/articles/206178924', 4, 1, 0, 0),
(96, 'Proxmox', 'Proxmox Virtual Environment is a complete server virtualization management solution, based on KVM and container virtualization.', 'deb http://download.proxmox.com/debian stretch pve-no-subscription', '', 'wget -O- \"http://download.proxmox.com/debian/key.asc\" | apt-key add -', 'amd64', 'https://proxmox.com', 'https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Jessie', 2, 1, 1, 1),
(97, 'Proxmox', 'Proxmox Virtual Environment is a complete server virtualization management solution, based on KVM and container virtualization.', 'deb http://download.proxmox.com/debian jessie pve-no-subscription', '', 'wget -O- \"http://download.proxmox.com/debian/key.asc\" | apt-key add -', 'amd64', 'https://proxmox.com', 'https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Jessie', 1, 1, 0, 0),
(98, 'MariaDB', 'The MariaDB database server is published as free and open source software under the General Public License version 2. You can download and use it as much as you want free of charge. All use of the binaries from mariadb.org is at your own risk as stated in the GPLv2. While we do our best to make the world?s best database software, the MariaDB Foundation does not provide any guarantees and cannot be hold liable for any issues you may encounter.', 'deb http://mirror.23media.de/mariadb/repo/10.2/debian jessie main', 'deb-src http://mirror.23media.de/mariadb/repo/10.2/debian jessie main', 'apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db', 'i386,amd64', 'https://mariadb.org/', 'https://downloads.mariadb.org/mariadb/repositories/#mirror=rackspeed&distro=Debian&distro_release=wheezy--wheezy&version=10.1', 1, 1, 0, 0),
(100, 'MariaDB', 'The MariaDB database server is published as free and open source software under the General Public License version 2. You can download and use it as much as you want free of charge. All use of the binaries from mariadb.org is at your own risk as stated in the GPLv2. While we do our best to make the world?s best database software, the MariaDB Foundation does not provide any guarantees and cannot be hold liable for any issues you may encounter.', 'deb http://mirror.23media.de/mariadb/repo/10.2/debian stretch main', 'deb-src http://mirror.23media.de/mariadb/repo/10.2/debian stretch main', 'apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xF1656F24C74CD1D8', 'i386,amd64', 'https://mariadb.org/', 'https://downloads.mariadb.org/mariadb/repositories/#mirror=rackspeed&distro=Debian&distro_release=wheezy--wheezy&version=10.1', 2, 1, 0, 0),
(101, 'MariaDB', 'The MariaDB database server is published as free and open source software under the General Public License version 2. You can download and use it as much as you want free of charge. All use of the binaries from mariadb.org is at your own risk as stated in the GPLv2. While we do our best to make the world?s best database software, the MariaDB Foundation does not provide any guarantees and cannot be hold liable for any issues you may encounter.', 'deb http://mirror.23media.de/mariadb/repo/10.2/debian sid main', 'deb-src http://mirror.23media.de/mariadb/repo/10.2/debian sid main', 'apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xF1656F24C74CD1D8', 'amd64,i386', 'https://mariadb.org/', 'https://downloads.mariadb.org/mariadb/repositories/#mirror=rackspeed&distro=Debian&distro_release=wheezy--wheezy&version=10.1', 4, 1, 0, 0),
(102, 'Lazarus', 'Open Source GUI RAD IDE for free Pascal', 'deb http://www.hu.freepascal.org/lazarus/ lazarus-stable universe', '', 'gpg --keyserver hkp://pgp.mit.edu:11371 --recv-keys 6A11800F  && gpg --export --armor 0F7992B0 | apt-key add -', 'i386', 'http://www.lazarus.freepascal.org/', 'http://wiki.lazarus.freepascal.org/Lazarus_release_version_for_Ubuntu', 3, 1, 0, 0),
(103, 'TOX', 'A New Kind of Instant Messaging\r\nWhether it\'s corporations or governments, digital surveillance today is widespread. Tox is easy-to-use software that connects you with friends and family without anyone else listening in. While other big-name services require you to pay for features, Tox is completely free and comes without advertising — forever.', 'deb https://pkg.tox.chat/debian stable jessie ', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys A2B076511A171ABE', 'i386,amd64', 'https://tox.chat/index.html', 'https://wiki.tox.chat/doku.php', 1, 1, 0, 0),
(104, 'TOX', 'A New Kind of Instant Messaging\r\nWhether it\'s corporations or governments, digital surveillance today is widespread. Tox is easy-to-use software that connects you with friends and family without anyone else listening in. While other big-name services require you to pay for features, Tox is completely free and comes without advertising — forever.', 'deb https://pkg.tox.chat/debian stable stretch ', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys A2B076511A171ABE', 'i386,amd64', 'https://tox.chat/index.html', 'https://wiki.tox.chat/doku.php', 2, 1, 1, 1),
(105, 'TOX', 'A New Kind of Instant Messaging\r\nWhether it\'s corporations or governments, digital surveillance today is widespread. Tox is easy-to-use software that connects you with friends and family without anyone else listening in. While other big-name services require you to pay for features, Tox is completely free and comes without advertising — forever.', 'deb https://pkg.tox.chat/debian stable sid ', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys A2B076511A171ABE', 'i386,amd64', 'https://tox.chat/index.html', 'https://wiki.tox.chat/doku.php', 4, 1, 0, 0),
(107, 'Jabber.at ejabberd Repo', 'Jabber.at Repo for ejabbered', 'deb https://apt.jabber.at jessie ejabberd', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 1, 1, 0, 0),
(108, 'Jabber.at ejabberd Repo', 'Jabber.at Repo for ejabbered', 'deb https://apt.jabber.at stretch ejabberd', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 2, 1, 0, 0),
(109, 'Jabber.at ejabberd Repo', 'Jabber.at Repo for ejabbered', 'deb https://apt.jabber.at unstable ejabberd', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 4, 1, 0, 0),
(111, 'Jabber.at gajim Repo', 'Jabber.at Repo for gajim', 'deb https://apt.jabber.at jessie gajim', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 1, 1, 0, 0),
(112, 'Jabber.at gajim Repo', 'Jabber.at Repo for gajim', 'deb https://apt.jabber.at stretch gajim', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 2, 1, 0, 0),
(113, 'Jabber.at gajim Repo', 'Jabber.at Repo for gajim', 'deb https://apt.jabber.at unstable gajim', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 4, 1, 0, 0),
(115, 'Jabber.at mcabber Repo', 'Jabber.at Repo for mcabber', 'deb https://apt.jabber.at jessie mcabber', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 1, 1, 0, 0);
INSERT INTO `repos` (`repo_id`, `repo_name`, `repo_desc`, `repo_url`, `repo_url_src`, `repo_gpg`, `repo_arch`, `repo_homepage`, `repo_documentation`, `repo_release`, `repo_checked`, `issue`, `issue_key`) VALUES
(116, 'Jabber.at mcabber Repo', 'Jabber.at Repo for mcabber', 'deb https://apt.jabber.at stretch mcabber', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 2, 1, 1, 1),
(117, 'Jabber.at mcabber Repo', 'Jabber.at Repo for mcabber', 'deb https://apt.jabber.at unstable mcabber', '', 'wget -qO- https://apt.jabber.at/gpg-key | apt-key add -', 'i386,amd64', 'https://jabber.at', 'https://jabber.at/p/apt-repository/', 4, 1, 0, 0),
(118, 'Vivaldi Browser', 'Vivaldi is a freeware, cross-platform web browser developed by Vivaldi Technologies, a company founded by Opera Software co-founder and former CEO Jon Stephenson von Tetzchner and Tatsuki Tomita. The browser was officially launched on April 12, 2016', 'deb http://repo.vivaldi.com/stable/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 2CC26F777B8B44A1', 'i386,amd64', 'https://vivaldi.net/', 'https://forum.vivaldi.net/topic/1803/vivaldi-repo/15', 1, 1, 0, 0),
(119, 'Vivaldi Browser', 'Vivaldi is a freeware, cross-platform web browser developed by Vivaldi Technologies, a company founded by Opera Software co-founder and former CEO Jon Stephenson von Tetzchner and Tatsuki Tomita. The browser was officially launched on April 12, 2016', 'deb http://repo.vivaldi.com/stable/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 2CC26F777B8B44A1', 'i386,amd64', 'https://vivaldi.net/', 'https://forum.vivaldi.net/topic/1803/vivaldi-repo/15', 2, 1, 0, 0),
(120, 'Vivaldi Browser', 'Vivaldi is a freeware, cross-platform web browser developed by Vivaldi Technologies, a company founded by Opera Software co-founder and former CEO Jon Stephenson von Tetzchner and Tatsuki Tomita. The browser was officially launched on April 12, 2016', 'deb http://repo.vivaldi.com/stable/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 2CC26F777B8B44A1', 'i386,amd64', 'https://vivaldi.net/', 'https://forum.vivaldi.net/topic/1803/vivaldi-repo/15', 3, 1, 1, 0),
(121, 'Vivaldi Browser', 'Vivaldi is a freeware, cross-platform web browser developed by Vivaldi Technologies, a company founded by Opera Software co-founder and former CEO Jon Stephenson von Tetzchner and Tatsuki Tomita. The browser was officially launched on April 12, 2016', 'deb http://repo.vivaldi.com/stable/deb/ stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 2CC26F777B8B44A1', 'i386,amd64', 'https://vivaldi.net/', 'https://forum.vivaldi.net/topic/1803/vivaldi-repo/15', 4, 1, 0, 0),
(126, 'Paper GTK Theme', 'Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons. Each icon has been meticulously designed for pixel-perfect viewing.', 'deb http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'deb-src http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 3766223989993A70', 'all', 'https://snwh.org/paper', 'https://snwh.org/paper/support', 1, 1, 0, 0),
(127, 'Paper GTK Theme', 'Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons. Each icon has been meticulously designed for pixel-perfect viewing.', 'deb http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'deb-src http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 3766223989993A70', 'all', 'https://snwh.org/paper', 'https://snwh.org/paper/support', 2, 1, 0, 0),
(128, 'Paper GTK Theme', 'Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons. Each icon has been meticulously designed for pixel-perfect viewing.', 'deb http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'deb-src http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 3766223989993A70', 'all', 'https://snwh.org/paper', 'https://snwh.org/paper/support', 3, 1, 0, 0),
(129, 'Paper GTK Theme', 'Paper is a modern freedesktop icon theme whose design is based around the use of bold colours and simple geometric shapes to compose icons. Each icon has been meticulously designed for pixel-perfect viewing.', 'deb http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'deb-src http://ppa.launchpad.net/snwh/pulp/ubuntu yakkety main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 3766223989993A70', 'all', 'https://snwh.org/paper', 'https://snwh.org/paper/support', 4, 1, 0, 0),
(130, 'Papirus GTK Theme', 'Papirus is a free and open source SVG icon theme for Linux, based on Paper Icon Set with a lot of new icons and a few extras, like Hardcode-Tray support, KDE colorscheme support, Folder Color support, and others.', 'deb http://ppa.launchpad.net/papirus/papirus/ubuntu artful main ', 'deb-src http://ppa.launchpad.net/papirus/papirus/ubuntu artful main ', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E58A9D36647CAE7F', 'all', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 1, 1, 0, 0),
(131, 'Papirus GTK Theme', 'Papirus is a free and open source SVG icon theme for Linux, based on Paper Icon Set with a lot of new icons and a few extras, like Hardcode-Tray support, KDE colorscheme support, Folder Color support, and others.', 'deb http://ppa.launchpad.net/papirus/papirus/ubuntu artful main ', 'deb-src http://ppa.launchpad.net/papirus/papirus/ubuntu artful main ', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E58A9D36647CAE7F', 'all', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 2, 1, 1, 1),
(132, 'Papirus GTK Theme', 'Papirus is a free and open source SVG icon theme for Linux, based on Paper Icon Set with a lot of new icons and a few extras, like Hardcode-Tray support, KDE colorscheme support, Folder Color support, and others.', 'deb http://ppa.launchpad.net/papirus/papirus/ubuntu artful main ', 'deb-src http://ppa.launchpad.net/papirus/papirus/ubuntu artful main ', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E58A9D36647CAE7F', 'all', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 3, 1, 0, 0),
(133, 'Papirus GTK Theme', 'Papirus is a free and open source SVG icon theme for Linux, based on Paper Icon Set with a lot of new icons and a few extras, like Hardcode-Tray support, KDE colorscheme support, Folder Color support, and others.', 'deb http://ppa.launchpad.net/papirus/papirus/ubuntu artful main ', 'deb-src http://ppa.launchpad.net/papirus/papirus/ubuntu artful main ', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys E58A9D36647CAE7F', 'all', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme', 4, 1, 0, 0),
(135, 'Squash TM', 'Squash TM is an open source tool for test repository management: requirements management, test cases, campaign and more... Squash TM is full web and natively inter- and multi- projects. ', 'deb http://repo.squashtest.org/debian jessie main', '', 'wget -q -O - http://repo.squashtest.org/repo.squashtest.org.gpg.key | apt-key add -', 'amd64,i386', 'http://www.squashtest.org', 'https://sites.google.com/a/henix.fr/wiki-squash-tm/', 1, 1, 0, 0),
(136, 'Skype', 'Skype is an instant messaging app that provides online text message and video chat services. Users may transmit both text and video messages and may exchange digital documents such as images, text, and video. Skype allows video conference calls.', 'deb https://repo.skype.com/deb stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1F3045A5DF7587C3', 'amd64', 'https://skype.com', 'https://support.skype.com/en/skype/linux/', 2, 1, 1, 0),
(137, 'Skype', 'Skype is an instant messaging app that provides online text message and video chat services. Users may transmit both text and video messages and may exchange digital documents such as images, text, and video. Skype allows video conference calls.', 'deb https://repo.skype.com/deb stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1F3045A5DF7587C3', 'amd64', 'https://skype.com', 'https://support.skype.com/en/skype/linux/', 3, 1, 0, 0),
(138, 'Skype', 'Skype is an instant messaging app that provides online text message and video chat services. Users may transmit both text and video messages and may exchange digital documents such as images, text, and video. Skype allows video conference calls.', 'deb https://repo.skype.com/deb stable main', '', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1F3045A5DF7587C3', 'amd64', 'https://skype.com', 'https://support.skype.com/en/skype/linux/', 4, 1, 0, 0),
(139, 'Visual Studio Code', 'Visual Studio Code is a source code editor developed by Microsoft for Windows, Linux and macOS. It includes support for debugging, embedded Git control, syntax highlighting, intelligent code completion, snippets, and code refactoring. It is also customizable, so users can change the editor\'s theme, keyboard shortcuts, and preferences. It is free and open-source, although the official download is under a proprietary license.', 'deb https://packages.microsoft.com/repos/vscode stable main', '', 'curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg && mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg', 'amd64', 'https://code.visualstudio.com', 'https://code.visualstudio.com/docs/setup/linux', 2, 1, 1, 1),
(140, 'Visual Studio Code', 'Visual Studio Code is a source code editor developed by Microsoft for Windows, Linux and macOS. It includes support for debugging, embedded Git control, syntax highlighting, intelligent code completion, snippets, and code refactoring. It is also customizable, so users can change the editor\'s theme, keyboard shortcuts, and preferences. It is free and open-source, although the official download is under a proprietary license.', 'deb https://packages.microsoft.com/repos/vscode stable main', '', 'curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg && mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg', 'amd64', 'https://code.visualstudio.com', 'https://code.visualstudio.com/docs/setup/linux', 3, 1, 0, 0),
(141, 'Visual Studio Code', 'Visual Studio Code is a source code editor developed by Microsoft for Windows, Linux and macOS. It includes support for debugging, embedded Git control, syntax highlighting, intelligent code completion, snippets, and code refactoring. It is also customizable, so users can change the editor\'s theme, keyboard shortcuts, and preferences. It is free and open-source, although the official download is under a proprietary license.', 'deb https://packages.microsoft.com/repos/vscode stable main', '', 'curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg && mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg', 'amd64', 'https://code.visualstudio.com', 'https://code.visualstudio.com/docs/setup/linux', 4, 1, 0, 0),
(143, 'nginx', 'Nginx, is a web server, which can also be used as a reverse proxy, load balancer and HTTP cache.', 'deb http://nginx.org/packages/debian/ jessie nginx', 'deb-src http://nginx.org/packages/debian/ jessie nginx', 'wget https://nginx.org/keys/nginx_signing.key && apt-key add nginx_signing.key', 'amd64,i386', 'https://nginx.org', 'https://nginx.org/en/linux_packages.html#stable', 1, 1, 1, 1),
(144, 'nginx', 'Nginx, is a web server, which can also be used as a reverse proxy, load balancer and HTTP cache.', 'deb http://nginx.org/packages/debian/ stretch nginx', 'deb-src http://nginx.org/packages/debian/ stretch nginx', 'wget https://nginx.org/keys/nginx_signing.key && apt-key add nginx_signing.key', 'amd64,i386', 'https://nginx.org', 'https://nginx.org/en/linux_packages.html#stable', 2, 1, 1, 1),
(145, 'nginx', 'Nginx, is a web server, which can also be used as a reverse proxy, load balancer and HTTP cache.', 'deb http://nginx.org/packages/debian/ stretch nginx', 'deb-src http://nginx.org/packages/debian/ stretch nginx', 'wget https://nginx.org/keys/nginx_signing.key && apt-key add nginx_signing.key', 'amd64,i386', 'https://nginx.org', 'https://nginx.org/en/linux_packages.html#stable', 4, 1, 0, 0),
(147, 'PostgreSQL', 'PostgreSQL, often simply Postgres, is an object-relational database management system (ORDBMS) with an emphasis on extensibility and standards compliance.', 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main', '', 'wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -', 'amd64,i386', 'https://www.postgresql.org', 'https://www.postgresql.org/download/linux/debian/', 1, 1, 0, 0),
(148, 'PostgreSQL', 'PostgreSQL, often simply Postgres, is an object-relational database management system (ORDBMS) with an emphasis on extensibility and standards compliance.', 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main', '', 'wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -', 'amd64,i386', 'https://www.postgresql.org', 'https://www.postgresql.org/download/linux/debian/', 2, 1, 0, 0),
(149, 'PostgreSQL', 'PostgreSQL, often simply Postgres, is an object-relational database management system (ORDBMS) with an emphasis on extensibility and standards compliance.', 'deb http://apt.postgresql.org/pub/repos/apt/ sid-pgdg main', '', 'wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -', 'amd64,i386', 'https://www.postgresql.org', 'https://www.postgresql.org/download/linux/debian/', 4, 1, 0, 0),
(150, 'nginx', 'Nginx, is a web server, which can also be used as a reverse proxy, load balancer and HTTP cache.', 'deb http://nginx.org/packages/debian/ stretch nginx', 'deb-src http://nginx.org/packages/debian/ stretch nginx', 'wget https://nginx.org/keys/nginx_signing.key && apt-key add nginx_signing.key', 'amd64,i386', 'https://nginx.org', 'https://nginx.org/en/linux_packages.html#stable', 3, 1, 0, 0),
(151, 'Pantheon Desktop', 'The Pantheon desktop environment is built on top of the GNOME software base, i.e. GTK+, GDK, Cairo, GLib (including GObject and GIO), GVfs and Tracker', 'deb http://gandalfn.ovh/debian stretch-loki main contrib', '', 'wget http://gandalfn.ovh/debian/pantheon-debian.gpg.key -O- | apt-key add -', 'amd64', 'https://gitlab.com/pantheon-debian/pantheon-debian', 'https://gitlab.com/pantheon-debian/pantheon-debian/wikis/home', 3, 1, 1, 0),
(152, 'Pantheon Desktop', 'The Pantheon desktop environment is built on top of the GNOME software base, i.e. GTK+, GDK, Cairo, GLib (including GObject and GIO), GVfs and Tracker', 'deb http://gandalfn.ovh/debian stretch-loki main contrib', '', 'wget http://gandalfn.ovh/debian/pantheon-debian.gpg.key -O- | apt-key add -', 'amd64', 'https://gitlab.com/pantheon-debian/pantheon-debian', 'https://gitlab.com/pantheon-debian/pantheon-debian/wikis/home', 4, 1, 0, 0),
(153, 'Nextcloud Client', 'Nextcloud is a suite of client-server software for creating and using file hosting services. It is functionally similar to Dropbox, although Nextcloud is free and open-source, allowing anyone to install and operate it on a private server. In contrast to proprietary services like Dropbox, the open architecture allows adding additional functionality to the server in form of applications.', 'deb http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/ /', '', 'wget -q -O - http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/Release.key | apt-key add -', 'amd64,i386', 'http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/', 'http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/', 2, 1, 0, 0),
(154, 'Nextcloud Client', 'Nextcloud is a suite of client-server software for creating and using file hosting services. It is functionally similar to Dropbox, although Nextcloud is free and open-source, allowing anyone to install and operate it on a private server. In contrast to proprietary services like Dropbox, the open architecture allows adding additional functionality to the server in form of applications.', 'deb http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/ /', '', 'wget -q -O - http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/Release.key | apt-key add -', 'amd64,i386', 'http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/', 'http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/', 3, 1, 0, 0),
(155, 'Nextcloud Client', 'Nextcloud is a suite of client-server software for creating and using file hosting services. It is functionally similar to Dropbox, although Nextcloud is free and open-source, allowing anyone to install and operate it on a private server. In contrast to proprietary services like Dropbox, the open architecture allows adding additional functionality to the server in form of applications.', 'deb http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/ /', '', 'wget -q -O - http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/Release.key | apt-key add -', 'amd64,i386', 'http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/', 'http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/', 4, 1, 0, 0),
(156, 'Nextcloud Client', 'Nextcloud is a suite of client-server software for creating and using file hosting services. It is functionally similar to Dropbox, although Nextcloud is free and open-source, allowing anyone to install and operate it on a private server. In contrast to proprietary services like Dropbox, the open architecture allows adding additional functionality to the server in form of applications.', 'deb http://download.opensuse.org/repositories/home:/ivaradi/Debian_8.0/ /', '', 'wget -q -O - http://download.opensuse.org/repositories/home:/ivaradi/Debian_8.0/Release.key | apt-key add -', 'amd64,i386', 'http://download.opensuse.org/repositories/home:/ivaradi/Debian_8.0/', 'http://download.opensuse.org/repositories/home:/ivaradi/Debian_8.0/', 1, 1, 1, 1),
(157, 'Pantheon Desktop', 'The Pantheon desktop environment is built on top of the GNOME software base, i.e. GTK+, GDK, Cairo, GLib (including GObject and GIO), GVfs and Tracker', 'deb http://gandalfn.ovh/debian stretch-loki main contrib', '', 'wget http://gandalfn.ovh/debian/pantheon-debian.gpg.key -O- | apt-key add -', 'amd64', 'https://gitlab.com/pantheon-debian/pantheon-debian', 'https://gitlab.com/pantheon-debian/pantheon-debian/wikis/home', 2, 1, 1, 1),
(158, 'Enpass Password Manager', 'Enpass is a Freemium software password management program to securely store passwords and other credentials.', 'deb http://repo.sinew.in/ stable main', '', 'wget -O - https://dl.sinew.in/keys/enpass-linux.key | apt-key add -', 'all', 'https://www.enpass.io', 'https://www.enpass.io/kb/how-to-install-on-linux/', 1, 1, 1, 1),
(159, 'Enpass Password Manager', 'Enpass is a Freemium software password management program to securely store passwords and other credentials.', 'deb http://repo.sinew.in/ stable main', '', 'wget -O - https://dl.sinew.in/keys/enpass-linux.key | apt-key add -', 'all', 'https://www.enpass.io', 'https://www.enpass.io/kb/how-to-install-on-linux/', 2, 1, 0, 0),
(160, 'Enpass Password Manager', 'Enpass is a Freemium software password management program to securely store passwords and other credentials.', 'deb http://repo.sinew.in/ stable main', '', 'wget -O - https://dl.sinew.in/keys/enpass-linux.key | apt-key add -', 'all', 'https://www.enpass.io', 'https://www.enpass.io/kb/how-to-install-on-linux/', 3, 1, 0, 0),
(161, 'Enpass Password Manager', 'Enpass is a Freemium software password management program to securely store passwords and other credentials.', 'deb http://repo.sinew.in/ stable main', '', 'wget -O - https://dl.sinew.in/keys/enpass-linux.key | apt-key add -', 'all', 'https://www.enpass.io', 'https://www.enpass.io/kb/how-to-install-on-linux/', 4, 1, 0, 0),
(162, 'Lynis', 'Lynis is an open source security auditing tool. Used by system administrators, security professionals, and auditors, to evaluate the security defenses of their Linux and UNIX-based systems. It runs on the host itself, so it performs more extensive security scans than vulnerability scanners.', 'deb https://packages.cisofy.com/community/lynis/deb/ jessie main', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C80E383C3DE9F082E01391A0366C67DE91CA5D5F', '', 'https://packages.cisofy.com/community/#debian-ubuntu', 'https://packages.cisofy.com/community/#debian-ubuntu', 1, 1, 0, 0),
(163, 'Lynis', 'Lynis is an open source security auditing tool. Used by system administrators, security professionals, and auditors, to evaluate the security defenses of their Linux and UNIX-based systems. It runs on the host itself, so it performs more extensive security scans than vulnerability scanners.', 'deb https://packages.cisofy.com/community/lynis/deb/ stable main', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C80E383C3DE9F082E01391A0366C67DE91CA5D5F', '', 'https://packages.cisofy.com/community/#debian-ubuntu', 'https://packages.cisofy.com/community/#debian-ubuntu', 2, 1, 1, 1),
(164, 'Lynis', 'Lynis is an open source security auditing tool. Used by system administrators, security professionals, and auditors, to evaluate the security defenses of their Linux and UNIX-based systems. It runs on the host itself, so it performs more extensive security scans than vulnerability scanners.', 'deb https://packages.cisofy.com/community/lynis/deb/ stable main', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C80E383C3DE9F082E01391A0366C67DE91CA5D5F', '', 'https://packages.cisofy.com/community/#debian-ubuntu', 'https://packages.cisofy.com/community/#debian-ubuntu', 3, 1, 1, 0),
(165, 'Lynis', 'Lynis is an open source security auditing tool. Used by system administrators, security professionals, and auditors, to evaluate the security defenses of their Linux and UNIX-based systems. It runs on the host itself, so it performs more extensive security scans than vulnerability scanners.', 'deb https://packages.cisofy.com/community/lynis/deb/ stable main', '', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C80E383C3DE9F082E01391A0366C67DE91CA5D5F', '', 'https://packages.cisofy.com/community/#debian-ubuntu', 'https://packages.cisofy.com/community/#debian-ubuntu', 4, 1, 0, 0),
(166, 'Benno MailArchiv', 'Mailrchiv software from germany', 'deb http://www.benno-mailarchiv.de/download/debian /', '', 'wget -O - http://www.benno-mailarchiv.de/download/debian/benno.asc | apt-key add -', '', 'http://benno-mailarchiv.de', 'http://wiki.benno-mailarchiv.de/doku.php#installation_und_update', 1, 1, 1, 1),
(167, 'Benno MailArchiv', 'Mailrchiv software from germany', 'deb http://www.benno-mailarchiv.de/download/debian /', '', 'wget -O - http://www.benno-mailarchiv.de/download/debian/benno.asc | apt-key add -', '', 'http://benno-mailarchiv.de', 'http://wiki.benno-mailarchiv.de/doku.php#installation_und_update', 2, 1, 1, 1),
(168, 'Benno MailArchiv', 'Mailrchiv software from germany', 'deb http://www.benno-mailarchiv.de/download/debian /', '', 'wget -O - http://www.benno-mailarchiv.de/download/debian/benno.asc | apt-key add -', '', 'http://benno-mailarchiv.de', 'http://wiki.benno-mailarchiv.de/doku.php#installation_und_update', 3, 1, 1, 0),
(169, 'Benno MailArchiv', 'Mailrchiv software from germany', 'deb http://www.benno-mailarchiv.de/download/debian /', '', 'wget -O - http://www.benno-mailarchiv.de/download/debian/benno.asc | apt-key add -', '', 'http://benno-mailarchiv.de', 'http://wiki.benno-mailarchiv.de/doku.php#installation_und_update', 4, 1, 1, 1),
(170, 'Sublime Text', 'A sophisticated text editor for code, markup and prose', 'deb https://download.sublimetext.com/ apt/stable/', '', 'wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -', '', 'https://www.sublimetext.com/', 'https://www.sublimetext.com/docs/3/linux_repositories.html', 1, 1, 0, 0),
(171, 'Sublime Text', 'A sophisticated text editor for code, markup and prose', 'deb https://download.sublimetext.com/ apt/stable/', '', 'wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -', '', 'https://www.sublimetext.com/', 'https://www.sublimetext.com/docs/3/linux_repositories.html', 2, 1, 0, 0),
(172, 'Sublime Text', 'A sophisticated text editor for code, markup and prose', 'deb https://download.sublimetext.com/ apt/stable/', '', 'wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -', '', 'https://www.sublimetext.com/', 'https://www.sublimetext.com/docs/3/linux_repositories.html', 3, 1, 0, 0),
(173, 'Sublime Text', 'A sophisticated text editor for code, markup and prose', 'deb https://download.sublimetext.com/ apt/stable/', '', 'wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -', '', 'https://www.sublimetext.com/', 'https://www.sublimetext.com/docs/3/linux_repositories.html', 4, 1, 0, 0),
(174, 'Dino', 'A modern Jabber/XMPP Client using GTK+/Vala with support for OTR and OMEMO', 'deb http://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/Debian_9.0/ /', '', 'wget -nv https://download.opensuse.org/repositories/network:messaging:xmpp:dino/Debian_9.0/Release.key -O Release.key && apt-key add - < Release.key && rm Release.key', 'amd64,i386', 'https://github.com/dino/dino', 'https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&package=dino', 2, 1, 1, 1),
(175, 'Dino', 'A modern Jabber/XMPP Client using GTK+/Vala with support for OTR and OMEMO', 'deb http://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/Debian_9.0/ /', '', 'wget -nv https://download.opensuse.org/repositories/network:messaging:xmpp:dino/Debian_9.0/Release.key -O Release.key && apt-key add - < Release.key && rm Release.key', 'amd64,i386', 'https://github.com/dino/dino', 'https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&package=dino', 3, 1, 0, 0),
(176, 'Dino', 'A modern Jabber/XMPP Client using GTK+/Vala with support for OTR and OMEMO', 'deb http://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/Debian_9.0/ /', '', 'wget -nv https://download.opensuse.org/repositories/network:messaging:xmpp:dino/Debian_9.0/Release.key -O Release.key && apt-key add - < Release.key && rm Release.key', 'amd64,i386', 'https://github.com/dino/dino', 'https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&package=dino', 4, 1, 0, 0),
(177, 'Docker CE', 'Docker is a software technology providing containers, promoted by the company Docker, Inc. Docker provides an additional layer of abstraction and automation of operating-system-level virtualization on Windows and Linux. Docker uses the resource isolation features of the Linux kernel such as cgroups and kernel namespaces, and a union-capable file system such as OverlayFS and others to allow independent \"containers\" to run within a single Linux instance, avoiding the overhead of starting and maintaining virtual machines (VMs).', 'deb https://download.docker.com/linux/debian jessie stable', '', 'curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -', 'amd64', 'https://docker.com', 'https://docs.docker.com/engine/installation/linux/docker-ce/debian/#set-up-the-repository', 1, 1, 0, 0),
(178, 'Docker CE', 'Docker is a software technology providing containers, promoted by the company Docker, Inc. Docker provides an additional layer of abstraction and automation of operating-system-level virtualization on Windows and Linux. Docker uses the resource isolation features of the Linux kernel such as cgroups and kernel namespaces, and a union-capable file system such as OverlayFS and others to allow independent \"containers\" to run within a single Linux instance, avoiding the overhead of starting and maintaining virtual machines (VMs).', 'deb https://download.docker.com/linux/debian stretch stable', '', 'curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -', 'amd64', 'https://docker.com', 'https://docs.docker.com/engine/installation/linux/docker-ce/debian/#set-up-the-repository', 2, 1, 0, 0),
(179, 'Icon Repo', 'This Repo contains different icons from different creators but available by http://www.NoobsLab.com', 'deb http://ppa.launchpad.net/noobslab/icons/ubuntu artful main', 'deb-src http://ppa.launchpad.net/noobslab/icons/ubuntu artful main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D530E028F59EAE4D', 'all', 'http://www.NoobsLab.com', 'This PPA contains different icons from different creators but available by http://www.NoobsLab.com', 1, 1, 0, 0),
(180, 'Icon Repo', 'This Repo contains different icons from different creators but available by http://www.NoobsLab.com', 'deb http://ppa.launchpad.net/noobslab/icons/ubuntu artful main', 'deb-src http://ppa.launchpad.net/noobslab/icons/ubuntu artful main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D530E028F59EAE4D', 'all', 'http://www.NoobsLab.com', 'This PPA contains different icons from different creators but available by http://www.NoobsLab.com', 2, 1, 1, 1),
(181, 'Icon Repo', 'This Repo contains different icons from different creators but available by http://www.NoobsLab.com', 'deb http://ppa.launchpad.net/noobslab/icons/ubuntu artful main', 'deb-src http://ppa.launchpad.net/noobslab/icons/ubuntu artful main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D530E028F59EAE4D', 'all', 'http://www.NoobsLab.com', 'This PPA contains different icons from different creators but available by http://www.NoobsLab.com', 3, 1, 0, 0),
(182, 'Icon Repo', 'This Repo contains different icons from different creators but available by http://www.NoobsLab.com', 'deb http://ppa.launchpad.net/noobslab/icons/ubuntu artful main', 'deb-src http://ppa.launchpad.net/noobslab/icons/ubuntu artful main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D530E028F59EAE4D', 'all', 'http://www.NoobsLab.com', 'This PPA contains different icons from different creators but available by http://www.NoobsLab.com', 4, 1, 0, 0),
(183, 'Atom Editor', 'Atom is a text editor that\'s modern, approachable, yet hackable to the core—a tool you can customize to do anything but also use productively without ever touching a config file.', 'deb https://dl.bintray.com/alanfranz/atom-apt stable main', '', 'curl https://www.franzoni.eu/keys/D401AB61.txt | apt-key add -', 'amd64,i386', 'https://atom.io', 'https://github.com/alanfranz/atom-text-editor-repository/blob/master/README.md', 1, 1, 0, 0),
(184, 'Atom Editor', 'Atom is a text editor that\'s modern, approachable, yet hackable to the core—a tool you can customize to do anything but also use productively without ever touching a config file.', 'deb https://dl.bintray.com/alanfranz/atom-apt stable main', '', 'curl https://www.franzoni.eu/keys/D401AB61.txt | apt-key add -', 'amd64,i386', 'https://atom.io', 'https://github.com/alanfranz/atom-text-editor-repository/blob/master/README.md', 2, 1, 1, 1),
(185, 'Atom Editor', 'Atom is a text editor that\'s modern, approachable, yet hackable to the core—a tool you can customize to do anything but also use productively without ever touching a config file.', 'deb https://dl.bintray.com/alanfranz/atom-apt stable main', '', 'curl https://www.franzoni.eu/keys/D401AB61.txt | apt-key add -', 'amd64,i386', 'https://atom.io', 'https://github.com/alanfranz/atom-text-editor-repository/blob/master/README.md', 3, 1, 0, 0),
(186, 'Atom Editor', 'Atom is a text editor that\'s modern, approachable, yet hackable to the core—a tool you can customize to do anything but also use productively without ever touching a config file.', 'deb https://dl.bintray.com/alanfranz/atom-apt stable main', '', 'curl https://www.franzoni.eu/keys/D401AB61.txt | apt-key add -', 'amd64,i386', 'https://atom.io', 'https://github.com/alanfranz/atom-text-editor-repository/blob/master/README.md', 4, 1, 0, 0),
(187, 'Adapta GTK Theme', 'An adaptive Gtk+ theme based on Material Design Guidelines.', 'deb http://ppa.launchpad.net/tista/adapta/ubuntu artful main', 'deb-src http://ppa.launchpad.net/tista/adapta/ubuntu artful main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys EAC0D406E5D79A82ADEEDFDFB76E53652D87398A', 'all', 'https://github.com/adapta-project/adapta-gtk-theme', 'https://launchpad.net/~tista/+archive/ubuntu/adapta', 1, 1, 1, 0),
(188, 'Adapta GTK Theme', 'An adaptive Gtk+ theme based on Material Design Guidelines.', 'deb http://ppa.launchpad.net/tista/adapta/ubuntu artful main', 'deb-src http://ppa.launchpad.net/tista/adapta/ubuntu artful main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys EAC0D406E5D79A82ADEEDFDFB76E53652D87398A', 'all', 'https://github.com/adapta-project/adapta-gtk-theme', 'https://launchpad.net/~tista/+archive/ubuntu/adapta', 2, 1, 1, 1),
(189, 'Adapta GTK Theme', 'An adaptive Gtk+ theme based on Material Design Guidelines.', 'deb http://ppa.launchpad.net/tista/adapta/ubuntu artful main', 'deb-src http://ppa.launchpad.net/tista/adapta/ubuntu artful main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys EAC0D406E5D79A82ADEEDFDFB76E53652D87398A', 'all', 'https://github.com/adapta-project/adapta-gtk-theme', 'https://launchpad.net/~tista/+archive/ubuntu/adapta', 3, 1, 1, 0),
(190, 'Adapta GTK Theme', 'An adaptive Gtk+ theme based on Material Design Guidelines.', 'deb http://ppa.launchpad.net/tista/adapta/ubuntu artful main', 'deb-src http://ppa.launchpad.net/tista/adapta/ubuntu artful main', 'apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys EAC0D406E5D79A82ADEEDFDFB76E53652D87398A', 'all', 'https://github.com/adapta-project/adapta-gtk-theme', 'https://launchpad.net/~tista/+archive/ubuntu/adapta', 4, 1, 0, 0),
(191, 'Toot - a Mastodon CLI client', 'Interact with Mastodon social networks from the command line.', 'deb http://bezdomni.net/packages/ ./', '', 'curl https://keybase.io/ihabunek/pgp_keys.asc | apt-key add -', 'all', 'https://github.com/ihabunek/toot', 'https://github.com/ihabunek/toot', 1, 1, 0, 0),
(192, 'Toot - a Mastodon CLI client', 'Interact with Mastodon social networks from the command line.', 'deb http://bezdomni.net/packages/ ./', '', 'curl https://keybase.io/ihabunek/pgp_keys.asc | apt-key add -', 'all', 'https://github.com/ihabunek/toot', 'https://github.com/ihabunek/toot', 2, 1, 0, 0),
(193, 'Toot - a Mastodon CLI client', 'Interact with Mastodon social networks from the command line.', 'deb http://bezdomni.net/packages/ ./', '', 'curl https://keybase.io/ihabunek/pgp_keys.asc | apt-key add -', 'all', 'https://github.com/ihabunek/toot', 'https://github.com/ihabunek/toot', 3, 1, 0, 0),
(194, 'Toot - a Mastodon CLI client', 'Interact with Mastodon social networks from the command line.', 'deb http://bezdomni.net/packages/ ./', '', 'curl https://keybase.io/ihabunek/pgp_keys.asc | apt-key add -', 'all', 'https://github.com/ihabunek/toot', 'https://github.com/ihabunek/toot', 4, 1, 0, 0),
(195, 'Ubuntuzilla', 'This is the home of the Ubuntuzilla project, hosts an APT repository with .deb repacks of the latest official release versions of Mozilla Firefox, Mozilla SeaMonkey, and Mozilla Thunderbird. This repository should work on any APT-based distribution, including Ubuntu descendants, and Debian descendants. The project was born on Ubuntu forums, but despite the name is not really specific to Ubuntu.', 'deb http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt all main', '', 'apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2667CA5C', 'all', 'https://sourceforge.net/p/ubuntuzilla/wiki/Main_Page/', 'https://sourceforge.net/p/ubuntuzilla/wiki/Main_Page/', 1, 1, 0, 0),
(196, 'Ubuntuzilla', 'This is the home of the Ubuntuzilla project, hosts an APT repository with .deb repacks of the latest official release versions of Mozilla Firefox, Mozilla SeaMonkey, and Mozilla Thunderbird. This repository should work on any APT-based distribution, including Ubuntu descendants, and Debian descendants. The project was born on Ubuntu forums, but despite the name is not really specific to Ubuntu.', 'deb http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt all main', '', 'apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2667CA5C', 'all', 'https://sourceforge.net/p/ubuntuzilla/wiki/Main_Page/', 'https://sourceforge.net/p/ubuntuzilla/wiki/Main_Page/', 2, 1, 0, 0),
(197, 'Ubuntuzilla', 'This is the home of the Ubuntuzilla project, hosts an APT repository with .deb repacks of the latest official release versions of Mozilla Firefox, Mozilla SeaMonkey, and Mozilla Thunderbird. This repository should work on any APT-based distribution, including Ubuntu descendants, and Debian descendants. The project was born on Ubuntu forums, but despite the name is not really specific to Ubuntu.', 'deb http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt all main', '', 'apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2667CA5C', 'all', 'https://sourceforge.net/p/ubuntuzilla/wiki/Main_Page/', 'https://sourceforge.net/p/ubuntuzilla/wiki/Main_Page/', 3, 1, 0, 0),
(198, 'Ubuntuzilla', 'This is the home of the Ubuntuzilla project, hosts an APT repository with .deb repacks of the latest official release versions of Mozilla Firefox, Mozilla SeaMonkey, and Mozilla Thunderbird. This repository should work on any APT-based distribution, including Ubuntu descendants, and Debian descendants. The project was born on Ubuntu forums, but despite the name is not really specific to Ubuntu.', 'deb http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt all main', '', 'apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2667CA5C', 'all', 'https://sourceforge.net/p/ubuntuzilla/wiki/Main_Page/', 'https://sourceforge.net/p/ubuntuzilla/wiki/Main_Page/', 4, 1, 0, 0),
(199, 'GNS3', 'Join the world\'s largest community of network professionals who rely on GNS3 to build better networks, share ideas and make connections', 'deb http://ppa.launchpad.net/gns3/ppa/ubuntu trusty main\r\n', 'deb-src http://ppa.launchpad.net/gns3/ppa/ubuntu trusty main', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F88F6D313016330404F710FC9A2FD067A2E3EF7B', 'all', 'https://gns3.com', 'https://docs.gns3.com/1QXVIihk7dsOL7Xr7Bmz4zRzTsJ02wklfImGuHwTlaA4/index.html', 1, 1, 0, 0),
(200, 'GNS3', 'Join the world\'s largest community of network professionals who rely on GNS3 to build better networks, share ideas and make connections', 'deb http://ppa.launchpad.net/gns3/ppa/ubuntu xenial main\r\n', 'deb-src http://ppa.launchpad.net/gns3/ppa/ubuntu xenial main', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F88F6D313016330404F710FC9A2FD067A2E3EF7B', 'all', 'https://gns3.com', 'https://docs.gns3.com/1QXVIihk7dsOL7Xr7Bmz4zRzTsJ02wklfImGuHwTlaA4/index.html', 2, 1, 1, 1),
(201, 'GNS3', 'Join the world\'s largest community of network professionals who rely on GNS3 to build better networks, share ideas and make connections', 'deb http://ppa.launchpad.net/gns3/ppa/ubuntu artful main\r\n', 'deb-src http://ppa.launchpad.net/gns3/ppa/ubuntu artful main', 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F88F6D313016330404F710FC9A2FD067A2E3EF7B', 'all', 'https://gns3.com', 'https://docs.gns3.com/1QXVIihk7dsOL7Xr7Bmz4zRzTsJ02wklfImGuHwTlaA4/index.html', 3, 1, 0, 0),
(202, 'Vagrant', 'Vagrant provides the same, easy workflow regardless of your role as a developer, operator, or designer. It leverages a declarative configuration file which describes all your software requirements, packages, operating system configuration, users, and more. ', 'deb https://vagrant-deb.linestarve.com/ any main', '', 'apt-key adv --keyserver pgp.mit.edu --recv-key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4', '', 'https://www.vagrantup.com/', 'https://vagrant-deb.linestarve.com/', 1, 1, 1, 1),
(203, 'Vagrant', 'Vagrant provides the same, easy workflow regardless of your role as a developer, operator, or designer. It leverages a declarative configuration file which describes all your software requirements, packages, operating system configuration, users, and more. ', 'deb https://vagrant-deb.linestarve.com/ any main', '', 'apt-key adv --keyserver pgp.mit.edu --recv-key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4', '', 'https://www.vagrantup.com/', 'https://vagrant-deb.linestarve.com/', 2, 1, 1, 1),
(204, 'Vagrant', 'Vagrant provides the same, easy workflow regardless of your role as a developer, operator, or designer. It leverages a declarative configuration file which describes all your software requirements, packages, operating system configuration, users, and more. ', 'deb https://vagrant-deb.linestarve.com/ any main', '', 'apt-key adv --keyserver pgp.mit.edu --recv-key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4', '', 'https://www.vagrantup.com/', 'https://vagrant-deb.linestarve.com/', 3, 1, 1, 1),
(205, 'Vagrant', 'Vagrant provides the same, easy workflow regardless of your role as a developer, operator, or designer. It leverages a declarative configuration file which describes all your software requirements, packages, operating system configuration, users, and more. ', 'deb https://vagrant-deb.linestarve.com/ any main', '', 'apt-key adv --keyserver pgp.mit.edu --recv-key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4', '', 'https://www.vagrantup.com/', 'https://vagrant-deb.linestarve.com/', 4, 1, 1, 1);

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle `repos`
--
ALTER TABLE `repos`
  ADD PRIMARY KEY (`repo_id`);

--
-- AUTO_INCREMENT für exportierte Tabellen
--

--
-- AUTO_INCREMENT für Tabelle `repos`
--
ALTER TABLE `repos`
  MODIFY `repo_id` int(15) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=206;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
